### ISSUE TITLE
gtk 3.1.2 and windows10  : missing pango.so 

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#1025]
C:\Ruby22\lib\ruby\gems\2.2.0\gems\gtk3-3.1.3-x86-mingw32\sample\misc>ruby
radiobutton.rb
C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require': cannot load such file -- pango.so (LoadError)
        from
C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in

```
ruby -version
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
```

```
C:\Ruby22\lib\ruby\gems\2.2.0\gems\pango-3.1.3-x86-mingw32>dir /b/s  *.so
C:\Ruby22\lib\ruby\gems\2.2.0\gems\pango-3.1.3-x86-mingw32\lib\2.2\pango.so
C:\Ruby22\lib\ruby\gems\2.2.0\gems\pango-3.1.3-x86-mingw32\lib\2.3\pango.so
C:\Ruby22\lib\ruby\gems\2.2.0\gems\pango-3.1.3-x86-mingw32\lib\2.4\pango.so
```

**Comment by glurp** [comment]
on Github, AppVeyor CI seem to do CI on windows platform ....

**Comment by kou** [comment]
Could you try to update your cairo gem?

**Comment by glurp** [comment]
installed  cairo-1.15.7-x86-mingw32.gem
it is Ok !

Thank you,
