### ISSUE TITLE
Clutter-Gdk (Rubygems) Crash with not found typelib.

### ISSUE THREAD

**Issue by Alanzote** [ruby-gnome2/ruby-gnome2#1034]
I've been having a problem on starting up my project with Clutter-Gdk.
`C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.6-x64-mingw32/lib/gobject-introspection/loader.rb:37:in `require': Typelib file for namespace 'ClutterGdk' (any version) not found (GObjectIntrospection::RepositoryError::TypelibNotFound)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.6-x64-mingw32/lib/gobject-introspection/loader.rb:37:in `load'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clutter-gdk-3.1.6-x64-mingw32/lib/clutter-gdk.rb:22:in `<module:ClutterGdk>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clutter-gdk-3.1.6-x64-mingw32/lib/clutter-gdk.rb:20:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clutter-gtk-3.1.6-x64-mingw32/lib/clutter-gtk.rb:18:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from D:/Repos/LURebornPatcher/LURPatcher/src/MainWindow.rb:4:in `<top (required)>'
        from main.rb:3:in `require_relative'
        from main.rb:3:in `<main>'`

It seems that the typelib is missing.

**Comment by kou** [comment]
Thanks for your report.
I've fixed it. The next release ships `ClutterGdk.typelib`.
