### ISSUE TITLE
Invalid argument Cairo::Context when calling render_rsvg_handle

### ISSUE THREAD

**Issue by peret** [ruby-gnome2/ruby-gnome2#1035]
In a Rails application I use code like this to render an SVG to a file:
```
svg = RSVG::Handle.new(data: svg_data)
surface = Cairo::ImageSurface.new(Cairo::FORMAT_ARGB32, width, height)
context = Cairo::Context.new(surface)
context.render_rsvg_handle(svg)

b = StringIO.new
surface.write_to_png(b)
File.write(file_path, b.string)
```

Today I tried updating the rsvg2 gem and now the call to render_rsvg_handle crashes with this exception:
```
ArgumentError: invalid argument Cairo::Context (expect #<Class:0x007fe0b93ec4b0>)
	from /Users/peter/.rvm/gems/ruby-2.3.3@gemset/gems/gobject-introspection-3.1.4/lib/gobject-introspection/loader.rb:575:in `invoke'
	from /Users/peter/.rvm/gems/ruby-2.3.3@gemset/gems/gobject-introspection-3.1.4/lib/gobject-introspection/loader.rb:575:in `block in define_method'
	from /Users/peter/.rvm/gems/ruby-2.3.3@gemset/gems/rsvg2-3.1.4/lib/rsvg2/cairo.rb:24:in `render_rsvg_handle'
```

Looks like it still worked fine in version 3.1.3 and broke with the next release 3.1.4. Maybe it's related to the GObject introspection refactoring? Is this a bug/regression, or is there another way to do this now?

**Comment by kou** [comment]
Thanks for your report.
I've fixed.

Here is a workaround:

```ruby
require "cairo-gobject"
```

**Comment by Kagetsuki** [comment]
*Don't re-open!

I'd just like to leave a note on this. I have mass image converter that's converting thousands of images, and up until recently it worked without issue. To increase conversion speed it's running conversion processes in threads, so at any given time there could be ~16 parallel calls to ```render_svg_handle```. Before all this integration with gobject it worked fine, but now it appears that there's some blocking that causes the rendering or writing process to fail occasionally. I'm trying to diagnose the problem to find where it's originating from, but I'd just like to warn everyone to wrap their code in a begin-rescue-retry (rescue from ```Rsvg::Error::Failed```).
