### ISSUE TITLE
Centos 7 installation : some complements

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#1057]
On CentOS 7, gnome3 installed, I had to install some devel framework :
```
yum install cairo-gobject-devel
yum install gtk+-devel gtk3-devel
yum install gtksourceview3-devel.x86_64

```
Then all works kind.

I don't know where to document that ....
So it is not an issue, sorry :)

**Comment by kou** [comment]
Thanks for your report.
In the next release, you don't need to run `yum install` manually. They are installed automatically.
