### ISSUE TITLE
shange syle of a GtkSourceView

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#1059]
I would like to change the style of colors used by a GtkSourceView, as   'Cobalt'  
or 'Oblivien'... as gedit do it.

For language, there are a Gtk::SourceLanguagesManager,

But for StyleScheme, Gtk::SourceStyleSchemeManager seem missing...
as find at : https://developer.gnome.org/gtksourceviewmm//2.10/classgtksourceview_1_1SourceStyleSchemeManager.html

Is there another way to select e StyleCheme ?

**Comment by kou** [comment]
`GtkSource::StyleSchemeManager` may be what you look for.

**Comment by glurp** [comment]
I got it !
        scm=GtkSource::StyleSchemeManager.new()
        @edit.buffer.style_scheme=scm.get_scheme("oblivion")

Thank you,
