### ISSUE TITLE
Popper get_text and find_text identify different text.

### ISSUE THREAD

**Issue by RonLeapYearBoy** [ruby-gnome2/ruby-gnome2#1060]
**I would expect get_text to return 'nephilim'**

```ruby
  popplerpage.find_text('nephilim').each do |popplerrectangle|  
   puts  "====>>>" + popplerpage.get_text(popplerrectangle)
   end
```

```text
====>>>and fem
```

![nephilim](https://user-images.githubusercontent.com/1864766/28239971-f1fe34d4-6945-11e7-9f2c-45228b9393ae.png)

thanks

**Comment by kou** [comment]
Could you provide a script that can be runnable (instead of code snippet) and a PDF that reproduce your problem?

**Comment by cedlemo** [comment]
@RonLeapYearBoy ,

we just finished the poppler version based on GObject-Introspection instead of the pure C implementation. It would be great to test it with you script.

**Comment by kou** [comment]
poppler gem 3.1.9 has these features.
