### ISSUE TITLE
libgio~1.dll is not a valid Win32 application

### ISSUE THREAD

**Issue by dsisnero** [ruby-gnome2/ruby-gnome2#1064]
using windows ruby
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]

When I try to run the example0.rb from
https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gtk3/sample/tutorial/example-0.rb

I get a popup error that basically says the above 

libgio~1.dll is not a valid Win32 application
![image](https://user-images.githubusercontent.com/6213/28326500-28a1026e-6b9e-11e7-8dd5-acfece306cc3.png)

**Comment by kou** [comment]
What is your cairo gem version?

**Comment by dsisnero** [comment]
c:\Dominic\programming\ruby\try_gtk3\lib>gem list cairo

*** LOCAL GEMS ***

cairo (1.15.9 x64-mingw32, 1.15.5 x64-mingw32)
cairo-gobject (3.1.8 x64-mingw32)

**Comment by kou** [comment]
Uninstall cairo 1.15.5 and try again. It will fix this error.

**Comment by kou** [comment]
No feedback.
