### ISSUE TITLE
poppler: drop codes for Poppler < 0.15.0

### ISSUE THREAD

**Issue by kou** [ruby-gnome2/ruby-gnome2#1070]
Because poppler-glib supports GObject Introspection since 0.15.0.

**Comment by cedlemo** [comment]
I don't know/understand what you want me to do. :(

**Comment by kou** [comment]
Sorry for my less description.
I found some codes that checks Poppler version in `test/` such as `only_poppler_version(0, 7, 2)` and `Poppler::Version.or_later?(0, 9, 0)`. The GI based bindings supports only 0.15.0 or later. So we can remove these needless version check codes.
