### ISSUE TITLE
[gtk3] Gtk::DrawingArea#override_background_color() doesn't change the color

### ISSUE THREAD

**Issue by noanoa07** [ruby-gnome2/ruby-gnome2#1080]
- gtk3 3.1.8
- ruby 2.4.1
- macOS Sierra 10.12.6
- MacBook Air (non-Retina display)

The "**Gtk::DrawingArea#override_background_color()**" method in gtk3 doesn't change the background color.
In gtk2, the "**Gtk::DrawingArea#modify_bg()**" method changes the background color correctly.

Does any suitable method in gtk3?

Sample code;

```
require 'gtk3'

window = Gtk::Window.new
window.set_size_request(400, 350)

cyan   = Gdk::RGBA::new(0, 1.0, 1.0, 1.0)

drawing_area = Gtk::DrawingArea.new
drawing_area.set_size_request(300,300)
drawing_area.override_background_color(:normal, cyan) # doesn't change the color

drawing_area.signal_connect("draw") do
  context = drawing_area.window.create_cairo_context
  context.set_source_rgb(1.0, 0, 0)
  context.arc(150, 150, 150, 0, 2 * Math::PI)
  context.fill
end

fixed = Gtk::Fixed.new
fixed.put(drawing_area, 10, 10)
window.add(fixed)

window.show_all
window.signal_connect("destroy") { Gtk.main_quit }
Gtk.main
```
<img width="300" alt="issue_drawing_2_gtk3" src="https://user-images.githubusercontent.com/1836817/28710211-2599a256-73be-11e7-9f64-bb413bd481b0.png">

```
require 'gtk2'

window = Gtk::Window.new
window.set_size_request(400, 350)

cyan   = Gdk::Color.new(0, 65535, 65535)

drawing_area = Gtk::DrawingArea.new
drawing_area.set_size_request(300,300)
drawing_area.modify_bg(:normal, cyan) # change the color correct

drawing_area.signal_connect("expose_event") do
  context = drawing_area.window.create_cairo_context
  context.set_source_rgb(1.0, 0, 0)
  context.arc(150, 150, 150, 0, 2 * Math::PI)
  context.fill
end

fixed = Gtk::Fixed.new
fixed.put(drawing_area, 10, 10)
window.add(fixed)

window.show_all
window.signal_connect("destroy") { Gtk.main_quit }
Gtk.main
```

<img width="300" alt="issue_drawing_2_gtk2" src="https://user-images.githubusercontent.com/1836817/28711604-1a5fc712-73c3-11e7-8f3b-3bb6e2bd7585.png">

**Comment by cedlemo** [comment]
It seems that the method `Gtk::Widget#override_background_color` is deprecated since v3.16. (https://developer.gnome.org/gtk3/unstable/GtkWidget.html#gtk-widget-override-background-color).

In the link above, you will found another ways to do it.

**Comment by noanoa07** [comment]
Thanks.
But it's difficult for me to understand the way to change the background color in Ruby/GTK3

**Comment by cedlemo** [comment]
Ok,
given that the `Gtk::DrawingArea` is a widget designed to draw on it, it is a peculiar one. The best way is to use the `draw` signal to generate the backrgound of the widget : 

```ruby
require 'gtk3'

window = Gtk::Window.new
window.set_size_request(400, 350)

drawing_area = Gtk::DrawingArea.new
provider = Gtk::CssProvider.new
drawing_area.set_size_request(300,300)

drawing_area.signal_connect("draw") do |widget, cr|
  cyan = Cairo::Color.parse("cyan")
  w = widget.allocated_width
  h = widget.allocated_height
  cr.set_source_rgb(cyan.red, cyan.green, cyan.blue)
  cr.paint
  cr.set_source_rgb(1.0, 0, 0)
  cr.arc(w/2, h/2, w/2, 0, 2 * Math::PI)
  cr.fill
end

fixed = Gtk::Fixed.new
fixed.put(drawing_area, 10, 10)
window.add(fixed)

window.show_all
window.signal_connect("destroy") { Gtk.main_quit }
Gtk.main
```

Look at the C code example here : https://developer.gnome.org/gtk3/stable/GtkDrawingArea.html#GtkDrawingArea.description you can easily find the ruby methodx to use. 

For other widgets, the best way is to use Css customisation : 

```ruby
require "gtk3"

win = Gtk::Window.new
win.signal_connect "destroy" do
  Gtk.main_quit
end

mybutton = Gtk::Button.new(:label => "Does nothing")
mybutton.margin = 10
css_provider = Gtk::CssProvider.new
css_provider.load(data: "button { background-color: cyan; }")
mybutton.style_context.add_provider(css_provider, Gtk::StyleProvider::PRIORITY_USER)
win.add(mybutton)

win.show_all

Gtk.main
```

**Comment by noanoa07** [comment]
Thanks again!
The background color of Gtk::DrawingArea is changed!

I modified a little bit;
("provider = Gtk::CssProvider.new" is not necessary?)

```ruby
require 'gtk3'

window = Gtk::Window.new
window.set_size_request(400, 350)

drawing_area = Gtk::DrawingArea.new
drawing_area.set_size_request(300,300)

drawing_area.signal_connect("draw") do |widget, cr|
  cr.set_source_rgb(0, 1.0, 1.0)
  cr.paint
  cr.set_source_rgb(1.0, 0, 0)
  cr.arc(150, 150, 150, 0, 2 * Math::PI)
  cr.fill
end

fixed = Gtk::Fixed.new
fixed.put(drawing_area, 10, 10)
window.add(fixed)

window.show_all
window.signal_connect("destroy") { Gtk.main_quit }
Gtk.main
```

And one more your Button Css code;
I ran the code. But the color of the Button doesn't seem to change correctly.
I'll write more comment in #1084.

**Comment by cedlemo** [comment]
> ("provider = Gtk::CssProvider.new" is not necessary?)

No, it is an error from me sorry. For the `Gtk::DrawingArea`, you can not use CSS because it is a widget designed to be drawn on it. You just need to use the "draw" signal.
