### ISSUE TITLE
[gtk3] Color setting of the Gtk::Button does not affect

### ISSUE THREAD

**Issue by noanoa07** [ruby-gnome2/ruby-gnome2#1084]
- gtk3 3.1.8
- gtk2 3.1.8
- ruby 2.4.1
- macOS Sierra 10.12.6

In gtk3, the color setting of the Button does not affect compared with in gth2.
(the background color and the label color of the Button)

Is this related to the issue #1080?

Sample code in gtk3;

```ruby
require 'gtk3'

window = Gtk::Window.new
window.set_size_request(300, 200)

button = Gtk::Button.new(:label => 'Button')
button.set_size_request(100, -1)

font = Pango::FontDescription.new('28')
button.override_font(font)

yellow  = Gdk::RGBA::new(1.0, 1.0,   0, 1.0)
cyan    = Gdk::RGBA::new(  0, 1.0, 1.0, 1.0)
green   = Gdk::RGBA::new(  0, 1.0,   0, 1.0)
magenta = Gdk::RGBA::new(1.0,   0, 1.0, 1.0)
white   = Gdk::RGBA::new(1.0, 1.0, 1.0, 1.0)
blue    = Gdk::RGBA::new(  0,   0, 1.0, 1.0)

# background color of the button; only color flashes
button.override_background_color(:normal  , yellow)
button.override_background_color(:prelight,   cyan)
button.override_background_color(:active  ,  green)

# label color of the button
button.override_color(:normal  , magenta)
button.override_color(:prelight,    blue)
button.override_color(:active  ,   white) # not active


fixed = Gtk::Fixed.new
fixed.put(button, 10, 10)
window.add(fixed)

window.show_all
window.signal_connect("destroy") { Gtk.main_quit }
Gtk.main
```
<img width="300" alt="button_1_normal_gtk3" src="https://user-images.githubusercontent.com/1836817/28746270-e53c7830-74c3-11e7-96e0-248de95b11d8.png">  normal;

<img width="300" alt="button_1_prelight_gtk3" src="https://user-images.githubusercontent.com/1836817/28746289-26e6b660-74c4-11e7-823c-7df7a59fe307.png">  prelight (mouse over);

<img width="300" alt="button_1_active_gtk3" src="https://user-images.githubusercontent.com/1836817/28746293-4394b6c2-74c4-11e7-8e3f-8f580d7e3be8.png">  active (pushed);
  

Sample code in gtk2 as a comparison;

```ruby
require 'gtk2'

window = Gtk::Window.new
window.set_size_request(300, 200)

button = Gtk::Button.new('Button')
button.set_size_request(100, -1)

font = Pango::FontDescription.new('28')
button.child.modify_font(font)

yellow  = Gdk::Color.new(65535, 65535,     0)
cyan    = Gdk::Color.new(    0, 65535, 65535)
green   = Gdk::Color.new(    0, 65535,     0)
magenta = Gdk::Color.new(65535,     0, 65535)
white   = Gdk::Color.new(65535, 65535, 65535)
blue    = Gdk::Color.new(    0,     0, 65535)

# background color of the button
button.modify_bg(Gtk::STATE_NORMAL  , yellow)
button.modify_bg(Gtk::STATE_PRELIGHT,   cyan)
button.modify_bg(Gtk::STATE_ACTIVE  ,  green)

# label color of the button
button.child.modify_fg(Gtk::STATE_NORMAL  , magenta)
button.child.modify_fg(Gtk::STATE_PRELIGHT,    blue)
button.child.modify_fg(Gtk::STATE_ACTIVE  ,   white)


fixed = Gtk::Fixed.new
fixed.put(button, 10, 10)
window.add(fixed)

window.show_all
window.signal_connect("destroy") { Gtk.main_quit }
Gtk.main
```

<img width="300" alt="button_1_normal_gtk2" src="https://user-images.githubusercontent.com/1836817/28746315-b1bbf660-74c4-11e7-9b9d-b170f79188d5.png">  normal;

<img width="300" alt="button_1_prelight_gtk2" src="https://user-images.githubusercontent.com/1836817/28746317-c1e5e7c6-74c4-11e7-83f5-bbec81a09160.png">  prelight (mouse over);

<img width="300" alt="button_1_active_gtk2" src="https://user-images.githubusercontent.com/1836817/28746324-d9480fb6-74c4-11e7-9451-4febabf21c9f.png">  active (pushed);

**Comment by cedlemo** [comment]
Please see my previous answer here : https://github.com/ruby-gnome2/ruby-gnome2/issues/1080#issuecomment-318813669

In Gtk3, all the theming stuff *must* be done via a `Gtk::CssProvider` and CSS. see : 

```ruby
require "gtk3"

win = Gtk::Window.new
win.signal_connect "destroy" do
  Gtk.main_quit
end

mybutton = Gtk::Button.new(:label => "Does nothing")
mybutton.margin = 10
css_provider = Gtk::CssProvider.new
css_provider.load(data: "button {background-color: cyan;}\
                         button:hover {background-color: green;}\
                         button:active {background-color: brown;}"
                 )
mybutton.style_context.add_provider(css_provider, Gtk::StyleProvider::PRIORITY_USER)
win.add(mybutton)

win.show_all

Gtk.main
```

Here is a reference about the Css usage with Gtk widgets : https://developer.gnome.org/gtk3/stable/chap-css-overview.html

**Comment by cedlemo** [comment]
@noanoa07 ,

In the CSS, you can configure the font too, like in regular CSS. I didn't add it here.

**Comment by noanoa07** [comment]
@cedlemo ,
Thanks for your code!

I ran. But the color of Button, "cyan, green, brown", only flashes a sec. 
Is this only on my computer?

**Comment by cedlemo** [comment]
My system is ArchLinux and the colors are displayed as expected. Given that I don't have or use Apple products, I can not say that it is related to your computer. Maybe @kou (ping ?) could help you more.

**Comment by noanoa07** [comment]
- gtk3 3.1.8
- ruby 2.3.3 (32bit)
- Windows 7 (64bit)

On Windows, the cedlemo's code does not display the colors of Button as expected, either.

**Comment by kou** [comment]
You need to specify `background-image` like the following:

```ruby
require "gtk3"

win = Gtk::Window.new
win.signal_connect "destroy" do
  Gtk.main_quit
end

mybutton = Gtk::Button.new(:label => "Does nothing")
mybutton.margin = 10
css_provider = Gtk::CssProvider.new
css_provider.load(data: <<-CSS)
button {
  background-image: image(cyan);
}

button:hover {
  background-image: image(green);
}

button:active {
  background-image: image(brown);
}
CSS
mybutton.style_context.add_provider(css_provider, Gtk::StyleProvider::PRIORITY_USER)
win.add(mybutton)

win.show_all

Gtk.main
```

Or you can disable `background-image` like the following:

```ruby
require "gtk3"

win = Gtk::Window.new
win.signal_connect "destroy" do
  Gtk.main_quit
end

mybutton = Gtk::Button.new(:label => "Does nothing")
mybutton.margin = 10
css_provider = Gtk::CssProvider.new
css_provider.load(data: <<-CSS)
button {
  background-color: cyan;
  background-image: none;
}

button:hover {
  background-color: green;
  background-image: none;
}

button:active {
  background-color: brown;
  background-image: none;
}
CSS
mybutton.style_context.add_provider(css_provider, Gtk::StyleProvider::PRIORITY_USER)
win.add(mybutton)

win.show_all

Gtk.main
```

The default GTK+ theme uses `background-image` to set button background. `background-image` has higher priority than `background-color`. So we need to disable the default `background-image` setting to use `background-color`.

FYI: You can inspect GTK+ widget detail interactively by running your GTK+ application with `GTK_DEBUG=interactive` environment variable like the following:

```console
% GTK_DEBUG=interactive ruby your-application.rb
```
See also: https://developer.gnome.org/gtk3/stable/gtk-running.html#interactive-debugging

You can choose the target widget by the most left button in top buttons.

You can inspect the selected target widget by the 2nd left button in top buttons.

You can view the applied CSS by "CSS nodes" mode in the object view.

**Comment by noanoa07** [comment]
@kou
Thanks! they both work as expected.
And so more detailed information.
