### ISSUE TITLE
Some difficulties installing gtk3 on ubuntu 17.10

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#1085]
the ruby installed by ubuntu 17.10 is 2.3, but  gtk3 ( ruby-gtk3 ) is a very old version ( 3.0.1 ?).

So installing last version of ruby / gtk3 don't  work with gem (strange error in dependency of ATK...)

Solution : install rvm (with direct command, not with apt install rvm ...) and then ruby via rvm ,
all work kind.

**Comment by kou** [comment]
Here is a workaround:

```ruby
gem "gtk3"
require "gtk3"
```

**Comment by kou** [comment]
Could you report it to Debian?
@dai-vdr Could you explain to @glurp how to report a problem to Debian?

**Comment by dai-vdr** [comment]
@glurp 
Debian / Ubuntu's ruby-gnome2 version lesser 3.1.8-5 does not provide gemspec.
It maybe occur your strange error in dependency of ATK.

I am not familiar with Ubuntu's package treatment.
So could you please report this issue to [launchpad](https://launchpad.net/ubuntu/+source/ruby-gnome2)?

**Comment by glurp** [comment]
ok I will try with Launchpad :)
