### ISSUE TITLE
Problem with combobox.rb file, as example for gtk3 main.rb - it does not want to start, after left-mouse button double click

### ISSUE THREAD

**Issue by shevegen** [ruby-gnome2/ruby-gnome2#1101]
Some time ago, some months, cedlemo encouraged me to try gtk3 (I have been using ruby + gtk2 mostly for a long time).

I am testing the main.rb menu in the subdirectory right now, the subdirectory is here:

  gtk3/sample/gtk-demo/

So the file in particular is this one here:

  **gtk3/sample/gtk-demo/main.rb**

I am running into a problem with **combobox.rb**:

Here is the particular problem/error that shows up
----

    failed to run demo: ./combobox.rb
    RangeError: integer 94118834137120 too big to convert to `int'
    /Programs/Ruby/2.4.1/lib/ruby/site_ruby/2.4.0/gobject-introspection/loader.rb:576:in `invoke'
    /Programs/Ruby/2.4.1/lib/ruby/site_ruby/2.4.0/gobject-introspection/loader.rb:576:in `block in define_method'
    /Depot/j/rubygnome2-09.09.2017/gtk3/sample/gtk-demo/combobox.rb:102:in `initialize'
    main.rb:181:in `new'
    main.rb:181:in `run_demo_from_file'
    main.rb:367:in `block in run_application'
    /Programs/Ruby/2.4.1/lib/ruby/site_ruby/2.4.0/gobject-introspection/loader.rb:576:in `invoke'
    /Programs/Ruby/2.4.1/lib/ruby/site_ruby/2.4.0/gobject-introspection/loader.rb:576:in `block in define_method'
    main.rb:518:in `<main>'

----

I have no real idea how to resolve this; there is the error though. I have no idea how this happens to be, but perhaps a simple way to work around may be to check to the highest int, or an int that makes sense in this context?

The other examples work, by the way; I can double click and the widget shows up. But with combobox, this is not the case.

For my versions in use, I use most stuff from source, self-compiled including ruby; rubygnome2 github .zip checkout from 9th september 2017 so some days ago.

**Comment by cedlemo** [comment]
@shevegen ,
just to be sure, is it on Windows? 

On Linux, I re-tested and it works (I know, it does not help you much :( ). So maybe it is related to the platform.

**Comment by kou** [comment]
I can confirm it on Debian GNU/Linux.
I've fixed.
