### ISSUE TITLE
Checking for GTK version - simplify Gtk.check_version

### ISSUE THREAD

**Issue by ghost** [ruby-gnome2/ruby-gnome2#1102]
Hello ruby-gnome folks,

In my old legacy code, lots of gtk2 stuff :) - I check for Gtk version like this:

  unless Gtk.check_version?(2, 2, 0)

Now recently I had to try to check for the gtk version in use, e. g. gtk 2 versus
gtk 3. In gtk 3 some of the API changed, and I want to, for the time being, 
stay compatible with both gtk2 and gtk3. So I need checks to query for
the version in use.

I tried this:

  Gtk.check_version(2)
  Gtk.check_version(3)

Thinking that this could suffice ... "if gtk version 2" ... or "if gtk version 3§

However had I get this error:

    ArgumentError: Gtk.check_version: wrong number of arguments (1 for 3)

My proposal is:

May it be possible/wanted to allow Gtk.check_version() to be satisfied with only
one input argument? First one being the major version, e. g. 2 or 3.

If other minor versions, Gtk::MINOR_VERSION and Gtk::MICRO_VERSION is
necessary, these could default to the minimum version that is supported by
ruby-gnome. Or just '0' perhaps.

That way people could use a simpler query to check which Gtk version is
in use, rather than having to specify the other arguments.

Actually the response confuses me a bit :)

    Gtk.check_version(3,220,0) # => "GTK+ version too old (micro mismatch)"
    Gtk.check_version(2,0,0)    # => "GTK+ version too new (major mismatch)"
    Gtk.check_version(3,0,0)   # => nil

I guess I may be using Gtk.check_version incorrectly. Is it not possible to check
whether we may be running gtk2 or gtk3 that way? Anyway please do feel free to
close this issue at any moment in time! A lot of my local knowledgebase is 
semi-outdated. :)

**Comment by cosmo0920** [comment]
How about use `#or_later?` method which is defined in Ruby side:
https://github.com/ruby-gnome2/ruby-gnome2/blob/609018966de7382085df322a5e0e66085885834f/gtk3/lib/gtk3/version.rb#L22
