### ISSUE TITLE
Error: can't load 'gtk3'

### ISSUE THREAD

**Issue by BluePeony** [ruby-gnome2/ruby-gnome2#1104]
Hi there,

I tried to install the ruby-gnome2 in several ways. First I tried the
`sudo gem install gtk3` which returned several errors, then I tried this:
```
 % git clone https://github.com/ruby-gnome2/ruby-gnome2.git
    % cd ruby-gnome2
    % bundle install
    % bundle exec rake gem:build
    % bundle exec rake gem:install
```
But the last step returned several errors as well. Then I downloaded the ruby-gnome2-all-3.1.8.tar.gz and tried this:
```
  % ruby extconf.rb
    % make
    % sudo make install
```
That worked! Now when I open my irb and type `require 'gtk3' `I get this: 
```
irb(main):001:0> require 'atk'
LoadError: cannot load such file -- atk.so
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/atk.rb:11:in `rescue in <top (required)>'
	from /usr/lib/ruby/vendor_ruby/atk.rb:7:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
```
Where is my mistake? Does someone has a hint?

**Comment by cedlemo** [comment]
are you sure you have all the dependencies installed (ie gtk3 libraries ?)
what is your system?
what were the errors with the command `sudo gem install gtk3` ?

**Comment by BluePeony** [comment]
My system is Ubuntu 14.04 (64bit).
Now I uninstalled all gems with `sudo gem uninstall --all`, just to start all over again.
Now when I do `sudo gem install gtk3` I receive this: 
```
Fetching: pkg-config-1.2.7.gem (100%)
Successfully installed pkg-config-1.2.7
Fetching: native-package-installer-1.0.4.gem (100%)
Successfully installed native-package-installer-1.0.4
Fetching: glib2-3.1.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed glib2-3.1.8
Fetching: gobject-introspection-3.1.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed gobject-introspection-3.1.8
Fetching: gio2-3.1.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed gio2-3.1.8
Fetching: atk-3.1.8.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing gtk3:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.4.0/gems/atk-3.1.8/dependency-check
rake2.4 RUBYARCHDIR=/var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/atk-3.1.8 RUBYLIBDIR=/var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/atk-3.1.8
/usr/local/lib/site_ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem rake (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/lib/site_ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /usr/bin/rake2.4:22:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.4.0/gems/atk-3.1.8 for inspection.
Results logged to /var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/atk-3.1.8/gem_make.out
```
So I see, that rake gem is missing. Next: 
`sudo gem install rake` which is installed successfully. Now again: 
`sudo gem install gtk3`
and it works! I get this: 
```
Building native extensions.  This could take a while...
Successfully installed atk-3.1.8
Fetching: cairo-1.15.9.gem (100%)
Building native extensions.  This could take a while...
Successfully installed cairo-1.15.9
Fetching: cairo-gobject-3.1.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed cairo-gobject-3.1.8
Fetching: pango-3.1.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed pango-3.1.8
Fetching: gdk_pixbuf2-3.1.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed gdk_pixbuf2-3.1.8
Fetching: gdk3-3.1.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed gdk3-3.1.8
Fetching: gtk3-3.1.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed gtk3-3.1.8
Parsing documentation for atk-3.1.8
Installing ri documentation for atk-3.1.8
Parsing documentation for cairo-1.15.9
Installing ri documentation for cairo-1.15.9
Parsing documentation for cairo-gobject-3.1.8
Installing ri documentation for cairo-gobject-3.1.8
Parsing documentation for pango-3.1.8
Installing ri documentation for pango-3.1.8
Parsing documentation for gdk_pixbuf2-3.1.8
Installing ri documentation for gdk_pixbuf2-3.1.8
Parsing documentation for gdk3-3.1.8
Installing ri documentation for gdk3-3.1.8
Parsing documentation for gtk3-3.1.8
Installing ri documentation for gtk3-3.1.8
Done installing documentation for atk, cairo, cairo-gobject, pango, gdk_pixbuf2, gdk3, gtk3 after 5 seconds
7 gems installed
```
 Now, when I go to irb and type there: `require 'gtk3'` I get this: 
```
irb(main):001:0> require 'gtk3'
LoadError: cannot load such file -- atk.so
	from /usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/atk.rb:11:in `rescue in <top (required)>'
	from /usr/lib/ruby/vendor_ruby/atk.rb:7:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.4.0/gtk3.rb:18:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
```
And now I am lost. I don't know why the atk.so is missing. I thought that maybe it is necessary to load the atk-library first but `require 'atk' `gives me the same result as `require 'gtk3'`. 

Any ideas?

**Comment by BluePeony** [comment]
UPDATE: tried another way and SPOILER: still does not work... 
1. `sudo gem uninstall --all`
Now, as stated in the README-file:
2. `git clone https://github.com/ruby-gnome2/ruby-gnome2.git`
3. `cd ruby-gnome2`
4. `bundle install`
5. `bundle exec rake gem:build`
6. `bundle exec rake gem:install` That fails due to denied permissions. So I do `sudo bundle exec rake gem:install` and receive an error: 
```
WARNING:  You don't have /home/bluePeony/.gem/ruby/2.4.0/bin in your PATH,
	  gem executables will not run.
Building native extensions.  This could take a while...
Successfully installed glib2-3.1.9
Parsing documentation for glib2-3.1.9
Installing ri documentation for glib2-3.1.9
Done installing documentation for glib2 after 1 seconds
1 gem installed
/usr/bin/ruby2.4 -S gem install --local --user-install gobject-introspection/pkg/gobject-introspection-3.1.9.gem
ERROR:  Could not find a valid gem 'glib2' (= 3.1.9) in any repository
rake aborted!
Command failed with status (2): [/usr/bin/ruby2.4 -S gem install --local --...]
/home/bluePeony/ruby-gnome2/Rakefile:392:in `block (3 levels) in <top (required)>'
/home/bluePeony/ruby-gnome2/Rakefile:391:in `each'
/home/bluePeony/ruby-gnome2/Rakefile:391:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => gem:install
(See full trace by running task with --trace)
```
When I go to `/var/lib/gems/2.4.0/gems` I don't see any glib installed there, but when I go to `/home/bluePeony/.gem/ruby/2.4.0/gems`, there I see glib2-3.1.9. Why is this gem installed here instead of `/var/lib/gems/2.4.0/gems`? Can I change this somehow?

When I try gem environment I see these paths: 
 ```
- GEM PATHS:
     - /var/lib/gems/2.4.0
     - /home/bluePeony/.gem/ruby/2.4.0
     - /usr/share/rubygems-integration/2.4.0
     - /usr/share/rubygems-integration/all

```

Any hints are appreciated.

**Comment by kou** [comment]
It seems that you don't have rake gem:

> ```text
    current directory: /var/lib/gems/2.4.0/gems/atk-3.1.8/dependency-check
rake2.4 RUBYARCHDIR=/var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/atk-3.1.8 RUBYLIBDIR=/var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/atk-3.1.8
/usr/local/lib/site_ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem rake (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/lib/site_ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /usr/bin/rake2.4:22:in `<main>'
```

Try `sudo gem install rake` before `sudo gem install gtk3`.

**Comment by kou** [comment]
It seems that you don't have rake gem:

> ```text
>     current directory: /var/lib/gems/2.4.0/gems/atk-3.1.8/dependency-check
> rake2.4 RUBYARCHDIR=/var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/atk-3.1.8 RUBYLIBDIR=/var/lib/gems/2.4.0/extensions/x86_64-linux/2.4.0/atk-3.1.8
> /usr/local/lib/site_ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem rake (>= 0.a) (Gem::GemNotFoundException)
> 	from /usr/local/lib/site_ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
> 	from /usr/bin/rake2.4:22:in `<main>'
> ```

Try `sudo gem install rake` before `sudo gem install gtk3`.

**Comment by BluePeony** [comment]
Thanks for the idea, but I already did - you can read it just below the error message you quote. After I installed the rake gem I tried again `sudo gem install gtk3` which returned no errors. Great so far. 
But when I try to load gtk3 in ruby with `require 'gtk3'` I get the error
`LoadError: cannot load such file -- atk.so`. I checked, I do have the atk-gem installed. Now I can't figure out what to do with this error message.

**Comment by kou** [comment]
How to install Ruby 2.4 on Ubuntu 14.04? Remove `rake` by `sudo apt purge -V rake`.

**Comment by BluePeony** [comment]
When I do `sudo apt purge -V rake` I get: `Package 'rake' is not installed, so not removed`. When I go to /var/lib/gems/2.4.0/gems I still see rake-12.1.0. Do you know what this `atk.so`-File is and why it is not loaded, when I try to load gtk3 in irb?

You can install ruby 2.4 on Ubuntu 14.04. Look [here: ]( https://www.brightbox.com/blog/2017/01/13/ruby-2-4-ubuntu-packages/)

**Comment by cedlemo** [comment]
Your ruby gems installation seems to be a mess (system installation, local installation and maybe bundle cache installation) :) .

atk is a dependency for gtk3. The `atk.so` is generaly the name of the C extension of the *Atk* lib. The weird part is that the Atk bindings are now pure ruby based on GObject introspection.

Could you do a : 

    gem list --details rake

For example on my system : 

```
gem list --details rake

*** LOCAL GEMS ***

rake (12.0.0)
    Authors: Hiroshi SHIBATA, Eric Hodel, Jim Weirich
    Homepage: https://github.com/ruby/rake
    License: MIT
    Installed at: /home/cedlemo/.gem/ruby/2.4.0

    Rake is a Make-like program implemented in Ruby

rake-compiler (1.0.4, 1.0.3)
    Authors: Kouhei Sutou, Luis Lavena
    Homepage: https://github.com/rake-compiler/rake-compiler
    License: MIT
    Installed at (1.0.4): /home/cedlemo/.gem/ruby/2.4.0
                 (1.0.3): /home/cedlemo/.gem/ruby/2.4.0

    Rake-based Ruby Extension (C, Java) task generator.
```

**Comment by kou** [comment]
1. You failed to install atk gem because Rake related problem.
2. You load wrong atk gem at /usr/lib/ruby/vendor_ruby/atk.rb. Maybe, it's installed by `apt`. It should be removed.
3. The latest atk gem doesn't create and load `atk.so`.

**Comment by BluePeony** [comment]
Well I just followed the installation instructions in the readme file. 
When I type `gem list --details rake`  I get this:

```
*** LOCAL GEMS ***

rake (12.0.0)
    Authors: Hiroshi SHIBATA, Eric Hodel, Jim Weirich
    Homepage: https://github.com/ruby/rake
    License: MIT
    Installed at: /home/bluePeony/.rvm/gems/ruby-2.4.1@global

    Rake is a Make-like program implemented in Ruby
```
I really don't know how to fix the problem.

**Comment by cedlemo** [comment]
Could you try to make local install of the released gtk3 ?

`gem install --user-install rake`
`gem install --user-install gtk3`

**Comment by BluePeony** [comment]
Finally last weekend I managed to get it running this way:
1. Install ruby version manager as explained: [here](https://github.com/rvm/ubuntu_rvm)
2. Install ruby version 2.4 with rvm, see [here](https://github.com/rvm/rvm) how to install different ruby versions: 
3. Switch to ruby 2.4 with `rvm use 2.4`
4. `sudo gem install gtk3`

This might be not the best/cleanest solution but for now I am just glad it works.
Thank you all for your hints and your help.
