### ISSUE TITLE
GLib::IOChannel::create_source(...).set_callback is broken

### ISSUE THREAD

**Issue by kspt-johs** [ruby-gnome2/ruby-gnome2#1106]
As far as I understand GLib's procedure for using non-default contexts is:

1. create source
2. set_callback
3. attach to context

This works as expected for `GLib::Timeout`, and `GLib::Idle`, but `GLib::IOChannel` use a callback function internally that provides more arguments than the other type of source, and the ruby wrapper used by `set_callback` does not take this into account. The actual callback is wrapped correctly by `io_func` when the simplified `add_watch` is used, but the `GLib::Source` created by `create_source` does not pass along information about the fact that this will be called with more arguments than a basic `GSource`.

### Reproducible example
```ruby
require 'glib2'
iochan = GLib::IOChannel.new($stdout.fileno)
mainloop = GLib::MainLoop.new(nil, false)

source = iochan.create_watch(GLib::IOChannel::OUT)
source.set_callback do |src, condition|
  puts "create_watch: #{src.inspect} #{condition.inspect}"
  mainloop.quit
end
source.attach mainloop.context

mainloop.run
```

If you instead use `add_source`, which implicitly use the default context, then it outputs something like:
`create_watch: #<GLib::IOChannel:0x100a130 ptr=0x10ec6a0 own=true> 4`

Expected behavior would be that the more advance API where you are able to use a non-default `MainContext` would work in the same fashion.

Actual behavior is a segfault where the important part is:
`/usr/lib64/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/glib2-3.1.9/glib2.so(+0x2d7c4) [0x7f6653b467c4] rbglib_source.c:136`

### Problem
`source.set_callback` assumes that the source is suppose to call a `GSourceFunc` (i.e. only the user-provided argument). Despite the documentation for [g-source-set-callback](https://developer.gnome.org/glib/unstable/glib-The-Main-Event-Loop.html#g-source-set-callback) stating:

> The exact type of func depends on the type of source; ie. you should not count on func being called with data as its first parameter.

The `source_func` callback wrapper assumes its user-provided argument (the ruby `Proc`) is the first argument, but this argument will be the third for callbacks from the `GSource` returned by `g_io_create_watch`. The first argument is instead a `*GSource` and trying to call this as a `Proc` fails spectacularly.

### Environment
OpenSUSE 42.3
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux-gnu]
glib2 (3.1.9)

**Comment by kou** [comment]
Use `Gio::UnixOutputStream` instead. It's difficult to support the case because `GLib::Source#set_callback` is too generic.

```ruby
require 'gio2'
output = Gio::UnixOutputStream.new($stdout.fileno, false)
context = GLib::MainContext.new
mainloop = GLib::MainLoop.new(context, false)

source = output.create_source do |_output|
  puts "create_source: #{_output.inspect}"
  mainloop.quit
end
source.attach context

mainloop.run
```

**Comment by kspt-johs** [comment]
Okay, I will investigate porting my needs to `Gio` instead of `GLib`.

BTW, what is the use of a source created by `IOChannel::create_watch` if it does not support callback functions? Seems like a previous `Gio` implementation (65f61fa5bc6488fbb5b9ffa3f7f7d81efa1d78a5) for providing the callback to `create_source` functionality could be ported to `IOChannel::create_watch` fairly easy, but I am not familier with native ruby extensions, so there may be resource management problems that I did not take into account.

**Comment by kou** [comment]
I added callback support to `GLib::IOChannel#create_watch`.

**Comment by kspt-johs** [comment]
Great. Looking forward to the next release.
