### ISSUE TITLE
poppler: runtime dependencies are not updated for gi?

### ISSUE THREAD

**Issue by obache** [ruby-gnome2/ruby-gnome2#1107]
In 3.1.9 (Migrated to GObject Introspection bindings), poppler still require cairo>=1.14.0 and gdk_pixbuf2 gem:

https://github.com/ruby-gnome2/ruby-gnome2/blob/800378244c0291a8ef0c6da45a96eca279a60a7d/poppler/Rakefile#L25

But poppler/lib/poppler.rb require `gobject-introspection`, `gio2` and `cairo-gobject`:

https://github.com/ruby-gnome2/ruby-gnome2/blob/800378244c0291a8ef0c6da45a96eca279a60a7d/poppler/lib/poppler.rb#L17-L19

`package.windows` and `package.external_packages` also should be adjusted.

**Comment by kou** [comment]
Thanks. I've updated.
