### ISSUE TITLE
set_size_callback removed from rsvg2

### ISSUE THREAD

**Issue by willbryant** [ruby-gnome2/ruby-gnome2#1114]
The previous no-GI version of rsvg2 had a set_size_callback binding.  The use case we have for this function was that we could override the nominal pixel size at which an SVG would be rendered, so that we could produce a high-DPI rendering suitable for Retina displays.

It would be good to expose this again if possible under the GI bindings.

For our use case, it would be adequate to supply a fixed scale factor.  Perhaps there are other use cases that the callback is better for, though.

**Comment by kou** [comment]
RSVG deprecates it: https://developer.gnome.org/rsvg/2.40/RsvgHandle.html#rsvg-handle-set-size-callback

You can use `Cairo::Context#scale` and `Cairo::Context#render_rsvg_handle()` instead.

**Comment by willbryant** [comment]
Ok, thank you for the advice!

I think the documentation on http://ruby-gnome2.osdn.jp/hiki.cgi?Ruby%2FRSVG is out of date.  Is theer somewhere else I can find documentation for these methods?

**Comment by kou** [comment]
No.
We plan to integrate with YARD but it's not completed yet: https://github.com/ruby-gnome2/yard-gobject-introspection

If you join development of the project, you will get documentation sooner.

**Comment by timdown** [comment]
Bit of a bummer if you want a `Pixbuf`. Unless I'm reading this wrong (and I may well be, I know next to nothing about this stuff), you need do some kind of conversion to create a Pixbuf from a Cairo surface, which seems inefficient. Also no-one seems to be doing it, which makes me suspect I'm doing something wrong.

**Comment by kojix2** [comment]
Hi @timdown 

Do you mean that you want to create a pixbuf from the surface of Cairo?
In that case I think `to_pixbuf` method is useful.
I am sorry if I do not understand exactly what you mean (in polite way).

```ruby
require 'gtk3'

width = 600
height = 400

window = Gtk::Window.new('Cairo to Pixbuf')
window.signal_connect('destroy') { Gtk.main_quit }

surface = Cairo::ImageSurface.new(Cairo::FORMAT_ARGB32, width, height)

def ra
  rand(100) / 100.0
end

cr = Cairo::Context.new(surface)
200.times do
  cr.set_source_rgba(ra, ra, ra, ra)
  cr.circle(rand(width), rand(height), rand(50))
  cr.fill
end
cr.destroy

pixbuf = surface.to_pixbuf(surc_x: 0, src_y: 0, width: width, height: height)

image = Gtk::Image.new
image.pixbuf = pixbuf
window.add image
window.show_all

Gtk.main
```

screenshot. 

![image](https://user-images.githubusercontent.com/5798442/53170691-188b0f80-3624-11e9-8cad-95e10550ad79.png)

**Comment by kojix2** [comment]
But, following Ruby script did not work. 

```ruby
require 'gtk3'

width = 600
height = 400

surface = Cairo::ImageSurface.new(Cairo::FORMAT_ARGB32, width, height)

def ra
  rand(100) / 100.0
end

cr = Cairo::Context.new(surface)
200.times do
  cr.set_source_rgba(ra, ra, ra, ra)
  cr.circle(rand(width), rand(height), rand(50))
  cr.fill
end
cr.destroy

pixbuf = surface.to_pixbuf(surc_x: 0, src_y: 0, width: width, height: height)
```

Here is the error.

```console
Traceback (most recent call last):
cairo2pixbuf.rb:20:in `<main>': undefined method `to_pixbuf' for #<Cairo::ImageSurface:0x000055a61d2ed2b8> (NoMethodError)
```

I do not know the reason for the difference between the two scripts.

**Comment by kou** [comment]
Don't reuse closed issue.
Could you open a new issue?

**Comment by kojix2** [comment]
@kou
Sorry for writing this in the closed page.

My understanding is that you want to use pixbuf data in none-gtk application. That ‘s interesting. I think you might as well write on the new issue page what you want to do with the pixbuf data you create from SVG.

**Comment by timdown** [comment]
I've worked around this by having my code nadger the SVG itself before giving it to RSVG to render.
