### ISSUE TITLE
unable to install gnumeric on Archlinux

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#1118]
It faills to find gnumeric unless I do the following modifications: 

```diff
diff --git a/gnumeric/dependency-check/Rakefile b/gnumeric/dependency-check/Rakefile
index 9f32db772..54cd107b7 100644
--- a/gnumeric/dependency-check/Rakefile
+++ b/gnumeric/dependency-check/Rakefile
@@ -29,8 +29,10 @@ end
 namespace :dependency do
   desc "Check dependency"
   task :check do
+    unless PKGConfig.check_version?("libspreadsheet-1.12")
     unless NativePackageInstaller.install(:debian => "gir1.2-gnumeric")
       exit(false)
     end
+    end
   end
 end
```

I did not understand why it failed before I see this pull request : 
https://github.com/ruby-gnome2/ruby-gnome2/pull/1117#issuecomment-349827269

I don't send you a PR because I am not sure that this solution will work with debian/fedora and other linux distribution.

**Comment by mtasaka** [comment]
Okay for Fedora, verified.  And for redhat/fedora, this can use ``NativePackageInstaller.install(:redhat => "pkgconfig(libspreadsheet-1.12)")``

 (although now I've noticed that Fedora package does not enable gobject-introspection support for goffice and gnumeric... perhaps I have to ask Fedora side maintainer to enable it)

**Comment by mtasaka** [comment]
https://packages.debian.org/sid/amd64/gnumeric/filelist
says debian "gnumeric" package has libspreadsheet-1.12.pc, and "gir1.2-gnumeric" package depends on "gnumeric" according to 
https://packages.debian.org/unstable/gir1.2-gnumeric
 , so this should be okay also for debian.

**Comment by mtasaka** [comment]
> so this should be okay also for debian.

Ah... for debian, the dependency is the opposite, sorry. For debian, when "gnumeric" package is already installed,  ``unless PKGConfig.check_version?`` "fails" (because it is already installed) and ``gir1.2-gnumeric`` won't be installed...

**Comment by kou** [comment]
I used GObjectIntrospection to detect whether `.typelib` exists instead of using `.pc`.

**Comment by cedlemo** [comment]
thanks @kou
