### ISSUE TITLE
ruby 2.5.0 - does it work with ruby gnome?

### ISSUE THREAD

**Issue by shevegen** [ruby-gnome2/ruby-gnome2#1122]
Hello.

I am trying out the new ruby 2.5.0

I use an unusual way to install ruby-gnome2, just directly from the sources; then I usually install native-package-installer, the ruby pkg-config gem and rbcairo. After that, I invoke a custom script called "traverse_install", which usually either runs extconf.rb or just uses oldschool setup.rb

Anyway, the reason I mention is is because it worked fine on the ruby 2.4.x branch and I could use ruby-gnome stuff (I still use gtk2 ... I am so slow and lazy, I am sorry, but I am 100% sure that ruby + ruby-gtk worked for me on 2.4.3).

Now when I run it on ruby 2.5.0, my program called "tabble" (which was inspired by C gtk program tabble, see here http://www.rillion.net/tabble/index.html) I get this error trace back:

```text
        23: from /Users/x/DATA/PROGRAMMING_LANGUAGES/RUBY/src/tabble/bin/tabble:5:in `<main>'
        22: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        21: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        20: from /Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/tabble.rb:1:in `<top (required)>'
        19: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        18: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        17: from /Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/tabble/tabble.rb:20:in `<top (required)>'
        16: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        15: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        14: from /Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/tabble/basic_requires.rb:5:in `<top (required)>'
        13: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        12: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        11: from /Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/gtk_module.rb:1:in `<top (required)>'
        10: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         9: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         8: from /Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/gtk_module/gtk_runner.rb:23:in `<top (required)>'
         7: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         6: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         5: from /Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/gtk_module/gtk_module.rb:18:in `<top (required)>'
         4: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         3: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         2: from /Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/gtk2.rb:11:in `<top (required)>'
         1: from /Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Programs/Ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- gtk2/base (LoadError)
```

Somehow, I get an error related to gtk2/base.

I use a GoboLinux like scheme for my programs, so ruby will reside at /Programs/Ruby/VERSION_HERE

I still have my old 2.4.3 so I was using updatebb and locate to find out
if I have some gtk2/base directories. And indeed, I have.

The output is:

```text
/Programs/Ruby/2.4.3/lib/ruby/site_ruby/2.4.0/gtk2/base.rb
/Programs/Ruby/2.4.3/lib/ruby/site_ruby/2.4.0/gtk2.rb
/Programs/Ruby/2.4.3/lib/ruby/site_ruby/2.4.0/x86_64-linux/gtk2.so
/Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/gtk2
/Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/gtk2.rb
```

So for ruby 2.4.3, I have this directory. But for ruby 2.5.0, I do
not. Is this just a .rb file? If so, perhaps it could be copied no
matter what?

I then had a look at

/Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/

and actually, /Programs/Ruby/2.5.0/lib/ruby/site_ruby/2.5.0/gtk2 was
a file, not a directory. I do not know if this is helpful, but for whatever
reason, the installation did not work on 2.5.0, whereas ruby-gtk works
very well if I use ruby 2.4.3. Sorry to not be able to write a better error
report there. If ruby 2.5.x works for you guys, please feel free to 
close this issue. I may try again at a later time, perhaps with ruby
at the /usr/ hierarchy/prefix instead.

**Comment by kou** [comment]
Can you show how to install gtk2? `ruby extconf.rb && make install`?
And can you show the output of the install command?

**Comment by shevegen** [comment]
Sorry for the late reply Kouhei Sutou,

It actually works fine here now.

I somehow ended up mixing different gtk versions.

I also transitioned into "gem install gtk2/3" which appears
to be better than the old setup.rb.

Closing this now since I think it is resolved; it works
fine for me now.

Thanks!
