### ISSUE TITLE
GtkEntry oversized default margins and padding. CSS does not correct it.

### ISSUE THREAD

**Issue by dark-yux** [ruby-gnome2/ruby-gnome2#1125]
The Gtk::Entry in ruby-gtk3 is very big. I tried to use css with a priority of 800 and even 8000 but it did not shrink. `* {font: 9pt monospace; border-radius: 0px; border-width: 0px; margin: 0px; padding: 0px 0px 3px 3px;}`  This problem does appear in gtk3 python, css works normally.

**Comment by kou** [comment]
Can you show programs that show the problem?

**Comment by dark-yux** [comment]
```
		module Styleable
			def set_style(priority, css)
				provider = Gtk::CssProvider.new
				provider.load(data: css)
				style_context.add_provider(provider, priority)
			end
		end
		class AccelGroup < Gtk::AccelGroup
			def bind(accel, flags = :visible, &call)
				key, mods = Gtk.accelerator_parse(accel)
				connect(key, mods, flags, &call)
			end
		end
		class Cmd < Gtk::Entry
			include Styleable
			def initialize
				super()
				set_style(800, "* {font: 9pt monospace; border-radius: 0px; border-width: 0px; margin: 0px; padding: 0px 0px 3px 3px;}")
				set_placeholder_text("$:")
				configure()
			end
			def configure

			end
		end
```

**Comment by kou** [comment]
Thanks. It works on my environment.
`GTK_DEBUG=interactive` may help you:

```console
% GTK_DEBUG=interactive ruby your-script.rb
```

See also: https://developer.gnome.org/gtk3/stable/gtk-running.html#interactive-debugging

**Comment by cedlemo** [comment]
@dark-yux,

the priority `Gtk::StyleProvider::PRIORITY_USER` should be sufficient. Furthermore what do you found too big ? width, height, font ? you can find a reference of the gtk CSS here:

* https://developer.gnome.org/gtk3/stable/chap-css-overview.html#css-overview

and the CSS node description for a  `GtkEntry` here:

* https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkEntry.description

Maybe you should try something like : 

```css
entry {
...
}
```

and if you do in you code: 

```
my_entry = Gtk::Entry.new
my_entry.name = "css-entry-name"
```

you should be able to write you CSS like this: 

```css
css-entry-name {
  color: red;
}
```

**Comment by dark-yux** [comment]
Does it matter that I'm using GTK 3.22

**Comment by cedlemo** [comment]
It should work with your Gtk version. 

what system are you using ? what gems ? what is your current Gtk theme ?

**Comment by dark-yux** [comment]
```
#1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
abstract (1.0.0)
atk (3.2.1, 3.1.9, 3.1.8, 3.1.6)
bigdecimal (1.3.2, 1.2.8)
bit-packer (0.1.2)
cairo (1.15.10, 1.15.9)
cairo-gobject (3.2.1, 3.1.9, 3.1.8, 3.1.6)
clutter (3.1.9, 3.1.6)
clutter-gdk (3.1.9, 3.1.6)
clutter-gstreamer (3.1.9, 3.1.6)
clutter-gtk (3.1.9, 3.1.6)
devil (0.1.9.5)
did_you_mean (1.0.0)
ffi (1.9.18)
frozen-objects (0.2.0)
gdk3 (3.2.1, 3.1.9, 3.1.8, 3.1.6)
gdk_pixbuf2 (3.2.1, 3.1.9, 3.1.8, 3.1.6)
gif-info (0.1.1)
gio2 (3.2.1, 3.1.9, 3.1.8, 3.1.6)
gist (4.6.1, 4.5.0)
glib2 (3.2.1, 3.1.9, 3.1.8, 3.1.6)
gobject-introspection (3.2.1, 3.1.9, 3.1.8, 3.1.6)
gstreamer (3.1.9, 3.1.6)
gtk3 (3.2.1, 3.1.9, 3.1.8, 3.1.6)
io-console (0.4.6, 0.4.5)
json (2.1.0, 2.0.1, 1.8.3)
mini_portile2 (2.3.0, 2.2.0)
minitest (5.10.3, 5.10.2, 5.9.0)
native-package-installer (1.0.4)
net-telnet (0.1.1)
nokogiri (1.8.1, 1.8.0)
pango (3.2.1, 3.1.9, 3.1.8, 3.1.6)
pkg-config (1.2.8, 1.2.3)
power_assert (1.1.0, 1.0.2, 0.2.7)
psych (2.2.4, 2.1.0)
qml (1.0.2)
qtbindings (4.8.6.4, 4.8.6.3)
rake (12.1.0, 12.0.0, 10.5.0)
rdoc (5.1.0, 4.2.1)
rmagick (2.16.0)
struct-fx (0.1.1)
test-unit (3.2.6, 3.2.4, 3.1.7)
vim-addon-manager (0.5.6)
vte3 (3.2.1, 3.1.9, 3.1.8, 3.1.6)
```
@cedlemo I tried paracite (gtk-debug) like @kou sugested I could not get the bar to shrink. It could be a segfault, or hard coded somewhere. Here is a picture. The ruby one is the one with the dollar sign and the fat bar I'm trying to get rid of.
![2018-01-19-130742_1163x677_scrot](https://user-images.githubusercontent.com/1261573/35164799-d53b491e-fd19-11e7-9e6d-2b50ee75152f.png)

**Comment by cedlemo** [comment]
Please could you try the following script:

```ruby
require "gtk3"

module Styleable
	def set_style(priority, css)
		provider = Gtk::CssProvider.new
		provider.load(data: css)
		style_context.add_provider(provider, priority)
	end
end
class Entry < Gtk::Entry
	include Styleable
	def initialize
		super()
		set_style(Gtk::StyleProvider::PRIORITY_USER,
              "entry {
                      background-color: brown;
                      font: 20pt monospace;
                      border-radius: 10px;
                      border: solid;
                      border-width: 0px;
                      margin: 0px; padding: 0px 0px 3px 3px;}")
		set_placeholder_text("$:")
		configure()
	end
	def configure

	end
end

window = Gtk::Window.new
window.signal_connect("destroy") { Gtk.main_quit }
entry = Entry.new
window.add entry
window.show_all
Gtk.main
```

You should have an entry with big text and a colored background. Does it works ?

What is your Gtk theme ? It does not looks like a standard theme ?

**Comment by dark-yux** [comment]
yes it works as you describe
![2018-01-20-125852_155x64_scrot](https://user-images.githubusercontent.com/1261573/35186412-b7794318-fde1-11e7-8f50-40a6a3cf55aa.png)

**Comment by cedlemo** [comment]
Great, so now we have to figure out why you can not modify your `Gtk::Entry` in your application. Could you try to change the color of the background of the `Gtk::Entry` in your application with the CSS : 

```
"entry {
    background-color: brown;
}
```

**Comment by dark-yux** [comment]
I did and it worked.

**Comment by cedlemo** [comment]
But you still can modify the size/height of your `Gtk::Entry` at the bottom ? The problem does not come from the CSS.

did you set a default size for the window ? I guess that you used a `Gtk::Box` in order to pack your image then your entry. Did you use `mybox.pack_start` or something like that with `:fill` and or `:expand` set to true ?
In the same way try to see if the property "vexpand" like `myentry.vexpand = false`.

**Comment by dark-yux** [comment]
After `@box.pack_start(@cmd, fill: false, expand: false)`  and setting `vexpand` to false my bar is still too big.

**Comment by cedlemo** [comment]
Maybe you simplify:

1. don't fix the size of the main windows ie: don't use `Gtk::Window#set_default_size`
2. use expand and fill to false for all the element you add to your `Gtk::Box`.

Normaly you should be able to have an entry with an height that correspond to the font size.

if not, I can only help you if I see your script.

**Comment by dark-yux** [comment]
I'll come back later.
