### ISSUE TITLE
Dock icon on macOS?

### ISSUE THREAD

**Issue by valentinp72** [ruby-gnome2/ruby-gnome2#1131]
Hello,

I’ve made some search, but I did not find anything, is it possible to set an icon for the application on the dock on macOS (and on other OS), instead of the default one?
Is it also possible to rename the application title?

Thanks!
![capture d ecran 2018-02-10 a 22 06 51](https://user-images.githubusercontent.com/2760679/36066702-cfe27be4-0eae-11e8-9a8d-08a4a45b0132.png)

**Comment by cedlemo** [comment]
I use Linux with Gnome shell and for the icon, I use this method :  [` Gtk::Window#set_icon_name`](https://github.com/cedlemo/topinambour/blob/master/lib/window.rb#L21)
For the name I usually use `Gtk::Window#tittle=` , you can look here https://developer.gnome.org/gtk2/stable/GtkWindow.html#gtk-window-set-title for other functions. The problem is that I don't know if this works on macOS.

**Comment by valentinp72** [comment]
I tried `set_icon_name`, it doesn't work.. I also tried `title` (and set_title()), and it only changes the name at the top of the window...

I also tried your terminal, topinambour, the icon and the name of it are "Ruby" and the exec icon...

![capture d ecran 2018-02-11 a 12 05 40](https://user-images.githubusercontent.com/2760679/36072675-e5caa7ae-0f23-11e8-9995-64a88dfbaf82.png)

**Comment by cedlemo** [comment]
ha Ok, I am not sure that this can be done via Gtk on macOS, from some links I found via Google, they talk about [bundling script](https://www.smooth-code.com/articles/creer-app-mac-avec-script-shell) in .app package. But again I don't know much about macOS.

**Comment by valentinp72** [comment]
Thanks!

It works like a charm! I used Traveling-ruby and a custom script, so now I have a native-like application!
I going to try to do the same with a Linux now!

Thanks!

![capture d ecran 2018-02-18 a 20 24 37](https://user-images.githubusercontent.com/2760679/36355839-cda9742c-14e9-11e8-8be6-cb063498bc2f.png)

![capture d ecran 2018-02-18 a 20 24 48](https://user-images.githubusercontent.com/2760679/36355838-cd82d290-14e9-11e8-93d6-a0d705992649.png)
