### ISSUE TITLE
How to create an .exe from ruby script using gtk3?

### ISSUE THREAD

**Issue by BluePeony** [ruby-gnome2/ruby-gnome2#1132]
Hi,

I built a ruby app using gtk3 library and I need to create an exe for it. How can I do that? I tried rubyscript2exe, which did not work. I guess it's just outdated. Ocra gem also did not work and it seems as it 's not going to work in future too because the dependencies required for gtk3 are too big for ocra: https://github.com/larsch/ocra/issues/120
InnoSetup Mode did not work for me either because it builds a setup script and requires an already existing exe file. 
So my question is: how can I create an exe file from a ruby script which uses gtk3? 
I would appreciate all hints and help.

**Comment by kou** [comment]
"did not work" shows only too small information.

> So my question is: how can I create an exe file from a ruby script which uses gtk3?

You can look into why "did not work" and fix it.
