### ISSUE TITLE
where is Gtk::Grid defined ?

### ISSUE THREAD

**Issue by TitouanT** [ruby-gnome2/ruby-gnome2#1142]
After a quick look at all the gtk3/lib/gtk3/ folder I didn't see any file where it could be defined. 
So I cloned the ruby-gnome2 repo and runed `grep -r "Grid"` to see where it's used and with hope of finding it's declaration :D .

but here is my output:

```
grep -r "Grid"
gtk2/ext/gtk2/rbgtktreeview.c:    /* GtkTreeViewGridLines */
gtk2/ext/gtk2/rbgtktreeview.c:    G_DEF_CLASS(GTK_TYPE_TREE_VIEW_GRID_LINES, "GridLines", RG_TARGET_NAMESPACE);
gtk3/sample/misc/t-gtksocket.rb:    @grid = Gtk::Grid.new
gtk3/sample/misc/button.rb:grid = Gtk::Grid.new
gtk3/sample/misc/builder.ui:    <property name="title">Grid</property>
gtk3/sample/misc/builder.ui:      <object id="grid" class="GtkGrid">
gtk3/sample/gtk-demo/filtermodel.ui:      <object class="GtkGrid" id="grid1">
gtk3/sample/gtk-demo/application.ui:      <object class="GtkGrid">
gtk3/sample/gtk-demo/panes.rb:    @table = Gtk::Grid.new
gtk3/sample/gtk-demo/blendmodes.ui:      <object class="GtkGrid">
gtk3/sample/gtk-demo/blendmodes.ui:              <object class="GtkGrid">
gtk3/sample/gtk-demo/blendmodes.ui:              <object class="GtkGrid">
gtk3/sample/gtk-demo/blendmodes.ui:              <object class="GtkGrid">
gtk3/sample/gtk-demo/stack.ui:      <object class="GtkGrid">
gtk3/sample/gtk-demo/pickers.rb:    @table = Gtk::Grid.new
gtk3/sample/gtk-demo/sizegroup.rb:    table = Gtk::Grid.new
gtk3/sample/gtk-demo/spinbutton.ui:      <object class="GtkGrid">
gtk3/sample/gtk-demo/overlay.rb:    @grid = Gtk::Grid.new
gtk3/sample/gtk-demo/revealer.ui:      <object class="GtkGrid">
gtk3/sample/gtk-demo/dialog.rb:    table = Gtk::Grid.new
gtk3/sample/gtk-demo/listbox.ui:      <object class="GtkGrid" id="grid1">
gtk3/sample/gtk-demo/scale.ui:      <object class="GtkGrid" id="grid1">
gtk3/sample/gtk-demo/theming.ui:  <object class="GtkGrid" id="grid">
gtk3/sample/gtk-demo/messages.txt:167|GTK+ and friends|GTKtoolkit|GtkGrid landed:new container similar to GtkTable without unnecessary restrictions.It does height-for-width geometry management. #gtkhackfest|1287759681|0||0|1
gtk3/sample/tutorial/exampleapp6/prefs.ui:          <object class="GtkGrid" id="grid">
gtk3/sample/tutorial/exampleapp8/prefs.ui:          <object class="GtkGrid" id="grid">
gtk3/sample/tutorial/example-2.rb:  grid = Gtk::Grid.new
gtk3/sample/tutorial/README.md:The following example shows how the `Gtk::Grid` container lets you arrange several buttons:
gtk3/sample/tutorial/README.md:  grid = Gtk::Grid.new
gtk3/sample/tutorial/README.md:    <property name="title">Grid</property>
gtk3/sample/tutorial/README.md:      <object id="grid" class="GtkGrid">
gtk3/sample/tutorial/README.md:          <object class="GtkGrid" id="grid">
gtk3/sample/tutorial/exampleapp7/prefs.ui:          <object class="GtkGrid" id="grid">
gtk3/sample/tutorial/exampleapp9/prefs.ui:          <object class="GtkGrid" id="grid">
gtk3/sample/tutorial/exampleapp10/prefs.ui:          <object class="GtkGrid" id="grid">
gtk3/sample/tutorial/builder.ui:    <property name="title">Grid</property>
gtk3/sample/tutorial/builder.ui:      <object id="grid" class="GtkGrid">
gtk3/lib/gtk3/deprecated.rb:    define_deprecated_const :GridLines, "Gtk::TreeViewGridLines"
gtk3/lib/gtk3/deprecated.rb:    define_deprecated_enums :TreeViewGridLines, 'GRID_LINES'
gtk4/lib/gtk4/deprecated.rb:    define_deprecated_const :GridLines, "Gtk::TreeViewGridLines"
gtk4/lib/gtk4/deprecated.rb:    define_deprecated_enums :TreeViewGridLines, 'GRID_LINES'
clutter/sample/grid-layout.rb:grid_layout = Clutter::GridLayout.new
clutter-gtk/sample/window-test2.rb:table = Gtk::Grid.new
clutter-gtk/sample/test.rb:vbox = Gtk::Grid.new
gtk3-no-gi/sample/gtk-demo/theming.ui:  <object class="GtkGrid" id="grid">
gtk3-no-gi/lib/gtk3/deprecated.rb:    define_deprecated_enums :GridLines, 'GRID_LINES'
gtk3-no-gi/ext/gtk3/rbgtk-tree-view.c:    G_DEF_CLASS(GTK_TYPE_TREE_VIEW_GRID_LINES, "GridLines", RG_TARGET_NAMESPACE);
gtk3-no-gi/ext/gtk3/rbgtk-grid.c:#define RG_TARGET_NAMESPACE cGrid
gtk3-no-gi/ext/gtk3/rbgtk-grid.c:    VALUE RG_TARGET_NAMESPACE = G_DEF_CLASS(GTK_TYPE_GRID, "Grid", mGtk);
```

I also runed `grep -r "class Grid"` to be sure but no more result were found.

I wanted to see the class itself because I am trying to apply a particular spacing every nth col/row of a grid. Does someone know if it's possible or do I have to create sub grids into my grid ?

ps: maybe it's just magic after all... :p

**Comment by cedlemo** [comment]
The bindings are generated at runtime for the most part via gobject-introspection. All the libraries of the Gnome project come with a typelib which is a binary file and a gir file which is a text file (xml). For example on my system there are for Gtk3:
* /usr/lib/girepository-1.0/Gtk-3.0.typelib
* /usr/share/gir-1.0/Gtk-3.0.gir

Those file are generated when they build/compile the library. Now with gobject-introspection, you can have access to a description of the data of the library and you have access to function like  [g_function_info_invoke](https://developer.gnome.org/gi/stable/gi-GIFunctionInfo.html#g-function-info-invoke) which are in fact using libffi. Based on that you can generate either:
* directly the bindings in some files (Haskell)
* or generate them at runtime (ruby).

Here there are to ways to tweak those automatically generated bindings:
* add C extention (look for the ext dir in gtk3 for example)
* add a file/module like in gtk3/lib/gtk3/*.rb

https://developer.gnome.org/gi/stable/
look at the `GObjectIntrospection::Loader` in the gobject-introspection lib.

From a `GIRepository` you can require / load a namespace ("Gtk3") for example with [g_irepository_require](https://developer.gnome.org/gi/stable/GIRepository.html#g-irepository-require) then with the [g_irepository_get_info/g_irepository_get_n_infos](https://developer.gnome.org/gi/stable/GIRepository.html#g-irepository-get-info), you can iterate through all the GIInfos that can be object, structure, interface, functions. The gobject-introspection use those GIInfo and the ruby metaprogrammation possibilities to automatically generate a class from a GObject or a Boxed structure, a method or a module function from a function and so on.

That is what I have understood so far.

**Comment by TitouanT** [comment]
Ok !! Thank you for taking the time to give a such a detailed response ! I am not sure I got it all but I will look into that ASAP :) 
:1st_place_medal:

**Comment by cedlemo** [comment]
@TitouanT, sorry TL;DR; yes the subclass is a good idea, you can look in *gtk3/lib/gtk3/' dir, there are a lot of examples.
