### ISSUE TITLE
Cannot put the same image in multiple widgets

### ISSUE THREAD

**Issue by valentinp72** [ruby-gnome2/ruby-gnome2#1146]
Hello,

For my game, I have a grid (Gtk::Grid) composed of multiple EventBoxes. Each EventBox must display an image (black, white or crossed). This grid can be quite big, so to keep good performances, I added my images in custom EventBox class inside three class variables:

```ruby
class CellButton < Gtk::EventBox

  # AssetsLoader.loadImage returns a Gtk::Image.new(:file => path)
  BLACK_IMAGE = AssetsLoader.loadImage('black_img.png')
  WHITE_IMAGE = AssetsLoader.loadImage('white_img.png')
  CROSS_IMAGE = AssetsLoader.loadImage('cross_img.png')

  def initialize()
    ...
    self.add(BLACK_IMAGE)
    ...
  end

  ..

end
```

The problem is, Gtk doesn't allow me to have the same image in multiple EventBox widgets:
```
Gtk-WARNING **:  Attempting to add a widget with type GtkImage to a container of type
GtkEventBox but this widget is already inside a container of type GtkEventBox, please 
remove the widget from its existing container first.
```

I don't want to load the images for each **CellButton**... :(
How can I dow load the images only once, and display them inside different widgets?

Thanks,
Valentin

**Comment by pterjan** [comment]
I am not familiar with AssetsLoader but a GtkImage is more than the image, it's a widget to display an image. The underlying image is a GtkPixbuf (creating a GtkImage directly from a file is just a convenience method, it loads the GtkPixbuf from the file then creates a GtkImage from it).
What you want to do is to reuse the GtkPixbuf to create new GtkImage.

**Comment by valentinp72** [comment]
Thanks! :)
I now save only a Pixbuf, and create an image with this one for every cell I need! :)
