### ISSUE TITLE
Packager

### ISSUE THREAD

**Issue by arjunmenon** [ruby-gnome2/ruby-gnome2#1150]
Hey
I couldn't find a guide to package an app for distribution.
Can you link one for gtk2 as well as gtk3, both?

Thanks.

**Comment by cedlemo** [comment]
you mean as a gem ?

**Comment by arjunmenon** [comment]
No as an executable. An application. Can we do that for gtk apps built with ruby?

**Comment by shevegen** [comment]
The old way was to to put everything together, including a ruby version (!), and then offer that as a download.

This here was one way for ruby on windows:

https://github.com/larsch/ocra

But I think there was a variant for linux too.

Do you only need it for windows by the way?

I am pretty sure that there used to be one for linux as well but I do not remember which one; and this is many years old, don't kow if that works for gtk3.

**Comment by arjunmenon** [comment]
Linux. I require for linux. I thought packaging would be a straight forward, considering gtk is touted cross platform, there will be tools.

**Comment by cedlemo** [comment]
With Linux its is quite easy, you can share you application in a gem or the hard way, you will have to create package for your distribution. 

For the gem, you just have to put your main script in the /bin directory of your gem and add in your gemspec that you want to export the bin directory too.

For gems that are installed system wide, just install your gem and you will be able to execute your script. 
here are some examples:

* https://github.com/remiprev/teamocil
* https://github.com/cedlemo/topinambour
* https://github.com/cedlemo/gifshouldbedead

Focus on the `s.executables` in the gemspec.

**Comment by arjunmenon** [comment]
Hey
Not looking for a gem. A deb file, for starters. Or an AppImage file, which is cross-platform in the linux world.
If it is not possible for gtk in ruby, what is the no headache substitute.?

**Comment by kou** [comment]
If you're interesting creating a .deb, see https://salsa.debian.org/ruby-team/mikutter/tree/master/debian . It's a .deb for a Ruby + GTK+2 application.

**Comment by arjunmenon** [comment]
Thanks for that link, but I have no prior experience in building packages from obscure templates. Not much comments either, what is going on.
I would need your help in creating an executable package for gtk2/gtk3 apps built with ruby.

**Comment by kou** [comment]
If you don't want to create .deb by yourself.
We recommend that you use gem.

```console
% sudo apt install -y ruby-dev
% sudo gem install your-application
```

is easier than

```console
% (Register your APT repository)
% sudo apt update
% sudo apt install -y your-application
```

for starters.

**Comment by arjunmenon** [comment]
Okay, you guys are to polite to say, this is not for noobs. :wink: 
I get it.
Perhaps you can, in future, add a wiki for this. Or even as a feature to this gem.
Packaging it for all three platforms shouldn't be that trivial. I can't find a reliable source either to know.
