### ISSUE TITLE
"warning: GRC losure invoking callback: already destroyed: (anonymous)" after 3.2.5 update

### ISSUE THREAD

**Issue by tsutsui** [ruby-gnome2/ruby-gnome2#1166]
After updating ruby-gnome2 3.2.5, mikutter emits the following warnings in debug mode:

```
/usr/pkg/share/mikutter/core/mui/cairo_cell_renderer_message.rb:73: warning: GRC
losure invoking callback: already destroyed: (anonymous)
/usr/pkg/share/mikutter/core/lib/uithreadonly.rb:22: warning: GRClosure invoking
 callback: already destroyed: (anonymous)
```

It looks 3.2.4 + https://github.com/ruby-gnome2/ruby-gnome2/commit/559674e97e54baa7095548cb3a3dc6ad718ac3f9 (for #1162) also reproduces these warnings.

As per #372, some functions for GC should be marked?

**Comment by tsutsui** [comment]
Note this issue is originally repored by Akira Ouchi at mikutter redmine:
https://dev.mikutter.hachune.net/issues/1221#note-1

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.
