### ISSUE TITLE
gtk-demo error: Hypertext ( signal_connect {return x} cause error?)

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1177]
gtk-demo error report Text > Hypertext
```bash
/ruby-gnome2/gtk3/sample/gtk-demo$ ruby main.rb
```
When I double clicked Hypertext demo window, it crashed.
This is the error message.
```bash
/ruby-gnome2/gtk3/sample/gtk-demo/hypertext.rb:37:in `block in initialize': unexpected return
	 from gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `invoke'
	 from gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `block in define_method'
	 from main.rb:518:in `<main>'
main.rb: [BUG] Segmentation fault at 0x0000000000000060
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```
Retruing false here
https://github.com/ruby-gnome2/ruby-gnome2/blob/01b94504cf1b3c773d382c7a39ae551e494017a2/gtk3/sample/gtk-demo/hypertext.rb#L37

I tried some simple experiments.
```ruby
require 'gtk3'
w = Gtk::Window.new
w.signal_connect("destroy"){Gtk.main_quit}
b = Gtk::TextView.new
b.signal_connect "event-after" do
  false
end
w.add b
w.show_all
Gtk.main
```
=> OK
```ruby
require 'gtk3'
w = Gtk::Window.new
w.signal_connect("destroy"){Gtk.main_quit}
b = Gtk::TextView.new
b.signal_connect "event-after" do
  return false
end
w.add b
w.show_all
Gtk.main
```
=> crashed (but the error message is different)

It seems that using 'return' in Ruby block is causing the error. 
I tried replacing "return false" with "next". it seems to be OK on my PC.

system:
- Ubuntu 16.04
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- libgtk-3-0 3.18.9-1ubuntu3.3
- ruby gtk3 (3.2.6)

**Comment by kou** [comment]
Thanks.
We should not `return` from signal connect callback.

**Comment by kojix2** [comment]
I confirmed. Thank you.
