### ISSUE TITLE
gtk-demo error: Info Bars

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1178]
gtk-demo error report : Info Bars
```bash
/ruby-gnome2/gtk3/sample/gtk-demo$ ruby main.rb
```
I pressed the "OK" button and crashed.
This is the error message. 
```console
gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:714:in `validate_arguments': Gtk::Widget#destroy: wrong number of arguments (1 for 0)
```
The error occurred here.

https://github.com/ruby-gnome2/ruby-gnome2/blob/01b94504cf1b3c773d382c7a39ae551e494017a2/gtk3/sample/gtk-demo/infobar.rb#L111

block again..
```ruby
      dialog.signal_connect("response") do
        dialog.destroy    # うごく
      end
```

system:
- Ubuntu 16.04
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- libgtk-3-0 3.18.9-1ubuntu3.3
- ruby gtk3 (3.2.6)

**Comment by kou** [comment]
Thanks.
We should use block not `&:destroy` because `Gtk::Widget#destroy` doesn't accept any arguments.

**Comment by kojix2** [comment]
I confirmed. Thank you!
