### ISSUE TITLE
Error when loading gschema with wayland backend.

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#1182]
I have an application that load settings from a custom gschema like described in https://github.com/ruby-gnome2/ruby-gnome2/tree/master/gtk3/sample/tutorial#define-and-store-settings-for-an-application-with-gschemas and I have a strange issue with the wayland backend:

I know it is a wayland backend because of the following environment variables: `$DISPLAY=:0` and `$WAYLAND_DISPLAY=wayland-0`.

 When I run my application that has been installed as a gem:

```
topinambour                                                               ~

(topinambour:7303): GLib-GIO-ERROR **: 20:15:07.218: Settings schema 'com.github.cedlemo.topinambour' is not installed

[1]    7303 trace trap (core dumped)  topinambour
```

I have the same error when I launch the application in its git local copy with `./bin/topinambour`

In both I tried to use : 
```
Gio::SettingsSchemaSource.new(data_path,
                              Gio::SettingsSchemaSource.default,
                              false)
``` 
instead of using `ENV[GSETTINGS_GSCHEMA_DIR]= data_path` but it did not works neither.

When I run in a local copy of ruby-gnome2 the sample *gtk3/sample/tutorial/exampleapp10* with `ruby exampleapp.rb` it works.

If I set in my .zshrc `export GSETTINGS_GSCHEMA_DIR=a/path/` it works.

I checked with a classical Xorg session : `$DISPLAY=:0` and `$WAYLAND_DISPLAY=` and I can run my application both from the gem installation or from the local copy of the git repository.

Any ideas ?

**Comment by kou** [comment]
How do you instantiate your `Gio::Settings`?
You need to specify the settings schema source:

```ruby
source = Gio::SettingsSchemaSource.new(data_path,
                                       Gio::SettingsSchemaSource.default,
                                       false)
settings = Gio::Settings.new(source)
```

**Comment by cedlemo** [comment]
`Gio::Settings#new` only accepts a string as argument: 

```
/home/cedlemo/.gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:317:in `invoke': no implicit conversion of Gio::SettingsSchemaSource into String
	 from /home/cedlemo/.gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:317:in `block (2 levels) in load_constructor_infos'
	 from /home/cedlemo/.gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:328:in `block in load_constructor_infos'
	 from /home/cedlemo/.gem/ruby/2.5.0/gems/gio2-3.2.6/lib/gio2/settings.rb:23:in `initialize'
	 from /home/cedlemo/Projects/Ruby/topinambour/lib/application.rb:33:in `new'
	 from /home/cedlemo/Projects/Ruby/topinambour/lib/application.rb:33:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `block in define_method'
	 from ./bin/topinambour:54:in `<main>'
```

https://developer.gnome.org/gio/stable/GSettings.html#g-settings-new

**Comment by kou** [comment]
We should impove `Gio::Settings#initialize` to accept the call by `g_settings_new_full()` https://developer.gnome.org/gio/stable/GSettings.html#g-settings-new-full

**Comment by cedlemo** [comment]
I can work on it this weekend if you want. If so, should I take care of all the others constructors ?

```
GSettings *  g_settings_new ()
GSettings *  g_settings_new_with_path ()
GSettings *  g_settings_new_with_backend ()
GSettings *  g_settings_new_with_backend_and_path ()
GSettings *  g_settings_new_full ()
```

**Comment by kou** [comment]
Thanks! Yes!
`Hash` style is better such as `Gio::Settings.new(:source => source)` (it uses `g_settings_new_full()`).
