### ISSUE TITLE
gtk-demo error: Icon View/Editing and Drag-and-Drop

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1183]
gtk-demo error report : Icon View/Editing and Drag-and-Drop
```bash
/ruby-gnome2/gtk3/sample/gtk-demo$ ruby main.rb
```
Crash when editing color labels.
This is the error message. 
```console
gem/ruby/2.5.0/gems/gdk3-3.2.6/lib/gdk3/rgba.rb:34:in `parse': invalid RGBA format: "Cat" (available formats: COLOR_NAME, #RGB, #RRGGBB, #RRRGGGBBB, #RRRRGGGGBBBB, rgb(R, G, B), rgba(R, G, B, A))
```
The computer says it does not know the color of the cat. I think that computers do not have imagination. That is natural.
But I do not like crash messages.

**Comment by kou** [comment]
Thanks!!
I've fixed.

**Comment by kojix2** [comment]
I checked it. Thank you!
