### ISSUE TITLE
gtk-demo error: Popovers

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1184]
gtk-demo error report: Popovers
```bash
/ruby-gnome2/gtk3/sample/gtk-demo$ ruby main.rb
```
Cannot run popvers demo. 
This is the error message.
```console
Gtk-ERROR **: failed to add UI: .:62:50 Invalid property: GtkScrolledWindow.max_content_height
```
The following issue was helpful.
https://github.com/dino/dino/issues/11
> Dino uses GtkScrolledWindow.max_content_height, which requires GTK 3.22. 

Updating gtk will solve the problem. Ubuntu's default Gtk is old.

system:

- Ubuntu 16.04
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- libgtk-3-0 3.18.9-1ubuntu3.3
- ruby gtk3 (3.2.6)

**Comment by kou** [comment]
Thanks!!!
I've add a workaround for GTK+ 3.18.

**Comment by kojix2** [comment]
Thank you very much.
