### ISSUE TITLE
Currently selected radio button

### ISSUE THREAD

**Issue by arjunmenon** [ruby-gnome2/ruby-gnome2#1192]
Hey
The tutorial here https://ruby-gnome2.osdn.jp/hiki.cgi?tut-gtk2-btt-radio shows how to set up the radio buttons, but doesn't to tell how to find which got selected

How do I then find which radio button is selected in a group? 
I cant use the first `radio1` to iterate over all others to find which got selected, even though that was set as the group. I have to go over every radio button separately.

I currently have a toggled event on all the buttons and in the tuts it is written it will emit two signals. one which got selected and the one which got deselcted

```ruby
#!/usr/bin/env ruby

require 'gtk2'

window = Gtk::Window.new(Gtk::Window::TOPLEVEL)
window.set_title  "Radio Buttons"
window.border_width = 10
window.signal_connect('delete_event') { Gtk.main_quit }

radio1 = Gtk::RadioButton.new("_I want to be clicked!")
radio2 = Gtk::RadioButton.new(radio1, "_Click me instead!")
radio3 = Gtk::RadioButton.new(radio1, "No! Click _me!")
radio4 = Gtk::RadioButton.new(radio1, "_No! Click me instead!")

vbox = Gtk::VBox.new(false, 5)
vbox.pack_start(radio1, false, true, 0)
vbox.pack_start(radio2, false, true, 0)
vbox.pack_start(radio3, false, true, 0)
vbox.pack_start(radio4, false, true, 0)

label = Gtk::Label.new("which one was clicked?")

vbox.pack_start(label, false, true, 0)

radio1.signal_connect('toggled') {|w| on_select(w)}
radio2.signal_connect('toggled') {|w| on_select(w)}
radio3.signal_connect('toggled') {|w| on_select(w)}
radio4.signal_connect('toggled') {|w| on_select(w)}

def on_select(w)
	puts w.label
end

window.add(vbox)
window.show_all
Gtk.main
```
It throws those signal, but it is extremely unintuitive to find the correct one. what is the proper way?

**Comment by kou** [comment]
It's the proper way.
