### ISSUE TITLE
gtk-demo error: Cursors ( Gdk::Cursor )

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1195]
problem with Gdk :: Cursor

```ruby
require 'gtk3'

a = Gdk::Cursor.new("default")
b = Gdk::Cursor.new("default")
```

Error
```console
gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:317:in `invoke': 
ruby wrapper for this GObject* already exists. (RuntimeError)
```

Due to the above error, once the cursor demo is executed, it can not be executed again.

system:
- Ubuntu 18.04
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- libgtk-3-0 3.22.30-1ubuntu1

**Comment by kou** [comment]
Thanks.
I've fixed.

**Comment by kojix2** [comment]
I confirmed Thank you!
