### ISSUE TITLE
Missing some widgets

### ISSUE THREAD

**Issue by dubst3pp4** [ruby-gnome2/ruby-gnome2#1202]
Hello and sorry if I somehow overlooked some important information, but it seems to me that some widgets are not implemented. I'm looking for GTKSwitch (available since Gtk 3.0) and GTKMenuButton (since 3.6) but I could not find them neither in the docs nor in the sources. Did I miss something?
Thanks for any help!

**Comment by kou** [comment]
We don't have documents of them but you can use both of them.

**Comment by dubst3pp4** [comment]
Oh, good to know! I've looked into the /lib directory of the gtk3 gem and could not find it, so I thought the bindings to the widgets are not implemented... Thanks for the hint!

**Comment by kou** [comment]
We generate bindings dynamically by gobject-introspection gem.
