### ISSUE TITLE
Add css classes to individual widgets

### ISSUE THREAD

**Issue by arjunmenon** [ruby-gnome2/ruby-gnome2#1229]
Hey
I am searching for a simple method to attach css classes/ids to individual widgets.

At present I am doing something like this which will add css to all widgets

```ruby
    provider = Gtk::CssProvider.new
    provider.load(:data => File.read("styles.css"))

    style_context = @window.style_context
    style_context.add_provider(provider, Gtk::StyleProvider::PRIORITY_USER)

    apply_style(container, provider)

..
..
def apply_style(widget, provider)
    style_context = widget.style_context
    style_context.add_provider(provider, Gtk::StyleProvider::PRIORITY_USER)
    return unless widget.respond_to?(:children)
    widget.children.each do |child|
      apply_style(child, provider)
    end
end
```

Now how can I declare classes for individual widgets like GtkEntry or GtkButton, so that I can set color on specific widgets directly like
```css
.button1 {
    color: red;
}

.button2 {
    color: blue;
}
```
and not declare the parent like `GtkButton {color: red;}`, which will apply to all buttons in the window.

I did come across solutions in [C](https://stackoverflow.com/questions/37609381/how-to-set-a-specific-css-class-to-a-widget-in-gtk3-c) and [Python](https://stackoverflow.com/questions/16740949/gtk-cssprovider-how-do-id-based-selectors-work-in-gtk3). Is there a way to do this in Ruby?

**Comment by cedlemo** [comment]
In one of my app, I use the `Gtk::Widget#set_name` method  ([see the C reference here](https://developer.gnome.org/gtk4/3.90/GtkWidget.html#gtk-widget-set-name) then I use the name in the Css file

for example : 

https://github.com/cedlemo/topinambour/blob/master/lib/terminal.rb#L24

and in my Css file : 
https://github.com/cedlemo/topinambour/blob/master/data/topinambour.css#L32

And I load my Css file with a provider : 

```ruby
screen = Gdk::Display.default.default_screen
    @provider = Gtk::CssProvider.new
    Gtk::StyleContext.add_provider_for_screen(screen,
                                              @provider,
                                              Gtk::StyleProvider::PRIORITY_USER)
```

and 

```ruby
   if @settings['custom-css']
      @css_content = File.open(file, 'r').read
      @provider.load(data: @css_content)
    else
      @provider.load(data: '')
    end
```

**Comment by arjunmenon** [comment]
Yup. That solved it. Thanks,

**Comment by arjunmenon** [comment]
Hey on second thoughts, can you give a simple explanation on these two lines, 
```ruby
screen = Gdk::Display.default.default_screen
Gtk::StyleContext.add_provider_for_screen(screen,
                                              @provider,
                                              Gtk::StyleProvider::PRIORITY_USER)
```
What is happening here?

**Comment by cedlemo** [comment]
To well understand this, here is the comments in the official documentation of [`gtk_style_context_add_provider`](https://developer.gnome.org/gtk3/unstable/GtkStyleContext.html#gtk-style-context-add-provider): 

>Adds a style provider to context , to be used in style construction. Note that a style provider added by this function only affects the style of the widget to which context belongs. If you want to affect the style of all widgets, use gtk_style_context_add_provider_for_screen().
Note: If both priorities are the same, a GtkStyleProvider added through this function takes precedence over another added through gtk_style_context_add_provider_for_screen().

With this function, you link a provider to a context from a widget. If you want that your provider (that will load your Css) affect all the application, you will have to use `Gtk::StyleContext.add_provider_for_screen`.
