### ISSUE TITLE
pango crash by "object allocation during garbage collection phase"

### ISSUE THREAD

**Issue by tsutsui** [ruby-gnome2/ruby-gnome2#1231]
As noted in #1230, ruby-gnome2 3.2.7 + https://github.com/ruby-gnome2/ruby-gnome2/commit/8816bbd86de838a7de18df8649847fb6586ddb4d change triggers coredump of ruby which runs mikutter 3.7.2. The crash seems to happen on drawing tweet by pango and cairo.

A crash log and gdb trace (no debug info) are attached.
[mikutter-crash-log.txt](https://github.com/ruby-gnome2/ruby-gnome2/files/2159961/mikutter-crash-log.txt)
[mikutter-crash-gdb-trace.txt](https://github.com/ruby-gnome2/ruby-gnome2/files/2159963/mikutter-crash-gdb-trace.txt)

**Comment by tsutsui** [comment]
gdb trace with glib2 gem built with --enable-debug-build:
[mikutter-crash-gdb-trace-enable-debug-build.txt](https://github.com/ruby-gnome2/ruby-gnome2/files/2160102/mikutter-crash-gdb-trace-enable-debug-build.txt)

**Comment by kou** [comment]
Thanks.
I've fixed it by https://github.com/ruby-gnome2/ruby-gnome2/commit/ec4160b4f4c5432c6ff8a9e962e7ffeacfd48869. Can you try it?

**Comment by tsutsui** [comment]
The assertion no longer happens and the memory leak reported in #1230 seems also fixed (sometimes VSZ decreases so GC looks working as expected). Thanks.

**Comment by kou** [comment]
Yay!
