### ISSUE TITLE
Trouble with gtk3 and Fibers: `fiber called across stack rewinding barrier`

### ISSUE THREAD

**Issue by LutzLue** [ruby-gnome2/ruby-gnome2#1241]
We are switching our GUI from wxruby to gtk3. Of course we want to keep the changes as small as possible.
Our old implementation relies on Fibers to switch the control flow between GUI and business logic.

Unfortunately when using the old structures with gtk3 I get an error `fiber called across stack rewinding barrier`.

Here is a minimalized sample code, you can reproduce the error with. I will explain some details afterwards.
```

#!/usr/bin/env ruby

require 'gtk3'
require 'fiber'

module Dialog
  def receiver=(fiber)
    @receiver = fiber
  end

  def dialog_return(x = nil)
    @receiver.resume(x) if @receiver
  end

  def dialog(&b)
    catch(:close) {
      while true
        x = Fiber.yield
        b.call(x)
      end
    }
  end
end

class Main_Window
  include Dialog
  def initialize
    @window = Gtk::Window.new
    @button = Gtk::Button.new(:label => "Hello World!")
    @window.add(@button)
    @button.signal_connect("clicked") {
      dialog_return
    }
    @window.show_all
  end
end

class Hello
  include Gtk
  def initialize
    @window = Main_Window.new
    @fiber = Fiber.new {@window.receiver = Fiber.current; main}
    @fiber.resume
  end

  def main
    @window.dialog{
      puts "Hello World"
    }
  end
end

Hello.new
Gtk.main
```

`Main_Window` includes `Dialog`. `Dialog.receiver` holds the Fiber that the windows business logic is supposed to be running in. In the block passed to `Dialog#dialog` we define a behavior of the window. The `yield` in `Dialog#dialog` gives the control flow back to the caller, allowing the GUI to be responsive. A click on the button triggers `Dialog#dialog_return` which is supposed to resume the windows fiber. That should lead to finally calling the block passed to `Dialog#dialog` before.
The expected behaviour in this example would be, that a click on the button `puts` "Hello World". Unfortunately it instead produces the following stack trace:

```
./hello_world.rb:12:in `resume': fiber called across stack rewinding barrier
         from ./hello_world.rb:12:in `dialog_return'
         from ./hello_world.rb:33:in `block in initialize'
         from /home/me/.gem/ruby/2.1.0/gems/gobject-introspection-3.2.7/lib/gobject-introspection/loader.rb:110:in `call'
         from /home/me/.gem/ruby/2.1.0/gems/gobject-introspection-3.2.7/lib/gobject-introspection/loader.rb:110:in `invoke'
         from /home/me/.gem/ruby/2.1.0/gems/gobject-introspection-3.2.7/lib/gobject-introspection/loader.rb:110:in `block in define_singleton_method'
         from ./hello_world.rb:55:in `<main>'
```
Is this a bug in gtk3? Do you have any hints on how to solve this without abandoning the current Fibers-solution?

**Comment by kou** [comment]
You can't use Fiber for the use case.

Why don't you just use `Gtk::MessageDialog`:

```ruby
#!/usr/bin/env ruby

require 'gtk3'

class Main_Window
  def initialize(&block)
    @window = Gtk::Window.new
    @button = Gtk::Button.new(:label => "Hello World!")
    @window.add(@button)
    @button.signal_connect("clicked") {
      dialog = Gtk::MessageDialog.new(parent: @window)
      result = dialog.run
      dialog.destroy
      block.call(result)
    }
    @window.show_all
  end
end

class Hello
  include Gtk
  def initialize
    @window = Main_Window.new do
      puts "Hello World"
    end
  end
end

Hello.new
Gtk.main
```

See also: https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gtk3/sample/gtk-demo/dialog.rb
