### ISSUE TITLE
wrong constant numbers of GLib class

### ISSUE THREAD

**Issue by cobodo** [ruby-gnome2/ruby-gnome2#1244]
https://gist.github.com/cobodo/c9d8104698ed72e497624a46c632c51d
GLib::MINLONG, GLib::MAXLONG, GLib::MININT64 seem to be wrong.

Environment:
* x86_64
* Ubuntu 18.04 on Windows Subsystem for Linux
* Ruby 2.5.1 built by rbenv
* glib2 (both 3.2.9 and master@ac7e510)

**Comment by kou** [comment]
Good catch!
There were more wrong constants.
