### ISSUE TITLE
[gtk3 3.3.0] Install error on Windows 10

### ISSUE THREAD

**Issue by noanoa07** [ruby-gnome2/ruby-gnome2#1247]
Install error occurs on Windows as follows.

- Windows 10 Home 64bit 1809
- Ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
（from rubyinstaller-devkit-2.5.3-1-x64）
- gtk3 3.3.0

-------------------------------------------------------

```console
C:\Users\user0>ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]

C:\Users\user0>gem install gtk3
Temporarily enhancing PATH for MSYS/MINGW...
Installing required msys2 packages: mingw-w64-x86_64-glib2
警告: mingw-w64-x86_64-glib2-2.58.1-1 は最新です -- スキップ
Building native extensions. This could take a while...
ERROR:  Error installing gtk3:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby253-1-x64/lib/ruby/gems/2.5.0/gems/glib2-3.3.0/ext/glib2
C:/Ruby253-1-x64/bin/ruby.exe -r ./siteconf20181103-4660-3wlogw.rb extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Waggregate-return option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wswitch-default option to compiler... yes
checking for -Wswitch-enum option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... no
checking for -Wunsafe-loop-optimizations option to compiler... yes
checking for -Wwrite-strings option to compiler... yes
checking for Windows... yes
checking for gobject-2.0 version (>= 2.12.0)... no
installing 'mingw-w64-x86_64-glib2' native package... succeeded
checking for gobject-2.0 version (>= 2.12.0)... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby253-1-x64/bin/$(RUBY_BASE_NAME)
        --enable-debug-build
        --disable-debug-build
        --with-pkg-config
        --without-pkg-config
        --with-override-variables
        --without-override-variables

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby253-1-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/glib2-3.3.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby253-1-x64/lib/ruby/gems/2.5.0/gems/glib2-3.3.0 for inspection.
Results logged to C:/Ruby253-1-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/glib2-3.3.0/gem_make.out

C:\Users\user0>
```

**Comment by kojix2** [comment]
I get same error.

**Comment by kou** [comment]
Can you update pkg-config gem to 1.3.3 and try again?

**Comment by noanoa07** [comment]
I've update gems, maybe the newest pkg-config is 1.3.2.
Then, `gem install gtk3` is no error! (gtk3 3.3.0)
Thanks!

There are several warnings though.
-------
> gem install gtk3
Temporarily enhancing PATH for MSYS/MINGW...
Installing required msys2 packages: mingw-w64-x86_64-glib2
警告: mingw-w64-x86_64-glib2-2.58.1-1 は最新です -- スキップ
Building native extensions. This could take a while...
Successfully installed glib2-3.3.0
Fetching: gobject-introspection-3.3.0.gem (100%)
Installing required msys2 packages: mingw-w64-x86_64-gobject-introspection
Building native extensions. This could take a while...
Successfully installed gobject-introspection-3.3.0
Fetching: gio2-3.3.0.gem (100%)
Installing required msys2 packages: mingw-w64-x86_64-glib-networking
Building native extensions. This could take a while...
Successfully installed gio2-3.3.0
Fetching: atk-3.3.0.gem (100%)
Installing required msys2 packages: mingw-w64-x86_64-atk
Building native extensions. This could take a while...
Successfully installed atk-3.3.0
Fetching: cairo-1.16.2.gem (100%)
Installing required msys2 packages: mingw-w64-x86_64-cairo
警告: 循環依存が検出されました:
警告: mingw-w64-x86_64-harfbuzz は依存パッケージ mingw-w64-x86_64-freetype の前にインストールされます
Building native extensions. This could take a while...
Successfully installed cairo-1.16.2
Fetching: cairo-gobject-3.3.0.gem (100%)
Building native extensions. This could take a while...
Successfully installed cairo-gobject-3.3.0
Fetching: pango-3.3.0.gem (100%)
Installing required msys2 packages: mingw-w64-x86_64-pango
Building native extensions. This could take a while...
Successfully installed pango-3.3.0
Fetching: gdk_pixbuf2-3.3.0.gem (100%)
Installing required msys2 packages: mingw-w64-x86_64-gdk-pixbuf2
Building native extensions. This could take a while...
Successfully installed gdk_pixbuf2-3.3.0
Fetching: gdk3-3.3.0.gem (100%)
Installing required msys2 packages: mingw-w64-x86_64-gtk3
Building native extensions. This could take a while...
Successfully installed gdk3-3.3.0
Fetching: gtk3-3.3.0.gem (100%)
Building native extensions. This could take a while...
Successfully installed gtk3-3.3.0
Parsing documentation for glib2-3.3.0
Installing ri documentation for glib2-3.3.0
Parsing documentation for gobject-introspection-3.3.0
Installing ri documentation for gobject-introspection-3.3.0
Parsing documentation for gio2-3.3.0
Installing ri documentation for gio2-3.3.0
Parsing documentation for atk-3.3.0
Installing ri documentation for atk-3.3.0
Parsing documentation for cairo-1.16.2
Installing ri documentation for cairo-1.16.2
Parsing documentation for cairo-gobject-3.3.0
Installing ri documentation for cairo-gobject-3.3.0
Parsing documentation for pango-3.3.0
Installing ri documentation for pango-3.3.0
Parsing documentation for gdk_pixbuf2-3.3.0
Installing ri documentation for gdk_pixbuf2-3.3.0
Parsing documentation for gdk3-3.3.0
Installing ri documentation for gdk3-3.3.0
Parsing documentation for gtk3-3.3.0
Installing ri documentation for gtk3-3.3.0
Done installing documentation for glib2, gobject-introspection, gio2, atk, cairo, cairo-gobject, pango, gdk_pixbuf2, gdk3, gtk3 after 15 seconds
10 gems installed

**Comment by kojix2** [comment]
me too :)

**Comment by kou** [comment]
Ah, sorry. 1.3.2 is the latest.
