### ISSUE TITLE
Ruby/RSVG の表記の揺れについて which one is correct? Ruby/Rsvg or Ruby/RSVG

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1252]
こんにちは。
Hello

いま Ruby-Gnome2 の勉強をかねて、プロジェクトページの改良しようと試みています。メーリングリストのアーカイブを見ましたところ数年間停止しているようです。本当は勝手にやるとまずいのかも知れませんが、昔の情報のまま停止しているよりも、ちょこちょこ置き換えていった方がよいだろうということで整理しています。
I am writing a document of Ruby-gnome 2.

そこで小さなことですが、Ruby/RSVG の表記にゆらぎがあることに気が付きました。
Ruby/Rsvg と Ruby/RSVG があります。どちらの方が正しい表記でしょうか。おしえてください。
which one is correct? Ruby/Rsvg or Ruby/RSVG.

**Comment by kou** [comment]
Ruby/RSVG is right.

**Comment by kojix2** [comment]
OK. I got it. Thanks!
