### ISSUE TITLE
example usage of Gdk.threads_add_idle?

### ISSUE THREAD

**Issue by xetum** [ruby-gnome2/ruby-gnome2#1256]
I'n not able to find any example. However there are examples of this method in PyObject. How many arguments does it have? It seems 1. Priority? But then how do I pass the callback? as a block? A bit confused here... Thanks

**Comment by kou** [comment]
It didn't work. I've fixed it. You can use `Gdk.threads_add_idle(GLib::PRIORITY_DEFAULT) {...}` since the next release.

But I don't recommend that you use it because it's removed by GDK4.

**Comment by xetum** [comment]
Just out of curiosity, C declaration is: `gdk_threads_add_idle (GSourceFunc function, gpointer data)`. How do you pass data to the block? Same applies to `Glib.Idle_add`

**Comment by kou** [comment]
You can use closure feature in Ruby as usual:

```ruby
x = "XXX"
GLib::Idle.add do
  p x # You can access x here
  GLib::Source::REMOVE
end
```
