### ISSUE TITLE
Installing gtk 3 on windows

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome2/ruby-gnome2#1265]
Windows で gtk3 をインストールする時に、msys2に先にcairoが入ってないとcairoがないと怒られて止まる場合があるかも(その場合cairo, rcairoは自動インストールされない？）
Installation of Ruby/gtk3 may stop if cairo is not pre-installed. (cairo/rcairo will not be installed automatically.)

それと、これは仕様なのかもしれませんが、gtk3が正常にインストールできたと思った場合でも、何か動かそうとするとrsvg2が無いって怒られるケースがあるかも。（その場でrsvg2入れてしまったので、原因や再現性などは不明です）
You may see a message that rsvg 2 is missing. (It may not be a problem)

いずれも再現性があまりないかもしれませんが報告まで

**Comment by kou** [comment]
If you have already installed rcairo 1.16.1, it may be occurred. Did you have rcairo 1.16.1?

rsvg2 problem has been fixed: #1261

**Comment by kojix2** [comment]
rcairoの方は、その後も色々怒られて、その都度pacmanでインストールしたりしたので最初のrubyinstallerのインストール時に何か問題があったのかも知れません。rsvg2の方は直っていたのですね。ありがとうございます。
