### ISSUE TITLE
test failures with glib 2.59.2

### ISSUE THREAD

**Issue by jbicha** [ruby-gnome2/ruby-gnome2#1272]
glib 2.59.2 uses a non-breaking space instead of a space to separate the quantity and unit in g_format_size() .

See https://gitlab.gnome.org/GNOME/glib/issues/1625

This causes failures with [glib2/test/test-file-utils.rb](https://github.com/ruby-gnome2/ruby-gnome2/blob/master/glib2/test/test-file-utils.rb) .

I'm not sure what the cleanest way to fix this is.

Full test failures
--------------------
https://autopkgtest.ubuntu.com/packages/r/ruby-gnome2/disco/amd64

test failure excerpt
-----------------------
```
Failure: test_gb(TestGLibFileUtils::#format_size)
/tmp/autopkgtest.K2FEAu/build.6mA/src/glib2/test/test-file-utils.rb:61:in `test_gb'
     58:     end
     59: 
     60:     def test_gb
  => 61:       assert_equal("1.0 GB", GLib.format_size(1000 * 1000 * 1000))
     62:     end
     63: 
     64:     def test_over_guint32_value
<"1.0 GB"> expected but was
<"1.0 GB">

diff:
? 1.0 GB
?       
```

**Comment by kou** [comment]
Thanks for your report.
ac9762a will fix this.
