### ISSUE TITLE
gtk2 test failure with Ubuntu 19.04

### ISSUE THREAD

**Issue by jbicha** [ruby-gnome2/ruby-gnome2#1275]
ruby-gnome2's gtk2 test recently started failing with Ubuntu 19.04 Alpha.

I believe the trigger is adwaita-icon-theme 3.31.91 which moved the full-color actions icons to "legacy" and now just provides symbolic versions.

I think the automatic -symbolic handling is a gtk3 feature.

Log excerpt
---------------
```
/tmp/autopkgtest.LPH84e/build.IKS/src/gtk2/test/test_gtk_icon_theme.rb:32:in `test_context'
     29:     end
     30: 
     31:     def test_context
  => 32:       assert_operator(@theme.icons("Actions"), :include?, "edit-find")
     33:     end
     34:   end
     35: end
```

Full logs
------------
http://autopkgtest.ubuntu.com/packages/r/ruby-gnome2/disco/amd64

References
---------------
- https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/7f3f91f9
- https://gitlab.gnome.org/GNOME/adwaita-icon-theme/commit/8d12f0a2

(Those are very large commits so will take some time to load.)

**Comment by kou** [comment]
Thanks for your report.
121c016 will fix this.

**Comment by jbicha** [comment]
I apologize for implying that the actions were the only icons to be affected.

It still fails. :cry: 

```
===============================================================================
Failure: test_context(TestGtkIconTheme::TestIcons):
          @theme.icons("Emotes").include?("face-cool")
          |      |               |
          |      |               false
          |      ["face-smile-big-symbolic", "face-raspberry-symbolic", "face-monkey-symbolic", "face-uncertain-symbolic", "face-glasses-symbolic", "face-embarrassed-symbolic", "face-yawn-symbolic", "face-surprise-symbolic", "face-kiss-symbolic", "face-laugh-symbolic", "face-sad-symbolic", "face-shutmouth-symbolic", "face-cool-symbolic", "face-wink-symbolic", "face-tired-symbolic", "face-crying-symbolic", "face-smile-symbolic", "emote-love-symbolic", "face-worried-symbolic", "face-angry-symbolic", "face-devilish-symbolic", "face-angel-symbolic", "face-sick-symbolic", "face-smirk-symbolic", "face-confused-symbolic", "face-plain-symbolic"]
          #<Gtk::IconTheme:0x55b354849b50 ptr=0x55b354c52c00>
/tmp/autopkgtest.rxM1jy/build.YYK/src/gtk2/test/test_gtk_icon_theme.rb:32:in `test_context'
     29:     end
     30: 
     31:     def test_context
  => 32:       assert do
     33:         @theme.icons("Emotes").include?("face-cool")
     34:       end
     35:     end
```

**Comment by kou** [comment]
Oh...
I assumed it works because `@theme.icons.include?("face-cool")` works on Ubuntu 19.04.

6b77339feaaf3c2ef1f203535b905f6d653286e9 will fix this.

**Comment by jbicha** [comment]
Thank you. I confirm that my issue is fixed now.

You could even change line 37 to
```
        @theme.icons("Actions").any? {|name| name.start_with?("edit-find")}
```
to more closely resemble the original test.

Or maybe it's better to just leave things as they are since things work now.

**Comment by kou** [comment]
Thanks for confirming this.
We can leave the test as is. Because icon type isn't important in the test. We can use any (portable) icon in the test.
