### ISSUE TITLE
'sample/misc/cairo-pong.rb' runs slow on macOS

### ISSUE THREAD

**Issue by spoolkitamura** [ruby-gnome2/ruby-gnome2#1278]
This is a matter about 'ruby-gnome2/gtk3/sample/misc/cairo-pong.rb'.

In the case of it runs on macOS, the drawing is quite slower than on Windows or Linux.
But, I move the mouse pointer quickly on macOS, the speed of the drawing becomes fast.

Though I feel it seems to due to Glib::Timeout.add(@speed) or power saving system on macOS, could you please examine the detail about it?
I want to run it the same speed on all operating systems.

I have tried it on following environment.

[Windows10 1809 64bit]
 Ruby 2.4.5
 Ruby/GTK3 3.3.2

[Linux lubuntu 1810]
 Ruby 2.5.1
 Ruby/GTK3 3.3.2

[macOS 10.10(Yosemite)]
 Macbook 12' (Retina display)
 Ruby 2.5.3
 Ruby/GTK3 3.3.2

**Comment by spoolkitamura** [comment]
I do not know the reason well, 
but adding the following statement in the `initialize` method makes drawing on macOS faster.

`GLib :: Idle.add { true }`

Thanks.

**Comment by kou** [comment]
Umm.
I couldn't reproduce this. Maybe, the latest gtk3 gem has solved this.
