### ISSUE TITLE
Strange behaviour for Gtk::Entry - set_text() seems to put the cursor to the very left hand side

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome2/ruby-gnome2#1283]
Hello,

As part of some widgets used for bioinformatics, I needed a widget that allows only nucleotides as input (DNA - represented by the letters A, T, C, G, and also U if we include RNA).

Anyway - I thus needed a Gtk::Entry that would only allow input like the above. I came up with a strange solution, e. g. I will simply only allow input like a t c g u, and keep everything upcased, while also checking for modifier-keys (such as ctrl+x deleting something, rather than just assume that x would be invalid input).

The following minimal example shows what behaviour I found confusing:

    require 'gtk2'

    window = Gtk::Window.new
    hbox = Gtk::HBox.new
    entry = Gtk::Entry.new
    entry.set_text('HELLO WORLD!')
    entry.signal_connect(:key_release_event) { |widget, event|
      widget.set_text(widget.text.upcase)
    }
    hbox.add(entry)
    window.signal_connect(:destroy) { Gtk.main_quit }
    window.add(hbox)
    window.show_all
    Gtk.main

If you input an UPCASED character, such as A or T, on the very right entry of this gtk-entry input, the focus for the GTK will be on the very right side.

IF, however had, you use the same code, yet input a downcased character such as "a" or "t", then the whole line will be upcased (correctly so), yet the focus of the cursor mysteriously jumps to the very left hand side.

To me this is very confusing, because I, as the user, do not do any differently, other than inputting a lower cased character. Compare this to upcased T versus downcased t.

In my opinion this behaviour is either a bug; and even if it is not a bug, it is slightly confusing.

I think the best behaviour would be to actually not change the cursor position at all, so the part where the cursor position jumps to the left most part is IMO a bug (or strange behaviour).

I am not sure if anyone may agree with this assessment, but even if you stand to reason that it is not a bug, to me it is very confusing, because I can not think of a very logical reason as to why the cursor focus should jump to the very left merely because I was using set_text() here on a key press release event. Thanks for reading.

**Comment by kou** [comment]
This is not a GTK bug. It's an application bug.

`set_text` doesn't require the same length text is set. So GTK can't keep cursor position.
Cursor position must keep in application:

```ruby
  position = widget.position
  widget.set_text(widget.text.upcase)
  widget.position = position
```
