### ISSUE TITLE
Gstreamer examples broken / out of date

### ISSUE THREAD

**Issue by kad3nce** [ruby-gnome2/ruby-gnome2#1285]
I am following the [Gstreamer tutorial on the website](https://ruby-gnome2.osdn.jp/hiki.cgi?tut-gst-bins-ghost-pads) and this example is broken. It looks like `#add_ghost_pad` is no longer a method of `Gst::Element`. What would be the current, working equivalent of the below example?

```
element = Gst::ElementFactory.make("autoaudiosrc")
bin = Gst::Bin.new

bin.add(element)

bin.add_ghost_pad(element.get_pad("sink"), "sink")
```

**Comment by kad3nce** [comment]
Here it is:

```ruby
element = Gst::ElementFactory.make('autoaudiosrc')
bin = Gst::Bin.new

bin.add(element)

pad = element.pads.first
ghost_pad = Gst::GhostPad.new('sink', pad)
bin.add_pad(ghost_pad)
```

**Comment by kou** [comment]
Thanks!
