### ISSUE TITLE
gtk3 doesn't compile on macOS

### ISSUE THREAD

**Issue by ViKomprenas** [ruby-gnome2/ruby-gnome2#1287]
I'm on macOS 10.14.5 (Ruby 2.6.3p62), but I think this won't work on any version. `sudo gem install gtk3` gives:

```
linking shared-object gtk3.bundle
clang: error: no such file or directory: 'Carbon'
clang: error: no such file or directory: 'CoreGraphics'
make: *** [gtk3.bundle] Error 1
```

(and also a ton of deprecations, but those probably don't matter much; [full log](https://pastebin.com/DijRR92J))

This seems to be because the Makefile's ldflags erroneously reads (in part) `-framework Cocoa Carbon CoreGraphics`, where it should be `-framework Cocoa -framework Carbon -framework CoreGraphics`. Making that change corrects the issue, but the Makefile is generated somewhere I don't have time to track down right now, and anyway after doing that and manually running `make` I get a different error at runtime that it can't find the library at all, which I assume is just because I didn't properly finish installing it (but `gem install` seems to regenerate the Makefile...) so I can't submit a patch, sorry.

**Comment by kou** [comment]
Could you also show `/usr/local/lib/ruby/gems/2.6.0/gems/gtk3-3.3.6/ext/gtk3/Makefile`?

**Comment by kou** [comment]
How did you install GTK+ itself (not gtk3 gem)? Homebrew?

**Comment by ViKomprenas** [comment]
Homebrew, yes, it lives at `/usr/local/Cellar/gtk+3/3.24.10`. And [here's the Makefile](https://pastebin.com/8GGSP1P2)

**Comment by kou** [comment]
Thanks. Could you also show `pkg-config --libs gtk+-3.0`?

**Comment by ViKomprenas** [comment]
`-L/usr/local/Cellar/gtk+3/3.24.10/lib -L/usr/local/Cellar/pango/1.42.4_2/lib -L/usr/local/Cellar/atk/2.32.0_1/lib -L/usr/local/Cellar/cairo/1.16.0_2/lib -L/usr/local/Cellar/gdk-pixbuf/2.38.1_1/lib -L/usr/local/Cellar/glib/2.60.5/lib -L/usr/local/opt/gettext/lib -lgtk-3 -lgdk-3 -framework Cocoa -framework Carbon -framework CoreGraphics -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl`

**Comment by kou** [comment]
Thanks. Could you also show `grep framework /usr/local/lib/pkgconfig/*.pc`?

**Comment by ViKomprenas** [comment]
[`grep framework /usr/local/lib/pkgconfig/*.pc`](https://pastebin.com/UzpqfnaM)

**Comment by kou** [comment]
Thanks.
This is a bug of pkg-config gem. I'll fix it later.

**Comment by kou** [comment]
I've fixed and released a new version of pkg-config gem.
