### ISSUE TITLE
pango error: assign Pango::Attribute field value

### ISSUE THREAD

**Issue by toshia** [ruby-gnome2/ruby-gnome2#1288]
In pango 1.44.3, I am getting this error.

```
TypeError: class or module required
from /home/toshi/.gem/ruby/2.6.0/gems/gobject-introspection-3.3.6/lib/gobject-introspection/loader.rb:276:in `set_field_value'
```

The test code works fine under 1.43.0.

# Environment

- ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
- ruby-gnome2 3.3.6
- Pango 1.44.3 ([Arch Linux \- pango 1:1\.44\.3\-1 \(x86\_64\)](https://www.archlinux.org/packages/extra/x86_64/pango/))

# Test code

```ruby
underline = Pango::AttrUnderline.new(Pango::Underline::SINGLE)
underline.start_index = 1
```

# Issue in my project

- https://dev.mikutter.hachune.net/issues/1371

**Comment by kou** [comment]
Could you show diff of `/usr/share/gir-1.0/Pango-1.0.gir` between Pango 1.43.0 and 1.44.3?

**Comment by kou** [comment]
Or could you show

```xml
<record name="Attribute" c:type="PangoAttribute">
...
</record>
```

of `/usr/share/gir-1.0/Pango-1.0.gir` of Pango 1.44.3?

**Comment by kou** [comment]
I used Arch Linux Docker image to reproduce this and have been fixed.
I'll release a new version in a few weeks.

Thanks for your report.
