### ISSUE TITLE
test 2.2.4 on windows

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#283]
gtk3
-----
Almost  all work fine, with gtk3.
with this env :
  pkg-config-1.1.5
  glib2-2.2.4
  gobject-introspection-2.2.4
  gio2-2.2.4
  atk-2.2.4
  cairo-1.14.1
  pango-2.2.4
  gdk_pixbuf2-2.2.4
  cairo-gobject-2.2.4
  gdk3-2.2.4
  gtk3-2.2.4
  gtksourceview3-2.2.4

Event
-------
same problem with datas on EventButton as 2.2.3

video
-------
with video , I have this : 
GLib::Error: Typelib file for namespace 'GtkClutter' (any version) not found
on 
  ClutterGtk::Embed.new

```text
d:\usr\Ruby\Ruby200\lib\ruby\gems\2.0.0\gems>gfind clu*2.2.4* -type f -name *.typelib
clutter-2.2.4-x86-mingw32/vendor/local/lib/girepository-1.0/Cally-1.0.typelib
clutter-2.2.4-x86-mingw32/vendor/local/lib/girepository-1.0/Clutter-1.0.typelib
clutter-2.2.4-x86-mingw32/vendor/local/lib/girepository-1.0/Cogl-1.0.typelib
clutter-2.2.4-x86-mingw32/vendor/local/lib/girepository-1.0/Cogl-2.0.typelib
clutter-2.2.4-x86-mingw32/vendor/local/lib/girepository-1.0/CoglPango-1.0.typelib
clutter-2.2.4-x86-mingw32/vendor/local/lib/girepository-1.0/CoglPango-2.0.typelib
clutter-2.2.4-x86-mingw32/vendor/local/lib/girepository-1.0/Json-1.0.typelib
clutter-gstreamer-2.2.4-x86-mingw32/vendor/local/lib/girepository-1.0/ClutterGst-3.0.typelib
clutter-gtk-2.2.4-x86-mingw32/vendor/local/lib/girepository-1.0/GtkClutter-1.0.typelib
```

gtk_demo
------------
Gtk::ItemFactory' scratch the demo
==> 'Gtk::ItemFactory' has been deprecated. Use 'Gtk::UIManager'

*DrawingArea* demo :
   uninitialized constant Gdk::Event::LEAVE_NOTIFY_MASK

*Cairo* demo : many set_source_rgba have no opacity parameter ==>scrach
(in cairo.rb, replace a=nil by a=1 => ok...)

Conclusions
--------------
So I close issues on 2.2.3 / Windows
Sarting in holiday this night, see you in 2015 !

**Comment by kou** [comment]
ref: #279
