### ISSUE TITLE
undefined method `setup_windows' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by empateinfinito** [ruby-gnome2/ruby-gnome2#285]
Hi dear friends
I have this issue, well i try to make a rpm for fedora following the guidelines, but when i try to compile the spec file the terminal give the issues and happen with all gems 
(atk,gdk3,gio2,glib2,pango,gdk_pixbuf2)
in the past i compile the gems and i made rpm for fedora 2.2.3 version and all work fine, well here is the files for us check this.

fedora spec file > http://empateinfinito.web44.net/rubygem/rubygem-gio2.spec
gio2 gem > http://empateinfinito.web44.net/rubygem/gio2-2.2.4.gem
rpmlint output >  http://empateinfinito.web44.net/rubygem/rpmlint
terminal output > http://empateinfinito.web44.net/rubygem/log

i hope this info can be helpfull :)

please excuse my poor english, regards from chile

**Comment by kou** [comment]
No response.
