### ISSUE TITLE
Strange issue with gtk3 and active_support

### ISSUE THREAD

**Issue by michelboaventura** [ruby-gnome2/ruby-gnome2#291]
I'm having a very strange issue with ruby 2.2.0, gtk3 2.2.4 and active_support 4.2.0:

```Ruby
require 'active_support'
require 'gtk3'
=>symbol lookup error: ~/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/atk-2.2.4/atk.so: undefined symbol: rbgobj_define_class
```

But, if I run:
```Ruby
require 'gtk3'
require 'active_support'
```
Everything works fine.

I discovered this while trying to fix another bug, which seems related to me. I used to use Gdk::Event::BUTTON2_PRESS, which is now deprecated, but instead of get the deprecation warning, I get:
```
Exception: private method `const_missing' called for Gdk:Module
/home/michel/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/home/michel/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
/home/michel/.gem/ruby/2.2.0/gems/glib2-2.2.4/lib/glib2/deprecatable.rb:96:in `const_missing'
```

I think active_support is messing with gtk gem, but I need help make sure. Could you please help me?

Thanks!

**Comment by kou** [comment]
Thanks for your report!

active_support related problem is not gtk3 gem problem. Use `gem "gtk3"; require "gtk3"`, use Bundler or uninstall old glib2 gem to load specific version. See also: #281 

`Gdk::Event::BUTTON2_PRESS` related problem has been fixed at master. Thanks for the report!

Please use `Gdk::EventType::BUTTON2_PRESS` in your code. `Gdk::Event::BUTTON2_PRESS` is deprecated.

**Comment by michelboaventura** [comment]
Thank you Kou. As always, very fast and nice  :)

**Comment by kou** [comment]
:-)
