### ISSUE TITLE
fork_command method for Vte::terminal doesn't work as expected

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#294]
I tried to use the fork_command method like in the test file test_terminal.rb but I cannot use it as expected.

Firstly the constant Vte::PtyFlags::DEFAULT didn't exist, I have to use Vte::Pty::Flags::DEFAULT.

Secondly if I try this (like in the test file):

    flags = Vte::Pty::Flags::DEFAULT
    terminal.fork_command(flags, nil, nil)

I have this error : 

    Vte::Terminal#fork_command(command, argv, envv, directory, lastlog, utmp, wtmp)' style has been deprecated. Use
    #Vte::Terminal#fork_command(:pty_flags => :default, :working_directory => <current>, :argv => <user_shell>, :envv => nil, :spawn_flags => :child_inherits_stdin)

So ok it's just that the tests are not up to date but when I try to use : 

    terminal.fork_command(:pty_flags =>flags, 
                                      :working_directory =>File.dirname(__FILE__), 
                                      :argv => '/usr/bin/fish', 
                                      :envv=>nil, 
                                      :spawn_flags => :child_inherits_stdin )

I have this kind of error:

    /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.4/lib/glib2/deprecatable.rb:47:in `fork_command': malloc: possible integer overflow (ArgumentError)
   from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.4/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'

I am able to have a working terminal/vte if I don't use arguments:

    terminal.fork_command()

Any advices?

**Comment by kou** [comment]
Specify `:argv` as an `Array`:

```ruby
terminal.fork_command(:argv => ['/usr/bin/fish'])
```

**Comment by cedlemo** [comment]
Thanks you,
it works:

    terminal.fork_command(:pty_flags =>flags,
                          :working_directory =>File.dirname(__FILE__),
                          :argv => ['/usr/bin/fish'],
                          :envv=>nil,
                          :spawn_flags => GLib::Spawn::SEARCH_PATH )
