### ISSUE TITLE
Missing Gdk Stuff....

### ISSUE THREAD

**Issue by carlosjhr64** [ruby-gnome2/ruby-gnome2#295]
I did not leave a bug report earlier because it looked like you guys were aware of the problem, but just in case as it appears that it was not a simple "oops, we lost some code here"....
Missing:
  Gdk::Selection::PRIMARY
  Gdk::Selection::CLIPBOARD
  Gdk::Event::BUTTON_PRESS_MASK
Not responding to method:
  Gdk::RGBA.parse
That's just what I'm aware of.  This happened from 2.2.0 to 2.2.1!  :-??  I guess it's not semantic.  So that's on top of the other Gdk issues mentioned by other people earlier.  Looks like the Selection stuff is coming soon.  Looking forward to the next release as I'm waiting on it to upgrade to ruby 2.2.
BTW, thanks for making Gtk available to Ruby!

**Comment by kou** [comment]
Thanks for your report! It's very helpful.

> Gdk::Selection::PRIMARY
> Gdk::Selection::CLIPBOARD

They are already supported at master.

> Gdk::Event::BUTTON_PRESS_MASK

Use Gdk::EventMask::BUTTON_PRESS_MASK instead.

> Gdk::RGBA.parse

I've implemented it at master.

> BTW, thanks for making Gtk available to Ruby!

:-)
