### ISSUE TITLE
Unable to have a working gtk3 gem after compiling it

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#296]
I am trying to install the gtk3 gem and its dependencies like this (I don't want to install all stuff like gnome2):

    ruby extconf.rb glib2 gio2 atk pango gdk_pixbuf2 gdk3 gobject-introspection gtk3
    make
    sudo make install

After the first command I have a message saying gdk3 have been ignored (no extconf.rb)
All the other gem can be installed but the gtk3 module can't not be loaded in ruby because it can't find gtk3.

I have tried to use : 

    ruby extconf.rb glib2 gio2 atk pango gdk_pixbuf2 gdk3-no-gi gobject-introspection gtk3

But that doesn't work either.

I think that I have missed something but I don't know what. Sorry for bothering you for something so simple.

**Comment by kou** [comment]
Try the following:

```text
% rake gem:build
% gem install --local {glib2,gio2,atk,pango,gdk_pixbuf2,gdk3,gobject-introspection,gtk3}/pkg/*-2.2.5.gem
```

**Comment by cedlemo** [comment]
Thank you,
your command line works, I just have to re-order the gems to install:

    %rake gem:build
    %gem install --local {glib2,gobject-introspection,gio2,atk,cairo-gobject,gdk_pixbuf2,pango,gdk3,gtk3}/pkg/*-2.2.5.gem

**Comment by kou** [comment]
Oh, sorry.
