### ISSUE TITLE
gtk3/sample/gtk-demo/main.rb crash when double clicking for launching application

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#297]
I was trying to use the main.rb file and when I click on an item in the gtkTreeView on the left on the interface, the script stop and diplays this message:

    ruby/2.2.0/gems/gtk3-2.2.5/lib/gtk3/tree-store.rb:30:in `get_iter': undefined method `iter?' for #<Gtk::TreeStore:0x39cc720 ptr=0x38a8700>
	 from main.rb:211:in `row_activated_cb'
	 from main.rb:186:in `block in create_tree'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:87:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:87:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:87:in `block (2 levels) in define_module_function'
	 from main.rb:384:in `<main>'

In the main.rb the origin of the problem start at line 185

      tree_view.signal_connect('row_activated') do |tree_view, path, column|
        row_activated_cb(tree_view.model, path)
      end

and at line  211

     def row_activated_cb(model, path)
      iter = model.get_iter(path)
      iter.set_value(ITALIC_COLUMN, true)

the get_iter  metod is defined in gems/gtk3-2.2.5/lib/gtk3/tree-store.rb  :

     def get_iter(path)
      if path.is_a?(String)
        # TODO: fix the method name "iter_from_string?".
        got, iter = iter_from_string?(path)
      else
        # TODO: fix the method name "iter?".
        got, iter = iter?(path)
      end
      if got
        iter.model = self  # workaround
        iter
      else
        nil
      end
    end

I have tried to find a solution ( I think that the iter_from_string? could be replaced by get_iter_from_string) but the path variable is a GtkTreePath instance and I don't find a way to handle this kind of class from the GtkStore class in order to get an iter.

Regards

**Comment by cedlemo** [comment]
For addtionnal informations, this issue depends on the version of the gtk3 lib. It only occurs on my Archlinux system (gtk3 Major 3 Minor 14 Micro 7) and not on a Debian 7.8 ( Gtk3 Major 3 Minor 4 Micro 2) or a Centos 7.0 (Gtk3 Major 3 Minor 8 Micor 8). As the bindings are automaticaly generated with gobject-introspection It's maybe impossible (difficult ) for you to give working demo for every systems.

**Comment by kou** [comment]
Thanks for your report.
I've fixed it. You can also run it on CentOS 7.
