### ISSUE TITLE
problem with check_version in gtk3 samples.

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#304]
I am currently testing samples in the gtk3 directory and lot of them cannot be run because there is a check on the gtk3 version that says that my Gtk 3 version is too recent. A simple grep give me this:

    gtk-demo/builder.rb:      available = Gtk.check_version?(2, 12, 0)
    misc/aboutdialog.rb:if str = Gtk.check_version(2, 6, 0)
    misc/aboutdialog2.rb:if str = Gtk.check_version(2, 6, 0)
    misc/combobox.rb:if str = Gtk.check_version(3, 10, 7)
    misc/composited-windows.rb:if str = Gtk.check_version(2, 12, 0)
    misc/pangorenderer.rb:if str = Gtk.check_version(2, 6, 0)
    misc/statusicon.rb:if str = Gtk.check_version(3, 10, 7)
    misc/textbuffer_serialize.rb:if str = Gtk.check_version(2, 10, 0)
    misc/tooltips.rb:if str = Gtk.check_version(2, 12, 0)
    misc/uimanager.rb:if str = Gtk.check_version(2, 4, 0)
    misc/uimanager.rb:if not Gtk.check_version(2, 12, 0)
    misc/uimanager.rb:if not Gtk.check_version(2, 12, 0)
    misc/uimanager2.rb:if str = Gtk.check_version(2, 4, 0)

The stable version of Gtk3 have a major version of 3 (this is the major version of most linux distribution)s so even with the stable version those samples won't work.

If you give a version number to use I can make the changes from my forked repos of ruby-gnome2.

**Comment by kou** [comment]
Thanks for your contribution!

What is your GTK+ 3 version? You can use your GTK+ 3.

These sample scripts are ported from sample programs in GTK+ 2. We need to upgrade some of them because API is different between GTK+ 2 and GTK+ 3. We may need to remove some of them because some API are removed/deprecated in GTK+ 3. Samples in GTK+ will help you: https://git.gnome.org/browse/gtk+/tree/demos/gtk-demo

**Comment by cedlemo** [comment]
On my Archlinux the Gtk3 version is 3.14.8 which is the latest stable version. On my centos VM Gtk3 is 3.8.8 and on my debian VM Gtk3 is 3.4.2. 
If I use the Archlinux version number, this could be problematic. I have made some test with the version 3.0.12 which is the first gtk3 version with 3 as major number and it works. Maybe I should use this one.

After you validate the Gtk3 version, I plan to check them all and try to update them.

**Comment by kou** [comment]
You can use 3.14.8.
If some samples has any problems with older GTK+, we add version check to these samples. It's the next works. Our first work is making all GTK+ 3 samples workable.

So, go ahead!
