### ISSUE TITLE
pango compilation fail unable to fing rbpangoversion.h

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#306]
Hi,
I wanted to rebuild the latest version of the gems with:

    ruby extconf.rb
    make

    gem install --local {glib2,gobject-introspection,gio2,atk,cairo-gobject,gdk_pixbuf2,pango,gdk3,gtk3}/pkg/*-2.2.5.gem

But the installation failed for pango because the makefile couldn't find any rbpangoversion.h to install.

**Comment by myokoym** [comment]
Hi,

Thanks for your report. I've fix it.
