### ISSUE TITLE
error linked to a recent commit in gtk3/lib/gtk3/loader.rb 

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#307]
When I try to launch gtk3//sample/misc/aboutdialog.rb I have this error:

    initialize_post': undefined method `reference_gobject' for Gtk::Loader:Class (NoMethodError)

That I think is related to this :

https://github.com/ruby-gnome2/ruby-gnome2/commit/e3b0b9d023fd04d13a2ec909f0f1c7474c040f22#diff-599f912520302f84711ba6c5d38fc435

ruby 2.2.0 and gnome gems 2.2.5

**Comment by kou** [comment]
It seems that your gobject-introspection gem is old.
Could you confirm that your gobject-introspection version (revision)?

**Comment by cedlemo** [comment]
gobject-introspection (2.2.5)

**Comment by cedlemo** [comment]
Okaaay,

I have cleaned everything 

    make clean && rm -rf */pkg 

rebuilt every gems then reinstalled everythings and now it works.

Sorry and Thank for your patience with me Kou.

**Comment by kou** [comment]
No problem. :-)
