### ISSUE TITLE
Add XXX::Version.or_later? API

### ISSUE THREAD

**Issue by kou** [ruby-gnome2/ruby-gnome2#308]
`Gtk::Version.or_later?` is more Ruby-ish rather than `Gtk.check_version`. We should provide Ruby-ish methods.

See `Gtk::Version.or_later?` in gtk3 for details.

**Comment by kou** [comment]
Could someone work on this?

**Comment by cedlemo** [comment]
You mean something like this #535 but for the other module?

**Comment by kou** [comment]
> You mean something like this #535 but for the other modules?

Yes.

> If yes give me a list of the modules I should focus on and I will do it.

Thanks! Here is a list:

  * atk
  * clutter-gstreamer
  * clutter-gtk
  * gdk3
  * gdk_pixbuf2
  * gio2
  * glib2
  * gobject-introspection
  * gstreamer
  * gtk2
  * gtksourceview3
  * pango
  * poppler
  * rsvg2
  * webkit-gtk

**Comment by cedlemo** [comment]
Done ?

**Comment by kou** [comment]
Wow!!! Very thanks for your great works!!!
I close this.

**Comment by cedlemo** [comment]
You are welcome! I have learnt a lot, that was fun.
