### ISSUE TITLE
Gtk::ListStore.new(String) segfault

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#311]
I am testing gtk3/sample/misc/listview.rb and it crash at the line : 

    Gtk::ListStore.new(String)

Here is the head of the error message:

    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:278: [BUG] Segmentation fault at 0x00000000000038
    ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
    
    -- Control frame information -----------------------------------------------
    c:0006 p:---- s:0032 e:000031 CFUNC  :invoke
    c:0005 p:0031 s:0028 e:000027 LAMBDA /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:278 [FINISH]
    c:0004 p:0034 s:0024 e:000023 LAMBDA /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:294 [FINISH]
    c:0003 p:---- s:0019 e:000018 CFUNC  :new
    c:0002 p:0188 s:0015 E:0010b8 EVAL   listview.rb:37 [FINISH]
    c:0001 p:0000 s:0002 E:0017c0 TOP    [FINISH]
    
    -- Ruby level backtrace information ----------------------------------------
    listview.rb:37:in `<main>'
    listview.rb:37:in `new'
    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:294:in `block in load_constructor_infos'
    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:278:in `block (2 levels) in load_constructor_infos'
    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb:278:in `invoke'

**Comment by kou** [comment]
I've fixed it.
