### ISSUE TITLE
vte3 and child-exited signal for VteTerminal instance

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#316]
I have written a little script ten days ago that use VteTerminal instances in a notebook with this signal:

    signal_connect "child-exited" do |widget|
      notebook = widget.parent
      current_page = notebook.page_num(widget)
      if notebook.n_pages > 1
        notebook.remove_page(current_page)
        notebook.get_nth_page(notebook.page).grab_focus 
      else
        notebook.remove_page(current_page)
        Gtk.main_quit 
      end
    end

When I used the "exit" command in a terminal, the widget was closed and removed from the notebook and if it was the last widget in the notebook, the main application was closed. All was working as expected.

I tested it yesterday And now when the instructions notebook.remove_page(current_page) is executed, I have this following message:

    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 454
       GLib-GObject-WARNING **:g_object_weak_unref: couldn't find weak ref 0x7f0b15eda470(0x31f4130)
    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 454
       GLib-GObject-WARNING **:instance with invalid (NULL) class pointer
    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 454
       GLib-GObject-CRITICAL **:g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 454
       GLib-GObject-WARNING **:g_object_weak_unref: couldn't find weak ref 0x7f0b15eda470(0x31f4130)
    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 454
       GLib-GObject-WARNING **:instance with invalid (NULL) class pointer
    /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 454
       GLib-GObject-CRITICAL **:g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

*    It must be a new change but I don't see how to adapt the code
*    Is it possible to add the exit status in the callback like in C

**Comment by kou** [comment]
Could you show full script?

**Comment by kou** [comment]
FYI: You can use [git bisect](http://git-scm.com/docs/git-bisect) to find a commit that introduces the problem.

**Comment by cedlemo** [comment]
Well here is a simple exemple that reproduce the problem:
```ruby
require "gtk3"
require "glib2"
require "vte3"

def create_term
  terminal = Vte::Terminal.new
  flags = Vte::PtyFlags::DEFAULT
  terminal.fork_command(:pty_flags =>flags, :working_directory =>File.dirname(__FILE__), :argv => ['/usr/bin/fish'], :envv=>nil, :spawn_flags => GLib::Spawn::SEARCH_PATH )
  terminal.signal_connect "child-exited" do |widget|
    notebook = widget.parent
    current_page = notebook.page_num(widget)
    puts current_page
    puts notebook.n_pages
    if notebook.n_pages > 1
      notebook.remove_page(current_page)
      notebook.get_nth_page(notebook.page).grab_focus 
    else
      notebook.remove_page(current_page)
      Gtk.main_quit 
    end
  end
  terminal.show
  return terminal
end
class MyWin < Gtk::Window
  def initialize
    super
    set_title "Center"
    signal_connect "destroy" do 
        Gtk.main_quit 
    end
    set_default_size 250, 200
    set_window_position(Gtk::WindowPosition::CENTER)
    notebook = Gtk::Notebook.new
    3.times do 
      notebook.append_page(create_term)
    end
    add(notebook)
    show_all
  end
end

window = MyWin.new
Gtk.main
```

I will try to use git bisect (thanks for the info by the way) in order to gather more informations for you.

**Comment by cedlemo** [comment]
After investigation with git bisect, it seems that this type of  error appeared after the commit:

https://github.com/ruby-gnome2/ruby-gnome2/commit/0618747f548ea8abf82d56aacaa9c39d2f6f42a9

For information, before this commit, the test script  (the one I have put in the preview comment) throw errors when Gtk.main_quit is called:

```
0
3
0
2
0
1
vte_test_2.rb: line 0
   GLib-GObject-WARNING **:g_object_weak_unref: couldn't find weak ref 0x7fabbcd65470(0x22dd930)
vte_test_2.rb: line 0
   GLib-GObject-WARNING **:g_object_weak_unref: couldn't find weak ref 0x7fabbcd65470(0x22dd930)
vte_test_2.rb: line 0
   GLib-GObject-WARNING **:g_object_weak_unref: couldn't find weak ref 0x7fabbcd65470(0x22dd930)
```


After the commit, those errors disappear but there are errors linked to notebook.remove_page (for which I have created this issue).

**Comment by kou** [comment]
Thanks! I've fixed it at master.
Your `git bisect` result was very helpful.


I don't know why the following warnings are displayed. It may be your script's bug or libvte's bug...

```text
vte_test_2.rb: line 0
   GLib-GObject-WARNING **:g_object_weak_unref: couldn't find weak ref 0x7fabbcd65470(0x22dd930)
vte_test_2.rb: line 0
   GLib-GObject-WARNING **:g_object_weak_unref: couldn't find weak ref 0x7fabbcd65470(0x22dd930)
vte_test_2.rb: line 0
   GLib-GObject-WARNING **:g_object_weak_unref: couldn't find weak ref 0x7fabbcd65470(0x22dd930)
```

**Comment by cedlemo** [comment]
It is not a bug of my script:, if I replace the vte with some buttons, I don't have those warning.

```ruby
require "gtk3"
require "glib2"

def create_textview
  close = Gtk::Button.new(:label => "Close this one", :stock_id => Gtk::Stock::CLOSE)
  close.signal_connect "clicked" do |widget| 
    notebook = widget.parent
    current_page = notebook.page_num(widget)
    if notebook.n_pages > 1
      notebook.remove_page(current_page)
      notebook.get_nth_page(notebook.page).grab_focus 
    else
      notebook.remove_page(current_page)
      Gtk.main_quit 
    end
  end
  close
end
class MyWin < Gtk::Window
  def initialize
    super
    notebook = Gtk::Notebook.new
    set_title "Center"
    signal_connect "destroy" do 
      Gtk.main_quit 
    end
    set_default_size 250, 200
    set_window_position(Gtk::WindowPosition::CENTER)
    3.times do 
      notebook.append_page(create_textview)
    end
    add(notebook)
    show_all
  end
end

window = MyWin.new
Gtk.main
```

I don't think it is a libvte neither because I use my own vte based terminal written in C (https://github.com/cedlemo/Tortosa.git) and I don't have those warnings. Maybe I should create an issue.
