### ISSUE TITLE
rsvg2 handle memory leak

### ISSUE THREAD

**Issue by Kagetsuki** [ruby-gnome2/ruby-gnome2#318]
We've found a pretty heavy memory leak in rsvg2. To test it yourself grab an svg file and run the following code:

```ruby
800.times do
  handle = RSVG::Handle.new_from_file("./test.svg")
  handle.close
end
```

Depending on the complexity of the svg file 800 times may be pretty heavy. Just this makes memory usage shoot up and it's irrecoverable even with forced garbage collection.

**Comment by kou** [comment]
Thanks for your report!
I've fixed it.

Your script was helpful.

**Comment by Kagetsuki** [comment]
@kou さん、
早っ!
ありがとうございました。

**Comment by kou** [comment]
新しいバージョンがリリースされるまではこんな書き方にしておいてください。これだとメモリーリークしません。

```ruby
require "rsvg2"

handle = RSVG::Handle.new
File.open("/tmp/test.svg", "rb") do |file|
  handle.write(file.read)
end
handle.close
```

**Comment by Kagetsuki** [comment]
@kou さん、
大変申し訳無いんですが、 戻ってませんか?
fb8b62de5d6443a071d3698786de10d52308fe6f の何かでしょうか?
テストしたらまたメモリが漏れている様子です。。。

2.2.5のリリース後に気づいて申し訳ございません。 90a84e2d750b4c6b946ff112402e1791649a9095 を試した所大丈夫だと確信して放置しました。

**Comment by kou** [comment]
あ、2.2.5にはこの変更は入っていないんですよ。
2.2.5は最新のGLibに対応するだけの変更が入っています。

**Comment by Kagetsuki** [comment]
おっとそうでしたか!

実はですね、rsvg2をphantom_svgに愛用してまして、そのphantom_svgがemojidex.comの画像変換のバックグラウンドタスクに使われています。まだユーザーが少ない中であんまり気づかないんですが、アップ毎にメモリが漏れてしまいパンクしてしまうんです。ユーザーが増えれば大変なことになりそうです。。。

@kou さんが勧めるhandleを自作する対策をしてもいいんですが、その場合結構色々自分で設定することになっちゃうんでちょっと面倒くさいです。メモリ開放のパッチが近日入れる予定でなければphantom_svgを調整しますが、どうでしょうか?

**Comment by kou** [comment]
すぐにはリリースできないので↓を当てておいてください！

```diff
diff --git a/lib/phantom/parser/png_writer.rb b/lib/phantom/parser/png_writer.rb
index f96abb4..2905eab 100644
--- a/lib/phantom/parser/png_writer.rb
+++ b/lib/phantom/parser/png_writer.rb
@@ -43,7 +43,15 @@ module Phantom
         def create_temporary_file(path, frame, width, height)
           Parser::SVGWriter.new.write("#{path}.svg", frame)
 
-          handle = RSVG::Handle.new_from_file("#{path}.svg")
+          handle = RSVG::Handle.new
+          File.open("#{path}.svg", "rb") do |file|
+            buffer = ""
+            while file.read(8192, buffer)
+              handle.write(buffer)
+            end
+          end
+          handle.close
+
           Cairo::ImageSurface.new(Cairo::FORMAT_ARGB32, width, height) do |surface|
             Cairo::Context.new(surface) do |context|
               context.scale(width.to_f / handle.dimensions.width,
```

あるいはそのホストにインストールされたrsvg2 gemを直接いじって`lib/rsvg2.rb`の最後に↓を追加しておいてください。

```ruby
module RSVG
  class Handle
    class << self
      alias_method :new_from_file_original, :new_from_file
      def new_from_file(path)
        handle = new

        File.open(path, "rb") do |file|
          buffer = ""
          while file.read(8192, buffer)
            handle.write(buffer)
          end
        end
        handle.close

        handle
      end
    end
  end
end
```

**Comment by Kagetsuki** [comment]
@kou さん、

何度もありがとうございます!

お陰てパッチが直ぐに出来ました。助かりました!
