### ISSUE TITLE
creation of a new instance of Gtk::FileChooserDialog block the execution of the script

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#323]
Whenever a new FileCHooser is created, the main script hangs/freezes with no dialog displayed. When I try to kill /interrupt  with ctrl-C in my terminal , I am not able to stop the process.

```ruby 
require "gtk3"
dialog = Gtk::FileChooserDialog.new(:title => "Choose a file") #it freezes here
dialog.run #the dialog is not displayed
```

For comparison this works for a font chooser:

```ruby
require "gtk3"
dialog = Gtk::FontChooserDialog.new("Pick a font")
dialog.run
```

**Comment by kou** [comment]
I've fixed it.
