### ISSUE TITLE
Gtk::ColorChooserDialog.new positional arguments instead of hash arguments

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#328]
When I have tryed to use Gtk::ColorChooserDialog, I first wrote this (like I did for Gtk::Dialog.new for example) : 

```ruby
    Gtk::ColorChooserDialog.new( :parent => my_main_window, :title => "Pick a color")
```
But this didn't work, the initialize method use positional arguments:

```ruby
     Gtk::ColorChooserDialog.new( my_main_window, "Pick a color")
```

It is not really a bug but I don't find it very consistant. 

Regards

**Comment by kou** [comment]
It's reasonable.
I've implemented the options Hash style.
