### ISSUE TITLE
error installing on windows

### ISSUE THREAD

**Issue by shevegen** [ruby-gnome2/ruby-gnome2#366]
Hi

I have an error trying to gem install
rubygnome on windows:

I type:

```text
gem install gtk2
```

it tells me "invalid gem: package is corrupt, exception
while verifying: undefined method size for nil,
NoMethodError for:

```text
cairo-1.14.1-x86-mingw32.gem
```

sorry for the bad layout, I am on windows right now :)

**Comment by kou** [comment]
Could you show `ruby -v` output?

**Comment by kou** [comment]
No response. I close this.
