### ISSUE TITLE
gtk_text_iter_has_tag assertion GTK_IS_TAXT_TAG(tag) failed with gtk 3.8.8

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#374]
here is a simple script that reproduce the error:
```ruby
#!/usr/bin/env ruby

require "gtk3"

def textview_query_tooltip(textview, keyboard_tip, x, y, tooltip, tag)
    if keyboard_tip
        iter = textview.buffer.get_iter_at_offset(textview.buffer.cursor_position)
    else
        bx, by = textview.window_to_buffer_coords(Gtk::TextWindowType::TEXT, x, y)
        iter, = textview.get_iter_at_position(bx, by)
    end
    if iter.has_tag?(tag)
        tooltip.text = 'Tooltip on text tag'
        return true
    else
        return false
    end
end

window = Gtk::Window.new(:toplevel)
window.title = 'Text tag issue'
window.border_width = 10
window.signal_connect('delete-event') { Gtk.main_quit }

box = Gtk::Box.new(:vertical, 3)
window.add(box)

buffer = Gtk::TextBuffer.new
buffer.insert(buffer.end_iter, 'Hello, the text ')
tag = buffer.create_tag('bold', { 'weight' => Pango::WEIGHT_BOLD })
buffer.insert(buffer.end_iter, 'in bold', :tags => [tag])
buffer.insert(buffer.end_iter, ' has a tooltip!')
textview = Gtk::TextView.new(buffer)
textview.set_size_request(200, 50)
textview.has_tooltip = true
textview.signal_connect('query-tooltip') { |widget, x, y, keyboard_tip, tooltip|
    textview_query_tooltip(widget, keyboard_tip, x, y, tooltip, tag)
}
box.pack_start(textview, :expand =>  false, :fill =>  false, :padding =>  2)

window.show_all
Gtk.main
```

This script work fine with gtk 3.16.2 (archlinux) but not with gtk 3.8.8 (centos). The gtk ems are the most up to date of the 2.2.5 versions.

here is the full error message:

    /home/cedlemo/.rvm/gems/ruby-2.2.0/gems/gobject-introspection-2.2.5/lib/gobject-introspection/loader.rb: line 494
       Gtk-CRITICAL **:gtk_text_iter_has_tag: assertion 'GTK_IS_TEXT_TAG (tag)' failed

The application doesn't crash but the tag is not applied and when I pass my mouse over the place where the text should be different I have this error message.

This is the only error I have with the tooltips.rb sample. Should I just use the Gtk.Version.or_later? in order to allow this script to run just on gtk 3.16.2 ??

**Comment by kou** [comment]
Thanks for the report.

It's caused by `gtk_text_tag_table_add()` API change at GTK+ 3.13.2. See also: https://bugzilla.gnome.org/show_bug.cgi?id=614717

I've pushed workaround for the case. Now, the script you attached can work on CentOS 7.
