### ISSUE TITLE
glib2 RubyGem build error on OSX Yosemite

### ISSUE THREAD

**Issue by Feldmrschl** [ruby-gnome2/ruby-gnome2#375]
Environment: OSX (Yosemite)
C Library: glib (2.44.0 :: installed via HomeBrew)
Ruby Version: 2.2.1p85 (installed via HomeBrew)
Gem Version: glib2-2.2.4

Error:

make "DESTDIR="
compiling glib-enum-types.c
glib-enum-types.c:1181:9: error: use of undeclared identifier 'G_WIN32_OS_ANY'
      { G_WIN32_OS_ANY, "G_WIN32_OS_ANY", "any" },
        ^
glib-enum-types.c:1182:9: error: use of undeclared identifier 'G_WIN32_OS_WORKSTATION'
      { G_WIN32_OS_WORKSTATION, "G_WIN32_OS_WORKSTATION", "workstation" },
        ^
glib-enum-types.c:1183:9: error: use of undeclared identifier 'G_WIN32_OS_SERVER'
      { G_WIN32_OS_SERVER, "G_WIN32_OS_SERVER", "server" },
        ^
3 errors generated.
make: *** [glib-enum-types.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.2.0/gems/glib2-2.2.4 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0/glib2-2.2.4/gem_make.out

Proposed Fix:
I patched the ext/glib2/extconf.rb file by capturing the return of the setup_windows method call and using this to remove gwin32.h from the include_paths list used to generate glib-enum-types files.

Replace: setup_windows(module_name, base_dir)
With: on_windows = setup_windows(module_name, base_dir)

Replace:  /g(iochannel|main|scanner)\.h/ =~ file
With: /g(iochannel|main|scanner)\.h/ =~ file || (!on_windows && /gwin.*\.h/ =~ file)

I was able to patch a local copy of the gem and get it to install correctly.

**Comment by kou** [comment]
Thanks for your report!
It had been fixed at master.
