### ISSUE TITLE
Trees in gtk2 and gdk3

### ISSUE THREAD

**Issue by KostblLb** [ruby-gnome2/ruby-gnome2#378]
have this error: "g_error_free: assertion 'error!=NULL' failed" when trying to append a child item to a treestore. code fragment:

(0..9).each do |i|
	iter = treeStore.append(nil)
	iter.set_value(0,"HI, #{i}")
	puts treeStore.get_value(iter,0)
	iter = treeStore.append(iter)
	iter.set_value(0,"hello again, #{arr[i][0]}!")
	puts treeStore.get_value(iter,0)
end

it issues an error message when gtk3 is required, and everything is alright with gtk2. also, the same trouble is with example code from page http://ruby-gnome2.sourceforge.jp/hiki.cgi?tut-treeview-model-reference

**Comment by kou** [comment]
Could you show a full runnable code instead of code fragment?
I can't run code fragment. :<

**Comment by KostblLb** [comment]
i don't have mine anymore, but, as i said, a tutorial app code from this page  http://ruby-gnome2.sourceforge.jp/hiki.cgi?tut-treeview-model-reference suffers, too,  from changing only one line - "require 'gtk2'" to "require 'gtk3'". it showes in lack of '+' buttons near TreeStore items with children, like there aren't any. but the code works if you have no children in your TreeStore.

**Comment by kou** [comment]
We've released gtk3 gem 3.0.0.
It migrated to GObject Introspection bindings from hand-writing bindings. The new version may fix the problem. Could you try 3.0.0?
