### ISSUE TITLE
Gtk::Widget.drag_source_set, Gtk::TargetEntry not automatically created from Sub-Arrays.

### ISSUE THREAD

**Issue by eumario** [ruby-gnome2/ruby-gnome2#386]
In Gtk2 and Gtk3 C Bindings, you can use drag_source_set() with an array of arrays defining the Gtk::TargetEntry that will be created by the library, but with the GI Bindings, they need to be created by the user.

Original Method signature:
```ruby
drag_source_set(Gdk::BUTTON_PRIMARY, [ [string, target_widget, 0] ], Gdk::DragAction::MOVE)
```

The current signature:
```ruby
drag_source_set(Gdk::BUTTON_PRIMARY, [ Gtk::TargetEntry.new(string, target_widget, 0) ], Gdk::DragAction::MOVE)
```

**Comment by kou** [comment]
I've fixed it.
