### ISSUE TITLE
G_APPLICATION_FLAGS constants in ruby-gnome2

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#401]
What are the equivalent for the constants of the enum G_APPLICATION_FLAGS with ruby-gnome2. I wasn't able to find them. 
reference:  https://developer.gnome.org/gio/unstable/GApplication.html#GApplicationFlags

I have seen in this closed issue (https://github.com/ruby-gnome2/ruby-gnome2/issues/393)  that 
```ruby
Gtk::Application.new "name", 0 
```
works so I guess they are implemented.

**Comment by kou** [comment]
> What are the equivalent for the constants of the enum G_APPLICATION_FLAGS with ruby-gnome2.

It's `Gio::ApplicationFlags`.

> ```ruby
> Gtk::Application.new "name", 0
> ```

It can be written like the following:

```ruby
Gtk::Application.new "name", :flags_none
```

BTW, `"name"` is not valid. `.` must be included. See also: https://developer.gnome.org/gio/stable/GApplication.html#g-application-id-is-valid

**Comment by cedlemo** [comment]
Thanks
