### ISSUE TITLE
Gtk3 and threads

### ISSUE THREAD

**Issue by michelboaventura** [ruby-gnome2/ruby-gnome2#415]
Hi all,

I'm trying to figure out how I'm suposed to work with ruby-gtk3 and threads. I read on some old posts that I should never call a gtk function from outsite gtk's main thread, because it could break things up. Is this still an issue? Also, I've seen [here](https://github.com/ruby-gnome2/ruby-gnome2/blob/2288c76eb2bd9dd8d787d207daa4a122f0983ba8/gtk3-no-gi/sample/misc/threads.rb) an example with two threads outside gtk's main one on which no special care is taken to deal with this.

**Comment by glurp** [comment]
see: http://ruby-gnome2.osdn.jp/hiki.cgi?tips_threads

**Comment by cedlemo** [comment]
@kou : 
Are those informations still up to date?

*    I have checked the ruby forum link in the hiki, it was written in 2007 - 2010. They talk about Gtk2
*    the last modification of the hiki page was in 2010.

If they are, it could be interesting to do a thread script example based on those informations. the thread.rb example that exist doesn't reflect the complexity of the wiki article (I must say that I haven't totally understood it).

Regards

**Comment by kou** [comment]
> Are those informations still up to date?

Yes.

We should not call GTK+ functions from not main thread. I've updated threads.rb: https://github.com/ruby-gnome2/ruby-gnome2/commit/8412c3a57c6d4856b72c3ae32a18124838131dae
