### ISSUE TITLE
Applet

### ISSUE THREAD

**Issue by quolpr** [ruby-gnome2/ruby-gnome2#416]
Is there any way to build gnome applet on ruby? I tried to google, but I nothing found.

**Comment by ff2000** [comment]
If you are talking about gnome-shell extensions:
They are AFAIK only possible in javascript, because gnome-sell itself is written in javascript. At least this was the case last time I tried gnome3 (3.12?)

**Comment by kou** [comment]
Can I close this?

**Comment by quolpr** [comment]
@ff2000 - thank you for answer. I close the issue.

**Comment by kou** [comment]
Thanks for your response!
