### ISSUE TITLE
undefined method `render_rsvg_handle'　(mac ruby)

### ISSUE THREAD

**Issue by R-Y** [ruby-gnome2/ruby-gnome2#430]
@kou 
失礼いたします。

macのrubyでrsvg2を利用しようとしても
undefined method `render_rsvg_handle'
とエラーが出てきて落ちてしまいます。

rvmでインストールしたrubyだとエラーは発生しないのですが、
諸事情によりmacのrubyを使用したいと思っています。
どのようにかして、使用できないものでしょうか？

よろしくお願いいたします。

**Comment by kou** [comment]
バックトレースを全部見せてもらえませんか？

**Comment by kou** [comment]
あと、`ruby -v`の結果も教えてください。

**Comment by R-Y** [comment]
@kou 
ruby -vは
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]

バックトレースはこちらになります。
https://gist.github.com/R-Y/35baa6c04ace3ef3998d

よろしくお願い致します。

**Comment by kou** [comment]
ありがとうございます。

`ruby -r rsvg2 -e 'puts $"'`の結果も教えてもらえますか？

あと、RubyGems自体をアップデートすると問題が解決するか試してみてもらえますか？

**Comment by R-Y** [comment]
@kou 
アップデートしても同様にundefined method `render_rsvg_handle'が発生致しました。

ruby -r rsvg2 -e 'puts $"'　の結果はこちらです。
https://gist.github.com/R-Y/36ee99b581627791429d

よろしくお願い致します。

**Comment by kou** [comment]
/Library/Ruby/Gems/2.0.0/gems/rsvg2-2.2.5/lib/rsvg2.rb を編集して（`p`を入れるなどして）

```ruby
module Cairo
  class Context
    def render_rsvg_handle(handle, *args, &block)
      handle.render_cairo(self, *args, &block)
    end
  end
end
```

のコードが実行されているか確認してもらえますか？

**Comment by R-Y** [comment]
@kou 
お手数お掛けしております。

試してみた結果、実行はされておりませんでした。
if RSVG.cairo_available?　がfalseになっているようです。

**Comment by kou** [comment]
であれば、`gem install rsvg2`したときに、OS XのRubyだと https://github.com/ruby-gnome2/ruby-gnome2/blob/2.2.5/rsvg2/ext/rsvg2/extconf.rb#L67 が`false`になっていて、RVMのRubyだと`true`になっているのだと思います。

私は環境がないのでこれ以上は調べられません。2つの違いを調べて解決してもらえますか？

原因と解決方法がわかったらここに書いてもらえると次に同じ問題に遭遇した人が困らなくなるので助かります。

**Comment by R-Y** [comment]
@kou 
ではその辺りをこちらで調べてみます。
原因がわかりましたら、またご連絡させていただきます。

ご回答いただきありがとうございました。

**Comment by Kagetsuki** [comment]
ちょっとマック貸してもらっているところでこれ試しましたが、以下の結果:
1. RVM (Ruby 2.2.1) + Brew: RSVG.cairo_available?がtrueだがD-busの問題様々でGTK3[/2]のアプリが固まる。
2. mac ruby (2.0.0) + Brew: システム標準のライブラリとBrewのライブラリ(ffiなど?)が重複しているとごちゃまぜにコンパイルされて、環境変数で無理やりBrewを優先させようとしても無理っぽい。恐らくmac rubyの問題よりmac rubyがシステム標準ライブラリに依存しているのが問題で、Brewと仲良く出来ません。

要するにBrewを使わないでシステム標準の物に手動でライブラリ度を整えば動くでしょう。そんな面倒くさいのを試す気がないんですが。。。

@kou さん; ラベルをWon't Fix度付けてこのイシューを閉じても良いでしょう。Ruby-Gnome2以前の問題で直すのにかなり無理があるだろうとのことで。

**Comment by kou** [comment]
確認ありがとうございます！
ラベルを使うくらい複雑な運用はしていないのでこのまま閉じます。
