### ISSUE TITLE
Gtk::FlowBox is unimplemented.

### ISSUE THREAD

**Issue by dark-yux** [ruby-gnome2/ruby-gnome2#435]
Please Implement Gtk::FlowBox.

**Comment by cedlemo** [comment]
What version of ruby-gnome2 are you using? The Gtk::FlowBox is implemented in the  gtk3 gem 2.2.6. I have pushed an example here #436

**Comment by dark-yux** [comment]
I'm using 2.2.5 when is 2.2.6 available on ruby gems?

**Comment by cedlemo** [comment]
@kou 
I have tested the 2.2.5 version and I confirm:

    /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-2.2.5/lib/glib2/deprecatable.rb:96:in `const_missing':    uninitialized constant Gtk::FlowBox (NameError)
	from papillon/tests/flowbox.rb:37:in `initialize'
	from papillon/tests/flowbox.rb:71:in `new'
	from papillon/tests/flowbox.rb:71:in `<main>'

@dark-yux 
It could have been related to your gtk version too. The Gtk FlowBox has been introduced in the Gtk version 3.12.

>when is 2.2.6 available on ruby gems?

I don't know maybe a couple of months (https://github.com/ruby-gnome2/ruby-gnome2/pull/402) .It depends on when I will have finished to update all the sample scripts.

Maybe you could try to use the  git version of the 2.2.6. It works well .

**Comment by kou** [comment]
@cedlemo Thanks for confirming it. Released gtk3 gem doesn't use gi. It doesn't provide recent GTK+ 3 API.

**Comment by kou** [comment]
> Maybe you could try to use the git version of the 2.2.6. It works well .

Here are command lines to install Git version: https://github.com/ruby-gnome2/ruby-gnome2/#install-from-github-master-branch

**Comment by kou** [comment]
Try gtk3 gem 3.0.0.
