### ISSUE TITLE
Gtk::RecentChooserdialog methods name more rubyish

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#453]
While I was updating the script recentchooserdialog.rb, I have seen that some methods name have changed and that they are not as rubyish as previously see #452.

*    get_application_info instead of appication_info
*    exists instead of exist?

**Comment by kou** [comment]
> get_application_info instead of appication_info

It's OK. Because we use the following naming rule:

Getter method that has one or more arguments doesn't remove "get_" prefix from the method name.

See: http://ruby-gnome2.osdn.jp/hiki.cgi?Naming+and+Conversion+Rules#Accessors+%28Setter%2FGetter+methods%29

> exists instead of exist?

We should use `exist?`. I've fixed it.
