### ISSUE TITLE
Gtk-WARNING **:Theme parsing error

### ISSUE THREAD

**Issue by infevvia** [ruby-gnome2/ruby-gnome2#460]
Hello Ruby community, i've installed rubygtk 2.2.5 and also i've made a simple window but when i run this i give this warning ( the script work fine )

==========================================================================
Script:

#!/usr/bin/ruby
require ('gtk3')
class Foo < Gtk::Window
	def initialize
		ui
	end
	def destroy
		Gtk.main_quit
	end
	def ui
		@win = Gtk::Window.new(:toplevel)
		@win.set_size_request(400,50)
		@win.border_width = 15
		@win.set_window_position(:center)
		@win.set_resizable(false)
		@win.signal_connect('destroy') { destroy}
		@win.show_all
	end
end
Gtk.init
	app = Foo.new()
Gtk.main

=========================================================================
Warning

[infevvia@localhost Downloads]$ ruby neck.rb
neck.rb: line 14
   Gtk-WARNING **:Theme parsing error: gtk-main.css:8:36: '' is not a valid color name
neck.rb: line 14
   Gtk-WARNING **:Theme parsing error: gtk-main.css:9:40: '' is not a valid color name
neck.rb: line 14
   Gtk-WARNING **:Theme parsing error: gtk-main.css:10:36: '' is not a valid color name
neck.rb: line 14
   Gtk-WARNING **:Theme parsing error: gtk-main.css:11:30: '' is not a valid color name
[infevvia@localhost Downloads]$

**Comment by cedlemo** [comment]
I don't think it'is related to ruby-gnome but what is your theme (is it a custom one )?, have you checked the `gtk-main.css`.


@infevvia FYI, you could use 

    ```ruby
    ruby code
    ```
in order to display your code in a more readable way (looks the code examples here https://guides.github.com/features/mastering-markdown/#examples)

**Comment by infevvia** [comment]
@cedlemo yes i'm using a custom theme, this is the reason of this warning, thank so much !!!

regards from Chile.

**Comment by kou** [comment]
It seems that this issue is solved. I close this issue.
