### ISSUE TITLE
Gtk::ComboBox#active_iter returns an array 

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#462]
I have a little test (that maybe could be added in the sample scripts):

```ruby
require "gtk3"

window = Gtk::Window.new "Comboooooooo !!!!"

model = Gtk::ListStore.new(TrueClass, String)

iter = model.append
iter[0] = false
iter[1] = "item1"
iter = model.append
iter[0] = false
iter[1] = "item2"
iter = model.append
iter[0] = false
iter[1] = "item3"

combobox = Gtk::ComboBox.new( :model => model, :entry => true)
toggle = Gtk::CellRendererToggle.new
toggle.signal_connect "toggled" do |widget, path|
  puts widget.class
  puts path.class
end

combobox.pack_start(toggle, true)
combobox.add_attribute(toggle, "active", 0)
combobox.set_entry_text_column(1)

window.add combobox

window.signal_connect("destroy") { Gtk.main_quit }
combobox.signal_connect("changed") do |widget|
  list = widget.model
  iter = widget.active_iter
  puts iter.inspect
  puts "#{list.get_value(iter[1],0)} #{list.get_value(iter[1], 1)}"
  
  list.set_value(iter[1], 0, true)
end

window.show_all
Gtk.main

```

When I click on an item in the combobox the instructions `puts iter.inspect`
 displays this:

    [true, #<Gtk::TreeIter:0x1cd8830 ptr=0x1b1c240 own=true>]

I guess that it means:

*    iter[0] boolean for active item or not
*    iter[1] the related item

Wouldn't it be more convenient if the method `Gtk::ComboBox#active_iter` returns nil if there is no active item and the iter itself in the other case?

**Comment by kou** [comment]
> Wouldn't it be more convenient if the method Gtk::ComboBox#active_iter returns nil if there is no active item and the iter itself in the other case?

You're right.

I've added the change for it to master.
