### ISSUE TITLE
TreeModelFilterModifyFunc not supported yet

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#476]
this part:

```ruby
#!/usr/bin/env ruby
=begin
  treemodelfilter.rb - Gtk::TreeModelFilter sample

  Copyright (c) 2004,2006 Ruby-GNOME2 Project Team
  This program is licenced under the same licence as Ruby-GNOME2.

  $Id: treemodelfilter.rb,v 1.3 2006/06/17 13:18:12 mutoh Exp $
=end
require 'gtk3'

ls = Gtk::ListStore.new(String, Integer)

column1 = Gtk::TreeViewColumn.new("data1",
				 Gtk::CellRendererText.new, {:text => 0})
column2 = Gtk::TreeViewColumn.new("data2",
				 Gtk::CellRendererText.new, {:text => 1})

mf = Gtk::TreeModelFilter.new( :child_model => ls)
mf.set_visible_func do |model, iter|
  /a/ =~ iter[0]
end

mf.set_modify_func([String, String]) do |model, iter, column|
  child_iter = model.convert_iter_to_child_iter(iter)
  if column == 0
    child_iter[0]
  else
    "#{child_iter[1]} * 2 = #{child_iter[1] * 2}"
  end
end
```

throws this error:

    TODO: <TreeModelFilterModifyFunc>(func) callback is not supported yet. (NotImplementedError)

**Comment by cedlemo** [comment]
@kou さん I know you are busy so this comment is just to  get your attention in case you didn't noticed this issue :-)

**Comment by kou** [comment]
Thanks for your remainder.
Yes, I'm busy this week and the previous week...
I'll fix it in the next week...!

**Comment by kou** [comment]
Done! :-)

**Comment by cedlemo** [comment]
Thanks !. Sorry if I look like I am impatient but according to my initial list, it remains just 5 scripts in the sample directory that need to be updated (with this one).

**Comment by kou** [comment]
> Sorry if I look like I am impatient

I don't think so. Sorry for my late response...!

> according to my initial list, it remains just 5 scripts in the sample directory that need to be updated (with this one).

Wow!!! Thanks for your great continuous works!!!

**Comment by cedlemo** [comment]
Well I hope I didn't give you false hope but I talked about the sample/misc directory, which is already a big step. It will remains to test/update:

*    sample/gtk-demo
*    sample/testgtk (if I have to do it, it seems that it is the ruby version of the C version tests for gtk2 which has not been updated for gtk3 according to their github)

So it still remains some works but one step is about to be done.

**Comment by kou** [comment]
> So it still remains some works but one step is about to be done.

I think so too!
We'll release a new version when you done works for `sample/misc/`.

`sample/gtk-demo` should be updated. `sample/testgtk` should be ... Umm... should be removed! It seems that `sample/gtk-demo` provides almost same features as `sample/testgtk`.
