### ISSUE TITLE
Gtk::RcProperty methods issue

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#486]
I am updating settings.rb and when I try to use methods like:

```ruby
p Gtk::RcProperty.parse_color(spec, "{2222,44444,65535}").to_a
p Gtk::RcProperty.parse_enum(enum, "watch")
```

I have those messages:

    home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:351:in `validate_arguments': Gtk::RcProperty.parse_color: wrong number of arguments (2 for 3) (ArgumentError)

The C api is:

```C
gboolean
gtk_rc_property_parse_color (const GParamSpec *pspec,
                             const GString *gstring,
                             GValue *property_value);
```

**Comment by kou** [comment]
We don't support `gtk_rc_property_parse_color()` because its not useful for users.
It's used by `gtk_settings_install_property()` but it's deprecated since GTK+ 3.16: https://developer.gnome.org/gtk3/stable/GtkSettings.html#gtk-settings-install-property

I'll remove settings.rb.

**Comment by cedlemo** [comment]
ok
