### ISSUE TITLE
GtkGLArea

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#492]
I really would like to create a sample for this widget (https://developer.gnome.org/gtk3/stable/GtkGLArea.html) but I don't know which gem to use.

On my system I use this command:

```
gem search opengl
*** REMOTE GEMS ***

ffi-opengl (0.2.1)
opengl (0.9.2 ruby x64-mingw32 x86-mingw32)
opengl-bindings (1.3.14)
opengl-core (2.0.1)
opengl-cube (0.0.2)
opengl-definitions (0.0.1)
remogatto-ffi-opengl (0.2.1)
ruby-opengl (0.61.0, 0.60.0 i386-mswin32)
ruby-opengl2 (0.60.6)
```

I have found an updated fork (https://github.com/larskanis/opengl/tree/master/lib/opengl) of the official github which seems inactive for 4 years.

And more important I don't even know if you have implemented the use of opengl ruby bindings with the gtk3 module.

**Comment by kou** [comment]
I think that opengl-bindings is better. Because it's active. :-)
If it doesn't work on Linux, we can send pull requests.

**Comment by kou** [comment]
I don't implement OpenGL bindings until all OpenGL bindings are died. If all OpenGL bindings are died, I may implement it.

**Comment by cedlemo** [comment]
>If it doesn't work on Linux, we can send pull requests.


I have checked the related github (https://github.com/vaiorabbit/ruby-opengl) and It seems that linux support have not been tested yet. They provide samples that work under window and MacOsx. but not under linux. If you think that this the bindings we should focus on, then I will do some tests and pull request for linux support.

**Comment by kou** [comment]
> If you think that it is the bindings we should focus on

I think so!

**Comment by cedlemo** [comment]
Ok I have started to test theirs samples. I close this issue for know even if I haven't tried the GtkGlArea yet.


Thanks
