### ISSUE TITLE
Vte3::Terminal#pty issue

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#493]
this code:

```ruby
require "gtk3"

require "vte3"

window = Gtk::Window.new
vte = Vte::Terminal.new
vte.fork_command(:argv => GLib::Shell.parse("/usr/bin/bash"),
                        :spawn_flags => GLib::Spawn::SEARCH_PATH)
window.add(vte)

window.show_all
window.signal_connect("delete-event") { Gtk.main_quit }
puts Vte.constants
puts pty = vte.pty
Gtk.main
```

Show that the `vte.pty` returns an integer instead of a Vte::Pty

**Comment by kou** [comment]
Use `Vte::Terminal#pty_object` instead.
`Vte::Terminal#pty` returns file descripter of PTY until 0.36. `Vte::Terminal#pty` returns `Vte::Pty` since 0.38.0.

**Comment by kou** [comment]
I've added VTE 0.38 (API version is vte-2.91.)
Now, you can use `Vte::Terminal#pty` to get `Vte::Pty`.
