### ISSUE TITLE
Read from a Vte::Pty#fd 

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#494]
I am about to provide a pull request for `Vte::Terminal#feed_child` (you will see why below) but in order to make a test for this method that I will modify, I have to read from a `Vte::Pty#fd ` and I have some problems:

First code:

```ruby
require "gtk3"
require "vte3"
# encoding: UTF-8
p "System #{Encoding.find("filesystem")}"

vte = Vte::Terminal.new
vte.set_encoding("UTF-8")
p "vte #{vte.encoding}"
vte.spawn(:argv => GLib::Shell.parse("/usr/bin/bash"),
                        :spawn_flags => GLib::Spawn::SEARCH_PATH)

str = "toto"
len = str.bytesize

vte.feed_child(str,str.bytesize)
pty = vte.pty
puts pty.class
fd = pty.fd
io= IO.new(fd,"r+:UTF-8")
puts io.read(4)
```

And I have this output:

```
"System UTF-8"
"vte UTF-8"
Vte::Pty
toto
vte3_terminal.rb: line 0
   GLib-GObject-WARNING **:The property GtkWidget:style is deprecated and shouldn't be used anymore. It will be removed in a future version.
fish: 'ruby vte3_terminal.rb' terminated by signal SIGSEGV (Erreur de frontière d'adresse)
```

There are two points:

*    the string "toto" is well printed
*     the script SIGSEV

Now if I add the vte terminal in a Gtk3 window:

```ruby
require "gtk3"
require "vte3"
# encoding: UTF-8
p "System #{Encoding.find("filesystem")}"

vte = Vte::Terminal.new
vte.set_encoding("UTF-8")
p "vte #{vte.encoding}"
vte.spawn(:argv => GLib::Shell.parse("/usr/bin/bash"),
                        :spawn_flags => GLib::Spawn::SEARCH_PATH)

str = "toto"
len = str.bytesize
window = Gtk::Window.new
window.add(vte)

window.show_all
window.signal_connect("delete-event") { Gtk.main_quit }
vte.feed_child(str,str.bytesize)
pty = vte.pty
puts pty.class
fd = pty.fd
io= IO.new(fd,"r+:UTF-8")
puts io.read(4)
Gtk.main
```

I have this output:

```
"System UTF-8"
"vte UTF-8"
]0;
vte3_terminal.rb: line 0
   GLib-GObject-WARNING **:The property GtkWidget:style is deprecated and shouldn't be used anymore. It will be removed in a future version.
```

*    The script doesn't crash anymore
*    There is an encoding issue with the string

**Comment by kou** [comment]
For first code: We need to run main loop to catch `child-exited` signal. If we don't catch the signal, error message by failing `waitpid()` from GLib to Ruby/GLib2 while Ruby is exiting. We get SIGSEGV when Ruby/GLib2 receives error message from GLib while Ruby is existing. Because error message logger in Ruby/GLib2 uses Ruby functions such as `rb_sourcefile()` and `rb_sourceline()`: https://github.com/ruby-gnome2/ruby-gnome2/blob/master/glib2/ext/glib2/rbglib_messages.c#L66

Try the following code:

```ruby
require "gtk3"
require "vte3"
# encoding: UTF-8
p "System #{Encoding.find("filesystem")}"

vte = Vte::Terminal.new
vte.set_encoding("UTF-8")
p "vte #{vte.encoding}"

loop = GLib::MainLoop.new
vte.spawn(:argv => GLib::Shell.parse("bash"),
          :spawn_flags => GLib::Spawn::SEARCH_PATH)
vte.signal_connect("child-exited") do |*args|
  p [:exited, args]
  loop.quit
end

str = "toto\n"
len = str.bytesize

vte.feed_child(str,str.bytesize)
pty = vte.pty
fd = pty.fd
io= IO.new(fd,"r+:UTF-8")
puts io.read(4)

vte.feed_child("\n", "\n".bytesize)
vte.feed_child("exit\n", "exit\n".bytesize)

loop.run
```

For GTK+ 3 version: It's unsafe to read input as is from `Vte::Pty#fd`. How about using cursor position to detect whether input is arrived or not?

```ruby
require "gtk3"
require "vte3"
# encoding: UTF-8
p "System #{Encoding.find("filesystem")}"

vte = Vte::Terminal.new
vte.set_encoding("UTF-8")
p "vte #{vte.encoding}"
vte.spawn(:argv => GLib::Shell.parse("bash"),
          :spawn_flags => GLib::Spawn::SEARCH_PATH)
vte.signal_connect("child-exited") do
  Gtk.main_quit
end

str = "toto"
len = str.bytesize
window = Gtk::Window.new
window.add(vte)

window.show_all
window.signal_connect("delete-event") { Gtk.main_quit }
GLib::Timeout.add(2000) do
  p vte.cursor_position
  vte.feed_child(str,str.bytesize)
  GLib::Source::CONTINUE
end
Gtk.main
```

**Comment by cedlemo** [comment]
So I just have to use `Vte::Terminal#cursor_position` and `Vte::Terminal#get_text_range` instead of using the file descriptor of the pty?

> For GTK+ 3 version: It's unsafe to read input as is from Vte::Pty#fd

Do you know where I can find informations about this (it is just that I like  understand was is behind)

This is not the subject but can I start updating gtk-demo or should I wait that you have made the new release?

**Comment by kou** [comment]
> So I just have to use `Vte::Terminal#cursor_position` and `Vte::Terminal#get_text_range` instead of using the file descriptor of the pty?

I think so.

> Do you know where I can find informations about this (it is just that I like understand was is behind)

I know it from VTE source. :<
VTE reads/writes from/to the fd to communicate subprocess. If we read/write from/to the fd directly, VTE can't communicate with subprocess correctly.

> This is not the subject but can I start updating gtk-demo or should I wait that you have made the new release?

Please start updating gtk-demo. I found a task in glib2 before we release the new release. We can't use `Gtk::Application` without the task in glib2... I'm working of the task.

**Comment by cedlemo** [comment]
Ok!
