### ISSUE TITLE
Gtk::ApplicationWindow and Gtk::Widget#set_template method

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#503]
I try to adapt the gtk3 examples in ruby and I have some difficulties with the exampleapp2 adaptation.
(source :  https://github.com/GNOME/gtk/tree/master/examples/application2)

Here is the code I have so far:

```ruby
require "gtk3"

require "fileutils"

current_path = File.expand_path(File.dirname(__FILE__))
gresource_bin = "#{current_path}/exampleapp.gresource"
gresource_xml = "#{current_path}/exampleapp.gresource.xml"

Dir.chdir(File.dirname(gresource_xml)) do
  system("glib-compile-resources",
         "--target", gresource_bin,
         File.basename(gresource_xml))
end

at_exit do
  FileUtils.rm_f(gresource_bin)
end

resource = Gio::Resource.load(gresource_bin)
Gio::Resources.register(resource)

class ExampleAppWindow < Gtk::ApplicationWindow
  type_register
  class << self
    def init
      set_template(:resource => "/org/gtk/exampleapp/window.ui")
    end
  end
  def open(file)
    
  end
end

class ExampleApp < Gtk::Application
  def initialize
    super("org.gtk.exampleapp", :handles_open)

    signal_connect "activate" do |application|
      window = ExampleAppWindow.new(application)
      puts window.class
      window.present
    end

    signal_connect "open" do |application, files, hin|
      windows = application.get_windows
      win = nil
      unless windows.empty?
        win = windows.first
      else
        win = ExampleAppWindow.new(application)
      end

      files.each { |file| win.open(file) }
        
      win.present
    end

  end
end

app = ExampleApp.new

puts app.run
```

This doesn't work (I don't even know if it is the good way to do this). I have this error message:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
exampleapp2.rb:39:in `initialize': wrong argument type ExampleApp (expected Hash)
	 from exampleapp2.rb:39:in `initialize'
	 from exampleapp2.rb:39:in `new'
	 from exampleapp2.rb:39:in `block in initialize'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-2.2.6/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from exampleapp2.rb:61:in `<main>'

```

FYI everything was working before I add the following part:

```ruby
  type_register
  class << self
    def init
      set_template(:resource => "/org/gtk/exampleapp/window.ui")
    end
  end
```

**Comment by kou** [comment]
Add the following code to `ExampleAppWindow`:

```ruby
  def initialize(application)
    super(:application => application)
  end
```

We alway need to use properties style constructor when we use `type_register`. Because the constructor provided by GTK+ creates an instance of super class not sub class.

For example, if we use `Gtk::ApplicationWindow#initialize` (that calls `gtk_application_window_new(GtkApplication *application)`) for `ExampleAppWindow`, it create an instance of `GtkApplicationWindow` not `ExampleAppWindow`.

If we use properties style constructor (`ExampleAppWindow.new(:application => application)`) is used, it create an instance of `ExampleAppWindow` not `GtkApplicationWindow`.

**Comment by cedlemo** [comment]
*    It works thanks. FYI I am actually converting all the C examples to ruby from this site : https://developer.gnome.org/gtk3/stable/gtk-getting-started.html. I do this in order to anticipate/prepare for the future tutorials (https://github.com/ruby-gnome2/ruby-gnome2/pull/402#issuecomment-100576162). As I didn't know where to put this, I have created a github repository (I can let them there until I have finished all of them: https://github.com/cedlemo/ruby-gtk3-tutorial)

*    I didn't know about properties style constructor. Why it is not the same for Gtk::Window? look:

in gtk3/sample/misc/template-from-resource.rb

```ruby
class MyWindow < Gtk::Window
  class << self
    def init
      set_template(:resource => "/template/template.ui")
      bind_template_child("label")
    end
  end

  type_register
end

window = MyWindow.new
```

and in gtk3/lib/gtk3/window.rb

```ruby

module Gtk
  class Window
    alias_method :initialize_raw, :initialize
    def initialize(type=:toplevel)
      if type.is_a?(String)
        initialize_raw(:toplevel)
        self.title = type
      else
        initialize_raw(type)
      end
    end
  end
end
```

There is no properties style constructor?

```ruby
Gtk::Window.new( :type => a_type)
```

**Comment by kou** [comment]
> * It works thanks. FYI I am actually converting all the C examples to ruby from this site : https://developer.gnome.org/gtk3/stable/gtk-getting-started.html. I do this in order to anticipate/prepare for the future tutorials (#402 (comment)). As I didn't know where to put this, I have created a github repository (I can let them there until I have finished all of them: https://github.com/cedlemo/ruby-gtk3-tutorial)

Wow! It's so great!
`gtk3/sample/tutorial/` is the best!

> Why it is not the same for Gtk::Window?

It's the same for `Gtk::Window`.
Because `Gtk::Window.new(:toplevel)` works but `MyWindow.new(:toplevel)` doesn't work.

> There is no properties style constructor?
> 
> ```ruby
> Gtk::Window.new( :type => a_type)
```

Yes. There is no properties style constructor for `Gtk::Window`.

We need to pull properties style constructor from `GLib::Object#initialize`. It's the properties style constructor.

Here is a real-world example to pull properties style constructor from `GLib::Object#initialize`:

https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gtk3/lib/gtk3/message-dialog.rb#L26-L28

```ruby
      initialize_general = GLib::Object.instance_method(:initialize).bind(self)
      initialize_general.call(:message_type => type,
                              :buttons => buttons)
```

**Comment by cedlemo** [comment]
I will create a pull request for the tutorial samples
