### ISSUE TITLE
GBinding with ruby-gnome2

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#524]
How do you link/bind two properties of 2 differents objects with ruby-gnome2:

in C (https://developer.gnome.org/gobject/stable/GBinding.html#g-object-bind-property):

```c
GBinding *
g_object_bind_property (gpointer source,
                        const gchar *source_property,
                        gpointer target,
                        const gchar *target_property,
                        GBindingFlags flags);
```
I was not able to find the ruby equivalent of `g_object_bind_property` or the `GBindingFlags` constants.

**Comment by kou** [comment]
I've implemented it.

Try like the following code:

```ruby
source_object("source-property-name", target_object, "target-property-name", :default)
```

Custom "source-property" value to "target-property" value converter feature isn't supported yet.

**Comment by cedlemo** [comment]
Thank a lot, now I have another issue ( #526 ).  :-) 

I think that when the tutorial will be finished, the Gtk::Application will be for the most part  tested/implemented.

**Comment by kou** [comment]
> I think that when the tutorial will be finished, the Gtk::Application will be for the most part tested/implemented.

It sounds great!!!
I should release a new version...!
