### ISSUE TITLE
test gtk3-3.0.0.0 on windows

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#538]
Can't create a gtk window : 

d:\usr\Ruby\Ruby200\lib\ruby\gems\2.0.0\gems\gtk3-3.0.0-x86-mingw32\sample\gtk-demo>ruby main.rb
d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/loader.rb:224:in `initialize': flag value must be one of nil, Fixnum, String, Symbol, #<Class:0x3aeaf20> or Array of them: <1073741824>(GdkModifierType) (ArgumentError)
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/loader.rb:224:in `new'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/loader.rb:224:in `define_class'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/loader.rb:224:in `load_flags_info'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/loader.rb:61:in `load_info'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/loader.rb:40:in `block in load'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/repository.rb:27:in `block (2 levels) in each'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/repository.rb:26:in `times'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/repository.rb:26:in `block in each'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/repository.rb:25:in `each'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/repository.rb:25:in `each'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.0-x86-mingw32/lib/gobject-introspection/loader.rb:39:in `load'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gdk3-3.0.0-x86-mingw32/lib/gdk3.rb:55:in `init'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.0-x86-mingw32/lib/gtk3.rb:67:in `init'
        from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.0-x86-mingw32/lib/gtk3.rb:43:in `const_missing'
        from main.rb:14:in `<module:Demo>'
        from main.rb:13:in `<main>'

**Comment by kou** [comment]
Thanks for your report.
I've fixed it. I'll release 3.0.1.

**Comment by kou** [comment]
I've released 3.0.1. Could you try it?

**Comment by glurp** [comment]
>ruby main.rb
ok , main window work
Button box => ok
style classes => missing somes icons...
change display => scrach, bject-introspection/loader.rb:551:in `invoke': no implicit conversion of Symbol into Integer
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb:551:in `block in define_method'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.1-x86-mingw32/lib/gtk3/dialog.rb:53:in `block in add_buttons'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.1-x86-mingw32/lib/gtk3/dialog.rb:52:in `each'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.1-x86-mingw32/lib/gtk3/dialog.rb:52:in `add_buttons'

CHange color => scratch rospection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb:307:in `invoke': no implicit conversion of Hash into String
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb:307:in `block (2 levels) in load_constructor_infos'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb:323:in `block in load_constructor_infos'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/glib2-3.0.1-x86-mingw32/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'

Cairo/Arc => ok
Caito/Clip => scratch
ngw32/lib/gdk3/cairo.rb:47:in `set_source_rgba': no implicit conversion to float from nil
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gdk3-3.0.1-x86-mingw32/lib/gdk3/cairo.rb:47:in `set_source_rgba'
         from d:/usr/Ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.1-x86-mingw32/sample/gtk-demo/cairo-clip.rb:27:in `draw'
most cairo  scratch, with set_source_rgba()

In my applications :
* Gtk.init seem not existe anymore ...?
* window.set_icon(string) ==> set_icon(name: filename)

Many many incompatibilities  :)
