### ISSUE TITLE
GStreamer gst-inspect sample throws segmentation fault

### ISSUE THREAD

**Issue by jeffheifetz** [ruby-gnome2/ruby-gnome2#539]
I was trying to run the [gst-inspect sample](https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gstreamer/sample/gst-inspect.rb) and got a segmentation fault.

Output can be found here - https://gist.github.com/jeffheifetz/50de57d21088d9eab251

Gstreamer Gem: 2.2.5
Gstreamer Version: 1.2.4
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
ubuntu 14.04

Edited:  I updated the URL, original post had the wrong one.

**Comment by kou** [comment]
Thanks for your report.
Please try again with gstreamer gem 3.0.0.

**Comment by jeffheifetz** [comment]
Upgrading to 3.0.2 seemed to fix it.
