### ISSUE TITLE
test 3.0.1 on windows 7 ruby 2.0.0p0  [i386-mingw32]

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#540]
```text
ruby main.rb
ok , main window work
Button box => ok
style classes => missing somes icons...
change display => scrach, 
object-introspection/loader.rb:551:in `invoke': no implicit conversion of Symbol into Integer
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb:551:in `block in define_method'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.1-x86-mingw32/lib/gtk3/dialog.rb:53:in `block in add_buttons'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.1-x86-mingw32/lib/gtk3/dialog.rb:52:in `each'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.1-x86-mingw32/lib/gtk3/dialog.rb:52:in `add_buttons'

Change color => scratch 
introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb:307:in `invoke': no implicit conversion of Hash into String
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb:307:in `block (2 levels) in load_constructor_infos'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb:323:in `block in load_constructor_infos'
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/glib2-3.0.1-x86-mingw32/lib/glib2/deprecatable.rb:47:in `block in define_deprecated_method_by_hash_args'

Cairo/Arc => ok
Caito/Clip => scratch
lib/gdk3/cairo.rb:47:in `set_source_rgba': no implicit conversion to float from nil
         from d:/usr/ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gdk3-3.0.1-x86-mingw32/lib/gdk3/cairo.rb:47:in `set_source_rgba'
         from d:/usr/Ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.1-x86-mingw32/sample/gtk-demo/cairo-clip.rb:27:in `draw'
```

most cairo  demos scratch, with set_source_rgba()

In my applications :
* Gtk.init seem not exist anymore ...?
* window.set_icon(string) ==> set_icon(name: filename)

Many many many incompatibilities  :)

**Comment by cedlemo** [comment]
What are you testing? 
> d:/usr/Ruby/Ruby200/lib/ruby/gems/2.0.0/gems/gtk3-3.0.1-x86-mingw32/sample/gtk-demo/cairo-clip.rb:27

if it is the gtk-demo, the scripts haven't been updated yet. For the moment you should look at the gtk3/sample/misc. There are a lot of scripts that have been tested and updated.

>In my applications : 
>
>Gtk.init seem not exist anymore ...?
>window.set_icon(string) ==> set_icon(name: filename)

You don't have to call `Gtk.init` anymore.  

>Many many many incompatibilities :)

Maybe we can help you :)

**Comment by kou** [comment]
Thanks for trying it!
I've fixed problems what you reported except "Change color". "Change color" should be rewritten because it uses deprecated widget.

> * Gtk.init seem not exist anymore ...?

It exists but it's removed when it's called to prevent double initialization:

```ruby
% ruby -r gtk3 -e 'p 1; Gtk.init; p 2; Gtk.init; p 3'
1
2
-e:1:in `<main>': undefined method `init' for Gtk:Module (NoMethodError)
```

Normally, you don't need to call `Gtk.init` explicitly. It:s the same behavior as gtk2 gem.

> * window.set_icon(string) ==> set_icon(name: filename)

I've added `window.set_icon(filename)` support at master.

> Many many many incompatibilities :)

Oh... Could you show them? I think that we should resolve most of them...

**Comment by kou** [comment]
@glurp Could you try sample/misc instead of sample/gtk-demo as @cedlemo says? If sample/misc works well on Windows, we can confirm that most gtk3 gem features works well on Windows.

**Comment by glurp** [comment]
Hello,
test with ruby 2.1, samples/misc directory.

seem ok.
some stock icon are missing (print-* )

>scratch on pango-layout.rb : 
D:/usr/ruby/Ruby21/lib/ruby/gems/2.1.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/collection-reader.rb: l
   GLib-GObject-WARNING **:The property GtkWidget:style is deprecated and shouldn't be used anymore. It will be removed in a future v
D:/usr/ruby/Ruby21/lib/ruby/gems/2.1.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb:551:in `invok
ment Array (expect Gtk::TreePath)
         from D:/usr/ruby/Ruby21/lib/ruby/gems/2.1.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb
n define_method'
         from D:/usr/ruby/Ruby21/lib/ruby/gems/2.1.0/gems/gtk3-3.0.1-x86-mingw32/lib/gtk3/tree-model.rb:24:in `get_iter'
         from tooltips.rb:33:in `treeview_query_tooltip'
         from tooltips.rb:144:in `block in <main>'
         from D:/usr/ruby/Ruby21/lib/ruby/gems/2.1.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb
         from D:/usr/ruby/Ruby21/lib/ruby/gems/2.1.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb

         from D:/usr/ruby/Ruby21/lib/ruby/gems/2.1.0/gems/gobject-introspection-3.0.1-x86-mingw32/lib/gobject-introspection/loader.rb
n define_singleton_method'
         from tooltips.rb:195:in `<main>'

>colorselection.rb scratch :
D:/usr/ruby/Ruby21/lib/ruby/gems/2.1.0/gems/glib2-3.0.1-x86-mingw32/lib/glib2/deprecatable.rb:111:in `const_missing': D:/usr/ruby/Ruby21/lib/ruby/gem
s/2.1.0/gems/gtk3-3.0.1-x86-mingw32/lib/gtk3.rb:47:in `const_missing': 'Gtk::ColorSelection' has been deprecated. Use 'Gtk::ColorChooserWidget' inste
ad. (GLib::DeprecatedError)
        from D:/usr/ruby/Ruby21/lib/ruby/gems/2.1.0/gems/gtk3-3.0.1-x86-mingw32/lib/gtk3.rb:47:in `const_missing'
        from colorselection.rb:10:in `<main>'

>scalebutton.rb: ok , but icons are missings
>application.rb :  scratch :
D:\usr\ruby\Ruby21\lib\ruby\gems\2.1.0\gems\gtk3-3.0.1-x86-mingw32\sample\misc>ruby application.rb

(ruby.exe:15476): GLib-GIO-CRITICAL **: This application can not open files.

all others app seem ok :)

**Comment by cedlemo** [comment]
@kou : 

For me on Linux x86_64:

*     pango-layout.rb works
*     tooltips.rb crash too (see below)
*     colorselection.rb crash because `Gtk::ColorSelction` is deprecated I have proposed an update (#541)
*     application.rb works

Error message for tooltips.rb:

```
ruby  gtk3/sample/misc/tooltips.rb                                                                                                                     
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.2/lib/gobject-introspection/loader.rb:551:in `invoke': invalid argument Array (expect Gtk::TreePath)
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.2/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gtk3-3.0.2/lib/gtk3/tree-model.rb:24:in `get_iter'
	 from gtk3/sample/misc/tooltips.rb:33:in `treeview_query_tooltip'
	 from gtk3/sample/misc/tooltips.rb:144:in `block in <main>'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.2/lib/gobject-introspection/loader.rb:114:in `call'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.2/lib/gobject-introspection/loader.rb:114:in `invoke'
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.2/lib/gobject-introspection/loader.rb:114:in `block in define_singleton_method'
	 from gtk3/sample/misc/tooltips.rb:195:in `<main>'
```

This ocurs when you use your mouse on the treeview in this part of the code.

```ruby
def treeview_query_tooltip(treeview, keyboard_tip, x, y, tooltip)
  if keyboard_tip
    # Keyboard mode
    path, = treeview.cursor
    if not path
      return false
    end
  else
    bin_x, bin_y = treeview.convert_widget_to_bin_window_coords(x, y)
    # Mouse mode
    path = treeview.get_path_at_pos(bin_x, bin_y)
    if not path
      return false
    end
  end
  puts path 
  data = treeview.model.get_value(treeview.model.get_iter(path), 0)
  tooltip.markup = "<b>Path #{path}:</b> #{data}"
  return true
end
```

The `puts path` displays:

```
3
#<Gtk::TreeViewColumn:0x00000003e0fd50>
319
25
```

I don't have the time to go further :( (Version .or_later methods and exampleapp10 to do )

**Comment by kou** [comment]
@glurp Thanks for trying them. We've almost fixed them.

Can we find incompatibilities as you said by running samples in https://github.com/glurp/dsl-gtk?

**Comment by kou** [comment]
@cedlemo Thanks for you works! #542 is only remained.

**Comment by glurp** [comment]
@kou : git is break on my pc at home... i wil fixe gtk_init and gtk.get_version tomorow, then
running spec/test_all.rb can be usefull.

**Comment by kou** [comment]
No problem.

I ran `spec/test_all.rb`. Now, you just need the following patch:

```diff
modified   lib/Ruiby.rb
@@ -123,7 +123,6 @@ module Ruiby
     Thread.abort_on_exception = true  
     BasicSocket.do_not_reverse_lookup = true if defined?(BasicSocket)
     trap("INT") { exit(0) }
-    Gtk.init
     yield
     secure_main()	
   end
@@ -139,7 +138,6 @@ module Ruiby
     Thread.abort_on_exception = true  
     BasicSocket.do_not_reverse_lookup = true if defined?(BasicSocket)
     trap("INT") { exit(0) }
-    Gtk.init
     yield
     secure_main()	
   end
```

Please wait gtk3 3.0.2.
