### ISSUE TITLE
test-unit-notify gem needed for some tests

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#543]
@kou, 

I am currently trying to write the method `Version.or_later?` for the atk module and in the test files, the gem **test-unit-notify** was needed. It is not very important but it is just that I while I was working on the gtk3 module it was not needed and this gem doesn't appear as a requirement/dependency anywhere in the README files.

**Comment by kou** [comment]
OK. Let's remove all test-unit-notify dependency.

**Comment by cedlemo** [comment]
As you wish . If you don't mind I will let this issue open until I have removed all those dependencies.

**Comment by kou** [comment]
I don't mind!
(I'm releasing a new version...)

**Comment by cedlemo** [comment]
pull request #547
