### ISSUE TITLE
test 3.0.2 on windows 7 , with ruby 32/64 bits

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#546]
Almost same as 32 bits.
rspec:
- - -

"""
Finished in 18.69 seconds (files took 1.37 seconds to load)
94 examples, 1 failure
"""
(failure com from win32screenshot x64)

sample/test.rb
- - -
* cell alignment do not work (centered in place of fill both)
* no icons 
* cairo mouse-event have wrong data

typelib error with gtksoureview3

sample/fractal.rb : no color, (all drawing in black) , same as x32, same under linux
... set_source_rgba() issue...

**Comment by kou** [comment]
> * cell alignment do not work (centered in place of fill both)

Could you show screenshot?

> * no icons

Could you change icon name from `gtk-XXX`? `gtk-XXX` name is obsoleted.

The following list will help you:

```text
gtk-about.png -> help-about.png
gtk-add.png -> list-add.png
gtk-bold.png -> format-text-bold.png
gtk-cancel.png -> process-stop.png
gtk-clear.png -> edit-clear.png
gtk-close.png -> window-close.png
gtk-copy.png -> edit-copy.png
gtk-cut.png -> edit-cut.png
gtk-delete.png -> edit-delete.png
gtk-execute.png -> system-run.png
gtk-find-and-replace.png -> edit-find-replace.png
gtk-find.png -> edit-find.png
gtk-fullscreen.png -> view-fullscreen.png
gtk-go-back-ltr.png -> go-previous.png
gtk-go-back-rtl.png -> go-next.png
gtk-go-down.png -> go-down.png
gtk-go-forward-ltr.png -> go-next.png
gtk-go-forward-rtl.png -> go-previous.png
gtk-go-up.png -> go-up.png
gtk-goto-bottom.png -> go-bottom.png
gtk-goto-first-ltr.png -> go-first.png
gtk-goto-first-rtl.png -> go-last.png
gtk-goto-last-ltr.png -> go-last.png
gtk-goto-last-rtl.png -> go-first.png
gtk-goto-top.png -> go-top.png
gtk-help.png -> help-contents.png
gtk-home.png -> go-home.png
gtk-indent-ltr.png -> format-indent-more.png
gtk-indent-rtl.png -> format-indent-less.png
gtk-italic.png -> format-text-italic.png
gtk-jump-to-ltr.png -> go-jump.png
gtk-jump-to-rtl.png -> go-jump.png
gtk-justify-center.png -> format-justify-center.png
gtk-justify-fill.png -> format-justify-fill.png
gtk-justify-left.png -> format-justify-left.png
gtk-justify-right.png -> format-justify-right.png
gtk-leave-fullscreen.png -> view-restore.png
gtk-media-forward-ltr.png -> media-seek-forward.png
gtk-media-forward-rtl.png -> media-seek-backward.png
gtk-media-next-ltr.png -> media-skip-forward.png
gtk-media-next-rtl.png -> media-skip-backward.png
gtk-media-pause.png -> media-playback-pause.png
gtk-media-play-ltr.png -> media-playback-start.png
gtk-media-previous-ltr.png -> media-skip-backward.png
gtk-media-previous-rtl.png -> media-skip-forward.png
gtk-media-record.png -> media-record.png
gtk-media-rewind-ltr.png -> media-seek-backward.png
gtk-media-rewind-rtl.png -> media-seek-forward.png
gtk-media-stop.png -> media-playback-stop.png
gtk-new.png -> document-new.png
gtk-open.png -> document-open.png
gtk-paste.png -> edit-paste.png
gtk-print-preview.png -> document-print-preview.png
gtk-print.png -> document-print.png
gtk-properties.png -> document-properties.png
gtk-quit.png -> application-exit.png
gtk-redo-ltr.png -> edit-redo.png
gtk-refresh.png -> view-refresh.png
gtk-remove.png -> list-remove.png
gtk-revert-to-saved-ltr.png -> document-revert.png
gtk-revert-to-saved-rtl.png -> document-revert.png
gtk-save-as.png -> document-save-as.png
gtk-save.png -> document-save.png
gtk-select-all.png -> edit-select-all.png
gtk-sort-ascending.png -> view-sort-ascending.png
gtk-sort-descending.png -> view-sort-descending.png
gtk-spell-check.png -> tools-check-spelling.png
gtk-stop.png -> process-stop.png
gtk-strikethrough.png -> format-text-strikethrough.png
gtk-underline.png -> format-text-underline.png
gtk-undo-ltr.png -> edit-undo.png
gtk-unindent-ltr.png -> format-indent-less.png
gtk-unindent-rtl.png -> format-indent-more.png
gtk-zoom-100.png -> zoom-original.png
gtk-zoom-fit.png -> zoom-fit-best.png
gtk-zoom-in.png -> zoom-in.png
gtk-zoom-out.png -> zoom-out.png
```

> * cairo mouse-event have wrong data

Could you show screenshot?

> typelib error with gtksoureview3

I've fixed it.

> sample/fractal.rb : no color, (all drawing in black) , same as x32, same under linux
> ... set_source_rgba() issue...

It has been fixed at master.

**Comment by kou** [comment]
> typelib error with gtksoureview3

Workaround: `ruby -r gtksourceview3 sample\test.rb`.

**Comment by glurp** [comment]
cell alignment
 - - -
3.0.2:
![snap09_15_16_02_30](https://cloud.githubusercontent.com/assets/27629/9878491/47808c14-5bc3-11e5-9a3a-926b43eac0b7.png)
old one:
![snap09_15_16_05_46](https://cloud.githubusercontent.com/assets/27629/9878582/bb11e966-5bc3-11e5-9514-71daa8805b08.png)

Also, as you can see, icons for +/- spinbox entry are nok...

**Comment by glurp** [comment]
Workaround: ruby -r gtksourceview3 sample\test.rb
ok after  a  'gem64 install gtksourceview3'

**Comment by glurp** [comment]
cairo mouse-event have wrong data
Could you show screenshot?
==>I was  wrong, x/y are ok with ruby x64

**Comment by glurp** [comment]
Could you change icon name from gtk-XXX? gtk-XXX name is obsoleted.
ok, for my icons load :) 
![snap09_15_16_32_14](https://cloud.githubusercontent.com/assets/27629/9879372/6ff6a472-5bc7-11e5-92e1-0735c21ddf22.png)

**Comment by glurp** [comment]
it's all!

**Comment by kou** [comment]
> cell alignment

Thanks. I've fixed it.

> Also, as you can see, icons for +/- spinbox entry are nok, idem for the comboBox ...

I've also fixed it.

**Comment by kou** [comment]
> for the fun :

Interesting application! :-)

**Comment by glurp** [comment]
Oups...

>gem install gtk3
Fetching: glib2-3.0.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing gtk3:
        ERROR: Failed to build gem native extension.

idem for x64
>gem64 install gtk3
Fetching: glib2-3.0.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing gtk3:
        ERROR: Failed to build gem native extension.

**Comment by kou** [comment]
Because I'm building gems for Windows now. :-)

**Comment by kou** [comment]
I've uploaded.

**Comment by glurp** [comment]
ok, all works!

Remain:
* mouse event data in x32 not valides (ok in x64)
* I use Stock.constants for get the list of icons in Stock, but all the names seems nok:
#<Gtk::IconThemeError::NotFound: L'icône « cdrom » n'est pas présente dans le thème Adwaita>
#<Gtk::IconThemeError::NotFound: L'icône « clear » n'est pas présente dans le thème Adwaita>
#<Gtk::IconThemeError::NotFound: L'icône « close » n'est pas présente dans le thème Adwaita>
. . . 

And colors rgba() are ok:
![snap09_16_21_07_02](https://cloud.githubusercontent.com/assets/27629/9915361/ee5467ba-5cb6-11e5-86d7-bc052514210e.png)

**Comment by kou** [comment]
> I use Stock.constants for get the list of icons in Stock, but all the names seems nok:

Use `Gtk::IconTheme.default.icons` instead.

**Comment by glurp** [comment]
Thank you for yours help,

**Comment by kou** [comment]
I'll look into about event data on 32bit.

(The fractal screenshot is good. :-)

**Comment by kou** [comment]
I confirmed that member offsets in the event data struct is wrong on 32bit Windows. (`g_field_info_get_offset()` for `GdkEventMtion::window` should return `4` but it returns `8`.) It may be a bug in GObjectIntrospection or our cross compile system.

If you can, could you try Python + GTK+ 3 on 32bit Windows? (If you can't, please use only 64bit Windows. ;-))
If Python + GTK+ 3 on 32bit Windows works well, our cross compile system will be buggy.
If Python + GTK+ 3 on 32bit Windows also doesn't work well, GObjectIntrospection will be buggy.

The following Python script may help you:

```python
from gi.repository import Gtk, Gdk

def motion_notify_event(widget, event):
    print(event.x, event.y)

window = Gtk.Window()
window.add_events(Gdk.EventMask.BUTTON_MOTION_MASK)
window.connect("motion_notify_event", motion_notify_event)
window.connect("destroy", Gtk.main_quit)
window.show_all()

Gtk.main()
```

**Comment by kou** [comment]
I found that a bug of our cross compile system... I'll fix it.

**Comment by kou** [comment]
Could you try this? http://pub.cozmixng.org/~kou/gdk3-3.0.3-x86-mingw32.gem
