### ISSUE TITLE
clutter-gtk unable to find Version references

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#557]
I am trying to implement the `ClutterGtk::Version.or_later?` method but I can not find any constants or methods that returns version values. Any ideas?

**Comment by kou** [comment]
I also confirmed that Clutter-GTK doesn't provide version information API.

OK. We don't provide `ClutterGtk::Version.or_later?`.

**Comment by cedlemo** [comment]
#308 
I close then.
