### ISSUE TITLE
gdk3 3.0.3 does not pass test for nil:NilClass

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#558]
gdk3 3.0.3 and also git head 9dd7fe9d3d2acadb2aed7ac096d12dda537bedf1 does not pass test with complaining about nil:NilClass like
```
--------------------------------------------------------------------------------
2015-09-21 00:31:53 +0900 running test for /home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gdk3
--------------------------------------------------------------------------------
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:128: warning: already initialized constant Gdk::Rectangle
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gdk3/lib/gdk3/loader.rb:52: warning: previous definition of Rectangle was here
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gdk3/lib/gdk3/loader.rb:105:in `apply_pending_rectangle_functions': undefined method `invoke' for nil:NilClass (NoMethodError)
        from /home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gdk3/lib/gdk3/loader.rb:73:in `post_load'
        from /home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:42:in `load'
        from /home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gdk3/lib/gdk3.rb:55:in `init'
        from test/run-test.rb:54:in `<main>'
--------------------------------------------------------------------------------
```

Other components depending on gdk3 fail similarly.

**Comment by kou** [comment]
Could you show your GTK+ version? 3.17.9?

**Comment by kou** [comment]
I want to see `Gdk-3.0.gir` on the environment. (I want to check whether `gdk_rectangle_get_type()` exists in the file or not.) Do you have URL for the file?

**Comment by mtasaka** [comment]
GTK3 is 3.17.9.
For Gdk-3.0.gir, please use below

https://mtasaka.fedorapeople.org/miscs/gtk+-3.17.9/Gdk-3.0.gir

**Comment by mtasaka** [comment]
I don't know the meaning of the following commit, however perhaps the following is related.

https://git.gnome.org/browse/gtk+/commit/?id=2495edc9fdd604fa9f052b4003a492d2b7230d37

**Comment by kou** [comment]
Thanks. It's very useful information provided by you.
It seems that https://git.gnome.org/browse/gtk+/commit/?id=724cc00f9baa8a808195eebfea686cef1d63d12c is the commit that changes behavior.

Could you try master? It may fix this problem.

**Comment by mtasaka** [comment]
Okay, fixed, thank you!

**Comment by kou** [comment]
Thanks for confirming it!
