### ISSUE TITLE
gdk3 unable to find Version references

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#560]
Same as clutter-gtk, I can not find any constants or methods that I could use in order to get the version informations

**Comment by kou** [comment]
OK. We don't provide `Gdk::Version.or_later?`. Users should use `Gtk::Version.or_later?` instead.

**Comment by cedlemo** [comment]
#308 for ref

**Comment by cedlemo** [comment]
@kou ,

Shouldn't we implement the Gdk::Version like we did for gio2 (from the GLib::Version)?

**Comment by kou** [comment]
Thanks for your suggestion.
But we can't do it because gdk3 doesn't depends on gtk3. gio2 depends on glib2. So we can use `GLib::Version` in gio2.

**Comment by cedlemo** [comment]
Oh yes, It will be a kind of circular require, isn't it?

**Comment by kou** [comment]
Yes.
