### ISSUE TITLE
Gio2 Unable to find version informations

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#569]
I can not find any constants or methods in order to get informations on the version of gio

**Comment by kou** [comment]
GIO is included in GLib. So we can version information in GLib:

  * `GLib::MAJOR_VERSION`
  * `GLib::MINOR_VERSION`
  * `GLib::MICRO_VERSION`
  * `GLib::VERSION`

**Comment by kou** [comment]
We just define `GLib::Version` as `Gio::Version`:

```ruby
module Gio
  Version = GLib::Version
end
```

**Comment by cedlemo** [comment]
Thanks
