### ISSUE TITLE
Gtk::Application command-line signal

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#581]
I started to write the main.rb and I have this kind of issue:

```ruby
require "gtk3"

class Demo < Gtk::Application
  def initialize
    super("org.gtk.Demo", [:non_unique, :handles_command_line])

    signal_connect "startup" do |application|
      puts "startup"
    end

    signal_connect "activate" do |application|
      puts "activate"
    end

    signal_connect "command-line" do |application, command_line|
      puts "cmd"
      puts command_line
    end
  end
end

demo = Demo.new

demo.run([$PROGRAM_NAME] + ARGV)
```

throw an error message:

```
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.6/lib/gobject-introspection/loader.rb: line 551
   Gtk-DEBUG **:Connecting to session manager
startup
cmd
#<Gio::ApplicationCommandLine:0x000000028f0a78>
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.6/lib/gobject-introspection/loader.rb:551:in `invoke': no implicit conversion from nil to integer
	 from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.6/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from main.rb:41:in `<main>'

```

This message disapears if I write this:

```ruby
    signal_connect "command-line" do |application, command_line|
      puts "cmd"
      puts command_line
       1
    end
```

**Comment by kou** [comment]
We must return integer in `command-line` signal handler. It's used for exit status. (`#run` returns the exit status.)

The document may help you: https://developer.gnome.org/gio/stable/GApplication.html#GApplication-command-line

Returning a correct value from signal handler is expected in all signal handlers. It's not only for `command-line` signal handler.

**Comment by cedlemo** [comment]
Sorry I have been misled by the gtk+/demos/gtk-demo/main.c where the command-line event callback is on the form:

```c
static void
command_line (GApplication            *app,
              GApplicationCommandLine *cmdline)
{
```

**Comment by kou** [comment]
Ah, I understood.
It may be a bug of the original gtk-demo. Could you report it to GTK+ developers?

**Comment by cedlemo** [comment]
Oh yes I can and I will do it even if I am a littre suprised that they do this kind of mistake.

**Comment by cedlemo** [comment]
Done https://bugzilla.gnome.org/show_bug.cgi?id=755692 .

**Comment by kou** [comment]
Thanks!!!
