### ISSUE TITLE
How to deal with GVariantDict

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#582]
Here is the code:

```ruby
require "gtk3"

class Demo < Gtk::Application
  def initialize
    super("org.gtk.Demo", [:non_unique, :handles_command_line])

    signal_connect "startup" do |application|
      puts "startup"
    end

    signal_connect "activate" do |application|
      puts "activate"
    end

    signal_connect "command-line" do |application, command_line|
      puts "cmd"
      options = command_line.options_dict
      puts options.inspect
      puts options.methods
      name = options.lookup("run", "&s")
      autoquit = options.lookup("autoquit", "b")
      list = options.lookup("list", "b")
      1
    end
  end
end

demo = Demo.new

demo.run([$PROGRAM_NAME] + ARGV)
```

The options variable that I get with `command_line.options_dict` should be the ruby implementation of the `GVariantDict` from glib but it doesn't seem to be well implemented.

**Comment by kou** [comment]
Could you use`command_line.arguments` and [OptionParser](http://docs.ruby-lang.org/en/2.2.0/OptionParser.html) instead of `options_dict`?

Because we don't have a plan to support `g_application_add_main_option()`. Parsing command line option in Ruby is convenience and Rubyish.

**Comment by cedlemo** [comment]
ok
