### ISSUE TITLE
Gtk::Builder#add_objects_from*

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#585]
@kou, 

I have to use one of those methods:

*     Gtk::Builder#add_objects_from_file
*     Gtk::Builder#add_objects_from_string
*     Gtk::Builder#add_objects_from_from_resource

They all works but in order to be consistent I thought that I had to write the method 

`Gtk::Builder#add_objects` and use hash argument like `Gtk::Builder#add_objects(:resource => "/gtk/org")`

But I have seen your implementation of `Gtk::Builder#add` : 

```ruby
    alias_method :add_from_string_raw, :add_from_string
    def add_from_string(string)
      add_from_string_raw(string, string.bytesize)
    end

    def add(target)
      if target.respond_to?(:to_path)
        add_from_file(target.to_path)
      elsif target.start_with?("<") or target.start_with?(" ")
        add_from_string(target)
      elsif File.exist?(target)
        add_from_file(target)
      else
        add_from_resource(target)
      end
    end
```

Should I consider that we just use hash argument form with initialize method?

**Comment by kou** [comment]
> They all works but in order to be consistent I thought that I had to write the method `Gtk::Builder#add_objects` and use hash argument like `Gtk::Builder#add_objects(:resource => "/gtk/org")`

I agree with it.

Do you try to implement it? If you don't try it, I'll implement it later.

**Comment by kou** [comment]
I've implemented but I didn't add `#add_objects`. I added `:object_ids` support to `#add` instead.
