### ISSUE TITLE
Gtk demo main.rb populate the TreeView

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#590]
@kou, 

In the main.ui file, the description of the Gtk TreeView is : 

```xml
  <object class="GtkTreeStore" id="treestore">
    <columns>
      <!-- column-name NAME -->
      <column type="gchararray"/>
      <!-- column-name TITLE -->
      <column type="gchararray"/>
      <!-- column-name FILENAME -->
      <column type="gchararray"/>
      <!-- column-name FUNC -->
      <column type="gpointer"/>
      <!-- column-name STYLE -->
      <column type="gint"/>
    </columns>
  </object>
```
My problem with this is the gpointer type, how can I adapt this ? I think that this question is related to the global question I asked you here #589.

**Comment by kou** [comment]
How about using `gchararray` instead of `gpointer`?
We can use `send(method_name)` to call method from `String` in Ruby. (We can do it in C.)

**Comment by cedlemo** [comment]
Ok Thanks!

**Comment by cedlemo** [comment]
After re-reading the C source code, the last main.rb I think that we should remove the column NAME and FUNC.

**Comment by kou** [comment]
I aggree with your proposals. You can go ahead!

> I am sorry but I cannot work efficiently if I can not plan how to implement some stuff.

No problem. :-)
If you have any problems, please ask us like this!

**Comment by cedlemo** [comment]
>If you have any problems, please ask us like this!

Ok
