### ISSUE TITLE
TODO: <TreeIterCompareFunc>(sort_func) callback is not supported yet.

### ISSUE THREAD

**Issue by dark-yux** [ruby-gnome2/ruby-gnome2#596]
Please Implement this in the next release. `<TreeIterCompareFunc>(sort_func)`

**Comment by kou** [comment]
I've implemented it.

**Comment by dark-yux** [comment]
Thank you!

**Comment by MTdeRuiter** [comment]
kou,

Any idea of when this patch will end up in the gem version?

In the meantime, do you happen to know the version when this was still working as intended?

**Comment by cosmo0920** [comment]
I think it is take a long time to ship the next release because we plan to drop CentOS 5 and Ubuntu 12.04 support.
In the meantime, please refer to this README section: https://github.com/ruby-gnome2/ruby-gnome2#install-from-github-master-branch and install yourself with master branch.
