### ISSUE TITLE
set_child_packing in gtk3 is unusable - raises ArgumentError

### ISSUE THREAD

**Issue by ibrahimtencer** [ruby-gnome2/ruby-gnome2#602]
If it is called like this:

    box.set_child_packing(@text_view, false, true, 0, nil)

then it raises the errors

    [redacted]: 'Gtk::Box#set_child_packing(child, expand, fill, padding, pack_type)' style has been deprecated. Use 'Gtk::Box#set_child_packing(child, :expand => nil, :fill => nil, :padding => nil, :pack_type => nil)' style.
    [redacted]/.rvm/gems/ruby-2.2.1/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:351:in `validate_arguments': Gtk::Box#set_child_packing: wrong number of arguments (2 for 5) (ArgumentError)

but then if you call it in the second style:

    box.set_child_packing(@text_view, expand: false, fill: true, padding: 0, pack_type: nil)

it raises the second error again, "(2 for 5)". The best workaround I've found is to actually remove all following child widgets and re-pack_start the one you want to change with different settings.

**Comment by ibrahimtencer** [comment]
Aha - this can actually be done instead with

    box.child_set_property(@text_view, :expand, false)

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.
