### ISSUE TITLE
Adjustment#value=

### ISSUE THREAD

**Issue by ibrahimtencer** [ruby-gnome2/ruby-gnome2#605]
So I'm using gtk3, and trying to get a TextView to scroll to the bottom every time the text is changed. My understanding is that the way to do this is by changing its vertical adjustment value. But, this doesn't work.

    @field = Gtk::TextView.new
    @scroll = Gtk::ScrolledWindow.new
    @scroll.add(@field)

    @field.buffer.signal_connect_after("changed") do |b|
      p @scroll.vadjustment.value #=> 0.0
      p @scroll.vadjustment.upper #=> 608.0
      @scroll.vadjustment.value = @scroll.vadjustment.upper
      p @scroll.vadjustment.value #=> 0.0
      true
    end

But the value is of course updated internally when the scrollbar is dragged by the user. Is there a different way to do it or is this just a bug?

**Comment by ibrahimtencer** [comment]
Hmm, this is strange. It turns out I was setting a size request on a different TextView inside of a ScrolledWindow, which doesn't work - you have to set it on the ScrolledWindow. Now, the Adjustment value is getting updated, but the upper value seems to be inaccurate - the code above now puts the second-to-last line in the TextView at the bottom with the last line invisible (and you can manually scroll down to show that the upper value is wrong).

**Comment by ibrahimtencer** [comment]
More info:

-The value returned by #upper is much higher than the actual highest possible value (the difference is variable)

-If you set it to the value of #upper or even somewhat lower than that, it always scrolls down so that everything but the last line in the TextView is visible (i.e. the bottom edge is at the top of the last line).

**Comment by cedlemo** [comment]
Can you provide a minimal example?

**Comment by ibrahimtencer** [comment]
```ruby
require 'gtk3'

class ScrollWindow < Gtk::Window
  def initialize
    super

    signal_connect("destroy") {Gtk.main_quit}

    @vbox = Gtk::Box.new(:vertical, 3)

    @scroll = Gtk::ScrolledWindow.new
    @field = Gtk::TextView.new
    @scroll.add(@field)

    @vbox.pack_start(@scroll, expand: true, fill: true)

    button = Gtk::Button.new(label: "Add and scroll")
    button.signal_connect "clicked" do
      @field.buffer.text += "h\n"*100

      puts "lower #{@scroll.vadjustment.lower}"
      puts "old val #{@scroll.vadjustment.value}"
      puts "upper #{@scroll.vadjustment.upper}"
      @scroll.vadjustment.value = @scroll.vadjustment.upper
      puts "after setting #{@scroll.vadjustment.value}"
    end

    @vbox.add(button)

    add(@vbox)

    show_all
  end
end

window = ScrollWindow.new
Gtk.main
```

In this example, the expected behavior is to scroll all the way to the bottom when you press the button. Instead, it scrolls down for me but not all the way to the bottom. "upper" always equals "after" plus 663.0 for whatever reason.

**Comment by cedlemo** [comment]
I have something that work for me could you confirm ?

```ruby
require 'gtk3'

class ScrollWindow < Gtk::Window
  def initialize
    super

    signal_connect("destroy") {Gtk.main_quit}
    set_default_size 400, 400
    @vbox = Gtk::Box.new(:vertical, 0)

    @scroll = Gtk::ScrolledWindow.new
    @scrollbar = @scroll.vscrollbar
    @field = Gtk::TextView.new
    @scroll.add(@field)

    @vbox.pack_start(@scroll, expand: true, fill: true)
    vadj = @scrollbar.adjustment
    vadj.signal_connect "changed" do |a|
      puts "upper #{a.upper}"
      a.value = a.upper
    end
    button = Gtk::Button.new(label: "Add and scroll")
    button.signal_connect "clicked" do
      @field.buffer.text += "h\n"*100
#      adj = @scrollbar.adjustment
#      puts "lower #{adj.lower}"
#      puts "old val #{adj.value}"
#      puts "upper #{adj.upper}"
#      adj.value = adj.upper - adj.page_size
#      puts "after setting #{adj.value}"
    end
    
    @vbox.add(button)

    add(@vbox)

    show_all
  end
end

window = ScrollWindow.new
Gtk.main
```
The code is ugly but still readable.

**Comment by ibrahimtencer** [comment]
Yep, that works perfectly. Thanks!

**Comment by cedlemo** [comment]
@ibrahimtencer or @kou ,

I think you can close this one.

**Comment by kou** [comment]
@cedlemo Thanks!
