### ISSUE TITLE
Gtk::Widget#destroyed

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#608]
This method which should be used like this ( I though):
    
```ruby
mywidget.destroyed 
# or
Gtk::Widget.destroyed(mywidget)
```

Can only be use like this:

```ruby
mywidget.destroyed(mywidget)
```

*   api https://developer.gnome.org/gtk3/unstable/GtkWidget.html#gtk-widget-destroyed
*   usage : https://git.gnome.org/browse/gtk+/tree/demos/gtk-demo/scale.c#n25

```c
     g_signal_connect (window, "destroy",
                        G_CALLBACK (gtk_widget_destroyed), &window);
```

The ruby adaptation:

```ruby
    window.signal_connect("destroy") { window.destroyed(window) }
```

I don't even know if this function is needed with the ruby bindings.

**Comment by kou** [comment]
We don't need to use `gtk_widget_destroyed()` because it just sets `NULL` to variable for widget pointer in C. We don't need to manage `NULL` In Ruby.
