### ISSUE TITLE
MenuPositionFunc support

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#612]
calling  GtkMenu.new.popup()
I get:
Error GTK : TODO: <MenuPositionFunc>(func) callback is not supported yet. :
     /home/regis/.rvm/gems/ruby-2.1.2/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `invoke'
     /home/regis/.rvm/gems/ruby-2.1.2/gems/gobject-introspection-3.0.7/lib/gobject-introspection/loader.rb:551:in `block in define_method'
     /home/regis/.rvm/gems/ruby-2.1.2/gems/Ruiby-3.7.0/lib/ruiby_gtk/dsl/menus_popup.rb:22:in `block (2 levels) in popup'

i thin This codes worked before 3.0.0.

**Comment by kou** [comment]
Thanks for your report.
I've implemented it.
