### ISSUE TITLE
Gtk::PageSetupUnixDialog deprecated ?

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#615]
I was trying to adapt the pagesetup.c demo and during my tests I have had this output in irb:

```
Gtk::PageSetupUnixDialog.methods
GLib::DeprecatedError: (irb):7:in `irb_binding': 'Gtk::PageSetupUnixDialog' has been deprecated. Use 'Gtk::PrintOperation' instead.
	from /home/cedlemo/.gem/ruby/2.2.0/gems/glib2-3.0.7/lib/glib2/deprecatable.rb:127:in `const_missing'
	from (irb):7
	from /usr/bin/irb:11:in `<main>'
```

The problem is that the pagesetup.c demo still exist (gtk-demo are not update?) and when I check the documentation, there are no messages of deprecation usage.

for both:

*    https://developer.gnome.org/gtk3/stable/GtkPageSetupUnixDialog.html
*    https://developer.gnome.org/gtk3/unstable/GtkPageSetupUnixDialog.html

**Comment by kou** [comment]
The class isn't introspectable because the class is only available on Unix. It means that GObject Introspection based bindings can't use the class.

`demos/gtk-demo/pagesetup.c` is only built on Unix.

**Comment by cedlemo** [comment]
Sorry I thought that the  OS_UNIX in the Make file was used in order to say not windows system ,you know? like the following code that should be closer to what I was thinking.

```ruby
module OS
  def OS.windows?
    (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  end

  def OS.mac?
   (/darwin/ =~ RUBY_PLATFORM) != nil
  end

  def OS.unix?
    !OS.windows?
  end

  def OS.linux?
    OS.unix? and not OS.mac?
  end
end
```

**Comment by kou** [comment]
We don't need to provide an example for `Gtk::PageSetupUnixDialog`!
So `OS.unix?` isn't needed.

**Comment by cedlemo** [comment]
>So OS.unix? isn't needed.

That was not my point. Nevermind .

> We don't need to provide an example for Gtk::PageSetupUnixDialog!

Ok I get it. Sorry to bother!

**Comment by kou** [comment]
No problem. :-)
