### ISSUE TITLE
Css doesn't apply to the GtkWindow

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#645]
I have updated the demo css_pixbufs and I have no error except the fact that I can not display the images or the animations on the window with the default css .

if I replace the css selector `GtkWindow` with the generic one `*{}`, I am able to display the images but I can not see any animations.

Any Ideas ?

**Comment by kou** [comment]
[GtkInspector](https://wiki.gnome.org/Projects/GTK%2B/Inspector) may help you.

```text
% GTK_DEBUG=interactive gtk3/sample/gtk-demo/main.rb
```

**Comment by cedlemo** [comment]
I will use it next time. Thx
