### ISSUE TITLE
Gtk::TreeStore#inserte is missing optional values parameter

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#659]
Here is a request that have been made on the ruby-gnome2-devel-en : 

> Hi,
with the old API it was possible to use
       `Gtk::TreeStore#inserte parent, position, values`

>where the values of the cells are given as an array or hash as optional 
last parameter. With the gi-bindings it is gone, but it was very handy.
>
>Cheers, detlef

It only exists the `Gtk::TreeStore#insert_with_values` that I was not able to use. The Capi provides this two functions : 

*    gtk_tree_store_insert_with_values ()
*    gtk_tree_store_insert_with_valuesv ()

The latter is dedicated to the bindings usage but I was not able to find any glue code in the gtk3 C parts so I guess this is not implemented.

I would like to point out to you that the `Gtk::ListStore` provides the method `Gtk::ListStore#set_values` so I think that for consistency, it would be great to have : 

*    Gtk::ListStore#set_values (already done)            
*    Gtk::ListStore#insert_with_values
*    Gtk::TreeStore#set_values
*    Gtk::TreeStore#insert_with_values  

If you agree with this, the remaining question is how should I implement them ?

*    using ruby 
*    using C

**Comment by kou** [comment]
Thanks for summarizing it.
I've implemented them in Ruby.

**Comment by cedlemo** [comment]
Ok , Thanks.
