### ISSUE TITLE
How to add a free data callback with G_DEF_CLASS_WITH_GC_FUNC

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#661]
in the Glib Regex part that I am working on, there are 2 class `GLib::Regex` and `GLib::MatchInfo`. 

Now I just use the macro `G_DEF_CLASS` in order to create the class but the problem is that the regex and matchinfo data need to be freed ( `g_regex_unref` and `g_match_info_unref` or `g_match_info_free`)

I have found in the glib C files the macros `G_DEF_CLASS_WITH_GC_FUNC` which could be great except that I can hardly see how is the form of the callback to use. 

Have you got any example or instructions ?

**Comment by kou** [comment]
Try the following code:

```c
static void
regex_free(gpointer object)
{
    GRegex *regex = object;

    g_regex_unref(regex);
}

void
Init_glib_regex(void)
{
    VALUE RG_TARGET_NAMESPACE =
        G_DEF_CLASS_WITH_GC_FUNC(G_TYPE_REGEX, "Regex", mGLib,
                                 NULL, regex_free);
}
```

**Comment by cedlemo** [comment]
Thanks.
