### ISSUE TITLE
GLib::MatchInfo and Garbage collector.

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#670]
@kou, 

with the standard C MACROS I have managed the creation of the class `GLib::MatchInfo` and how its internal memory is freed when an instance is garbage collected. However it could still exist one problem with this class. Look here is one function of the C api that is used in order to get a match info:

```c
gboolean
g_regex_match (const GRegex *regex,
               const gchar *string,
               GRegexMatchFlags match_options,
               GMatchInfo **match_info);
```

The doc says about the string : 

> string is not copied and is used in GMatchInfo internally. If you use any GMatchInfo method (except g_match_info_free()) after freeing or modifying string then the behaviour is undefined.

Knowing that I have implemented it like this:

```c
static VALUE
rg_match(gint argc, VALUE *argv, VALUE self)
{
  VALUE string, match_options;
  gboolean matched = FALSE;
  GMatchInfo *_match_info;

  rb_scan_args(argc, argv, "20", &string, &match_options);
  
  matched = g_regex_match(_SELF(self),
                          RVAL2CSTR(string),
                          NUM2UINT(match_options),
                          &_match_info);
  if (matched == FALSE)
    return Qnil;
  else
    return BOXED2RVAL( _match_info, G_TYPE_MATCH_INFO);
}
```
The test works fine : 

```ruby
class TestMatchInfo < Test::Unit::TestCase
  def setup
    @regex_pattern = "[A-Z]+"
    @matching_string = "abc DEF"
    @non_matching_string = "abc def"
    @regex = GLib::Regex.new(@regex_pattern, 0, 0)
  end

  def test_string
    match_info = @regex.match(@matching_string, 0)
    assert_equal(match_info.string, @matching_string)
  end
```

But if the string that is used to get the match is freed and then if we use `GLib::MatchInfo#string` (`g_match_info_get_string`) this could result in an undefined behavior.

I have already had to deal with this kind of problem and someone told me that I should set the string variable as an instance variable of the `GLib::MatchInfo` so that the Garbage Collector won't collect the string if there is a `GLib::MatchInfo` instance that holds it. (source : http://stackoverflow.com/questions/30410801/ruby-c-extension-how-to-manage-garbage-collection-between-2-objects )

*    Do you agree with this ?

If yes
*     should I implement this in C or Ruby ?
*    should I just use a call to the string instance variable and not implement g_match_info_get_string

**Comment by kou** [comment]
It's no problem that `GLib::MatchInfo` object refers the target string.

Note that we need to ensure that the target string is frozen. If the target string isn't frozen, the target string may be changed destructively by `String#replace!` and so on.

If the target string isn't frozen string, we should `#dup` and `#freeze` the duplicated target string.

It should be implemented in C. If you can't find how to implement it in C, I can tell you.

It's no problem that `GLIb::MatchInfo#string` returns the target string in Ruby instead of calling `g_match_info_get_string()`

Do I answer all your questions?

**Comment by cedlemo** [comment]
> Do I answer all your questions?

Yes I think so, this is what I have done:
*    I get the string that is given
*    I create a copy /dup of it
*    I freeze the copy
*    I set this string as an instance variable in the `GLib::MatchInfo` instance.

here is the C code:

```c
static VALUE
rg_match(gint argc, VALUE *argv, VALUE self)
{
  VALUE string, match_options;
  gboolean matched = FALSE;
  GMatchInfo *_match_info;

  rb_scan_args(argc, argv, "20", &string, &match_options);
  
  VALUE dup_string, match_info;
  dup_string = rb_str_dup(string);
  rb_str_freeze(dup_string);

  matched = g_regex_match(_SELF(self),
                          RVAL2CSTR(dup_string),
                          NUM2UINT(match_options),
                          &_match_info);
  
  if (matched == FALSE)
    return Qnil;
  else
  {  
    match_info = BOXED2RVAL(_match_info, G_TYPE_MATCH_INFO);
    rb_iv_set(match_info, "@string", dup_string);
    return match_info;
  }
}
```

And here is the C code for the method `GLib::MatchInfo#string`

```c
static VALUE
rg_string(VALUE self)
{
  return  rb_iv_get(self, "@string");
}
```

I hope that it is what you expected.

**Comment by kou** [comment]
Thanks for providing code snippets!
It's almost good!

I hope that the code reduces needless object allocation:

```c
VALUE target_string;
if (OBJ_FROZEN(string)) {
  target_string = string;
} else {
  target_string = rb_str_dup(string);
  rb_str_freeze(target_string);
}
```

**Comment by cedlemo** [comment]
Oh right, I will make the changes.

Can you have a look on the pull request #652 . I have finished the `GLib::Regex` implementation and it don't remains a lot of works to do before I finish the `GLib::MatchInfo` implementation.

There is one point on which I would like a closer review : the implementation of ``GLib::Regex#replace_eval`
this is the last commit for it:

https://github.com/cedlemo/ruby-gnome2/commit/dc625846fd372dc2f5e9b6cb521d95fd74157991

Many thanks kou
