### ISSUE TITLE
Add missing ! to Gtk::TreePath#next, #prev, #up and #down

### ISSUE THREAD

**Issue by kou** [ruby-gnome2/ruby-gnome2#683]
https://sourceforge.net/p/ruby-gnome2/mailman/message/34788222/

It should be done in `Gtk::Loader#load_method_info`.

**Comment by kou** [comment]
Done by #694.
(Adding tests is better.)

**Comment by cedlemo** [comment]
>(Adding tests is better.)

Message received :-) (I will do them today or tomorrow)

**Comment by kou** [comment]
Wow! Thanks!
