### ISSUE TITLE
Should we start to use `dist: trusty`?

### ISSUE THREAD

**Issue by cosmo0920** [ruby-gnome2/ruby-gnome2#706]
I've got success to run tests except for `ruby-head` environment: https://travis-ci.org/ruby-gnome2/ruby-gnome2/builds/108464901

But we should test on legacy Environment like CentOS 5.
Should we migrate Travis CI testing to Ubuntu Trusty 14.04 or keep it as-is for now?

**Comment by kou** [comment]
We drop Ubuntu 13.10 or older and CentOS 5 support from now! And we also drop Ruby 2.0 support.
We should migrate to Ubuntu 14.04 on Travis CI.

**Comment by cosmo0920** [comment]
Hmm, I see.

Perhaps, we should install gi packages which are gir1.2-clutter-1.0, gir1.2-clutter-gst-2.0, and gir1.2-webkit2-3.0 before testing on Trusty in Travis CI.

**Comment by cosmo0920** [comment]
Migrating from Precise to Trusty is done.
