### ISSUE TITLE
gtksourceview2-3.0.7 - Gem install failure on Windows 

### ISSUE THREAD

**Issue by Buzio** [ruby-gnome2/ruby-gnome2#714]
Hi there,
I have installed (on Windows Vista/Seven/10)

ruby 2.1.7p400 (2015-08-18 revision 51632) [i386-mingw32]
DevKit-mingw64-32-4.7.2-20130224-1151-sfx

Installation of gtksourceview2-3.0.7 on Windows fails with this message in mkmf.log (only last rows...)

..
have_header: checking for rb_cairo.h... -------------------- yes
"gcc -E -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/cairo-1.14.3-x86-mingw32/vendor/local/include -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/cairo-1.14.3-x86-mingw32/ext/cairo -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/cairo-1.14.3-x86-mingw32/vendor/local/include -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/cairo-1.14.3-x86-mingw32/ext/cairo -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/gtk2-3.0.7-x86-mingw32/vendor/local/include -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/gtk2-3.0.7-x86-mingw32/ext/gtk2 -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/gdk_pixbuf2-3.0.7-x86-mingw32/vendor/local/include -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/gdk_pixbuf2-3.0.7-x86-mingw32/ext/gdk_pixbuf2 -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/pango-3.0.7-x86-mingw32/vendor/local/include -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/pango-3.0.7-x86-mingw32/ext/pango -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/atk-3.0.7-x86-mingw32/vendor/local/include -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/atk-3.0.7-x86-mingw32/ext/atk -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/glib2-3.0.7-x86-mingw32/vendor/local/include -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/glib2-3.0.7-x86-mingw32/ext/glib2 -IC:/Ruby21/include/ruby-2.1.0/i386-mingw32 -IC:/Ruby21/include/ruby-2.1.0/ruby/backward -IC:/Ruby21/include/ruby-2.1.0 -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/gtksourceview2-3.0.7/ext/gtksourceview2 -IC:/Ruby21/lib/ruby/site_ruby/2.1.0/i386-msvcrt  -IC:/Ruby21/lib/ruby/vendor_ruby/2.1.0/i386-msvcrt  -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wall -Waggregate-return -Wcast-align -Wextra -Wformat=2 -Winit-self -Wlarger-than-65500 -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wswitch-default -Wswitch-enum -Wundef -Wunsafe-loop-optimizations -Wwrite-strings -IC:/Ruby21/lib/ruby/gems/2.1.0/gems/cairo-1.14.3-x86-mingw32/ext/cairo -mms-bitfields -mms-bitfields -I/home/vagrant/rcairo.win32/vendor/local/include/cairo -I/home/vagrant/ruby-gnome2.win32/glib2/vendor/local/include -I/home/vagrant/ruby-gnome2.win32/glib2/vendor/local/include/glib-2.0 -I/home/vagrant/ruby-gnome2.win32/glib2/vendor/local/lib/glib-2.0/include -I/home/vagrant/rcairo.win32/vendor/local/include/pixman-1 -I/home/vagrant/rcairo.win32/vendor/local/include -I/home/vagrant/rcairo.win32/vendor/local/include/freetype2 -I/home/vagrant/rcairo.win32/vendor/local/include/libpng16 -I/home/vagrant/rcairo.win32/vendor/local/include/libxml2  conftest.c -o conftest.i"
cc1.exe: warning: /home/vagrant/rcairo.win32/vendor/local/include/cairo: No such file or directory [enabled by default]
cc1.exe: warning: /home/vagrant/ruby-gnome2.win32/glib2/vendor/local/include: No such file or directory [enabled by default]
cc1.exe: warning: /home/vagrant/ruby-gnome2.win32/glib2/vendor/local/include/glib-2.0: No such file or directory [enabled by default]
cc1.exe: warning: /home/vagrant/ruby-gnome2.win32/glib2/vendor/local/lib/glib-2.0/include: No such file or directory [enabled by default]
cc1.exe: warning: /home/vagrant/rcairo.win32/vendor/local/include/pixman-1: No such file or directory [enabled by default]
cc1.exe: warning: /home/vagrant/rcairo.win32/vendor/local/include: No such file or directory [enabled by default]
cc1.exe: warning: /home/vagrant/rcairo.win32/vendor/local/include/freetype2: No such file or directory [enabled by default]
cc1.exe: warning: /home/vagrant/rcairo.win32/vendor/local/include/libpng16: No such file or directory [enabled by default]
cc1.exe: warning: /home/vagrant/rcairo.win32/vendor/local/include/libxml2: No such file or directory [enabled by default]
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include "winsock2.h"
4: #include "windows.h"
5: #include "rb_cairo.h"

setup_windows: checking for Windows... -------------------- yes
have_package: checking for gtksourceview-2.0... -------------------- no
find_executable: checking for pacman... -------------------- no
find_executable: checking for brew... -------------------- no
find_executable: checking for port... -------------------- no

...
I can't understand the meaning of last rows
Can you help me?

thanks in advance

**Comment by marcozimmer** [comment]
Hi,
I have the same problem... on Windows Vista/7/10 too... not tested on 8/8.1, but I think is the same...

Any suggestions?

Thanks.

**Comment by kou** [comment]
gtksourceview2 doesn't support Windows. Use gtksourceview3 instead.

**Comment by pintubigfoot** [comment]
Why not supported?

**Comment by kou** [comment]
Because it's old.

**Comment by pintubigfoot** [comment]
Why not supporting old one? Old products usually are stable and have wider support.

**Comment by kou** [comment]
If you can work on it, we can support it. Do you work on it?
