### ISSUE TITLE
Segfault in Gtk::TextBuffer#apply_tag

### ISSUE THREAD

**Issue by zznull** [ruby-gnome2/ruby-gnome2#716]
[error.txt](https://github.com/ruby-gnome2/ruby-gnome2/files/136780/error.txt)

**Comment by cedlemo** [comment]
As @kou must be busy, I will try to help you,

the first look at you error message tells me that it is maybe more related to the _did_you_mean_ gem.

As you did not provide a sample of code that generate a segfault, I tried the sample (you should try it too): https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gtk3/sample/misc/textbuffer-serialize.rb. I have used the color button and font button (that calls the method `Gtk::TextBuffer#apply_tag`) from it and I did not have any problems.

*    Could you post a minimum code that reproduce your problem. 
*    Could you indicate some informations on your environment (OS, gems from git or installed using gem)
*    Could you try the example _textbuffer-serialize.rb_ from the gtk3/sample/misc.

**Comment by zznull** [comment]
@cedlemo thank you for your response.

I have created a minimal script to reproduce it. It involves executing apply_tag n*1000 times to make it crash every run. https://gist.github.com/zznull/68b3a3501352c6a1e50a

This is on an x86_64 debian (testing), using gem gtk3-3.0.7

I tried gtk3/sample/misc/textbuffer-serialize.rb and it runs fine.

**Comment by zznull** [comment]
Also this does not happen when using gtk3 gem version 2.2.5

**Comment by cedlemo** [comment]
Okayy,

> Also this does not happen when using gtk3 gem version 2.2.5

Which ruby version (the did_you_mean gem have been bundled with the 2.3.0 https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/ )

But after reading the your script, I am not sure that it is related to the gem did_you_mean. I continue investigating.

**Comment by zznull** [comment]
This is on `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`

**Comment by cedlemo** [comment]
I have seen this : 
https://bugs.ruby-lang.org/issues/12078

I had the same issue when I was testing some stuff:

```
Error: test: eval(TestRegex::replace)/usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb:10: [BUG] Segmentation fault at 0x000a646e6520d
```

**Comment by zznull** [comment]
https://bugs.ruby-lang.org/issues/12078 was a different bug or they didn't fix it. This still happens on `ruby 2.4.0dev (2016-02-27 trunk 53957)`

I don't think I know how to create a minimal script to reproduce it that doesn't rely on the gtk3 gem.

**Comment by cedlemo** [comment]
>was a different bug

Yes but the problem is that it hides the informations that could help us to find the origin of the problem.

I have tried your script with different modifications and with the following modifications, the script doesn't crash:

```
buffer = text_view.buffer
1.upto(50) do
  buffer.ansi_sgr(['0'])
  buffer.print_direct('Normal')
  buffer.ansi_sgr(['0', '1', '31'])
#  buffer.print_direct('Bold')
  buffer.ansi_sgr(['0'])
  buffer.print_direct("Normal\n")
end
```

I am still wondering why.

**Comment by zznull** [comment]
I tried that modification and it does crash. The problem is that it sometimes doesn't crash at all, even with 1000 iterations.

**Comment by zznull** [comment]
buffer.ansi_sgr(['0'...])

causes the tag array to be replaced

    @current_sgr_tags = []

An interesting result is if I do GC.start right after the tag array is replaced:

    1.upto(1000) do
      buffer.ansi_sgr(['0'])
      buffer.print_direct('Normal')
      buffer.ansi_sgr(['0', '1', '31'])
      GC.start
      buffer.print_direct('Bold')
      buffer.ansi_sgr(['0'])
      buffer.print_direct("Normal\n")
    end

**Comment by cedlemo** [comment]
-_- 

try this:

    ruby --disable=did_you_mean segfault_script.rb

The script that segfault, doesn't crash with this. (I have done multiple tests)

**Comment by zznull** [comment]
No change, running with `ruby --disable=did_you_mean` produces https://gist.github.com/zznull/198ad1c3064d5bc113f8

**Comment by cedlemo** [comment]
Erf you are right, 
with --disable=did_you_mean the following did not crash
```
1.upto(50) do
  buffer.ansi_sgr(['0'])
#...
  buffer.print_direct("Normal\n")
end
```

but the option `--disable=did_you_mean` doesn't have any effect with

```
1.upto(200) do
  buffer.ansi_sgr(['0'])
#...
  buffer.print_direct("Normal\n")
end
```

**Comment by cedlemo** [comment]
@zznull,

I was doing some test and is this could be an alternative for you ?

```ruby
#!/usr/bin/env ruby
require 'gtk3'

tags = {}
def print_tag_with_coresponding_pango(buffer, style, tags)
  end_iter = buffer.end_iter
  if style != "\n"
    buffer.insert(end_iter, style, :tags => [tags[style.to_sym]])
  else
    buffer.insert(end_iter, style)
  end
end

def print_some_stuffs(buffer, tags)
  print_tag_with_coresponding_pango(buffer, "red", tags)
  print_tag_with_coresponding_pango(buffer, "\n", tags)
  print_tag_with_coresponding_pango(buffer, "bold", tags)
  print_tag_with_coresponding_pango(buffer, "\n", tags)
  print_tag_with_coresponding_pango(buffer, "underline", tags)
end

window = Gtk::Window.new(:toplevel)

window.set_default_size 200, 100
window.signal_connect "destroy" do
  Gtk.main_quit
end
text_view = Gtk::TextView.new
buffer = Gtk::TextBuffer.new
tags[:bold] = buffer.create_tag("bold", "weight" => Pango::WEIGHT_BOLD)
tags[:underline] = buffer.create_tag("underline", "underline" => Pango::UNDERLINE_SINGLE)
tags[:red] = buffer.create_tag("red", "foreground-rgba" => Gdk::RGBA.new(1,0,0.1,1))
text_view.buffer = buffer

sw = Gtk::ScrolledWindow.new
sw.add(text_view)
window.add(sw)
window.show_all
1.upto(10000) do
  print_some_stuffs(text_view.buffer, tags)
end
Gtk.main
```

The 10000 insertion take some seconds to be done but I have not experienced any segfault with it while I still have some issue with your script.

**Comment by kou** [comment]
Thanks for your report.
I've fixed it at master.
