### ISSUE TITLE
Poppler::Document - unable to close file handle?

### ISSUE THREAD

**Issue by MattFenelon** [ruby-gnome2/ruby-gnome2#732]
I can't seem to find a way to get Poppler::Document to close its file handle, which is stopping my code cleaning up after itself.

I'm running some code similar to this:

  ```ruby
  Dir.mktmpdir(nil, Rails.root.join('tmp/').to_s) do |tmp_dir|
    # Copy PDF to tmp dir
    doc = Poppler::Document.new pdf_in_temp_dir
    # do some work on PDF
  end
  ```

When the block ends, I receive an exception `Directory not empty @ dir_s_rmdir`. If I remove the Poppler code, the block ends without an exception.

Is there a way, that I'm not seeing, to get the Document to close the file handle?

**Comment by kou** [comment]
Could you provide a script that can reproduce the problem on my environment instead of code snippet?

**Comment by kou** [comment]
Windows?

**Comment by MattFenelon** [comment]
I've done some more digging, it turns out this is only happening when I run my app on an NFS share, NFS is creating hidden .nfsNNNN files (where NNN is a long number), which seems to be due to https://www.sunmanagers.org/archives/1998/0229.html. I'm not sure if this is a problem in the library or not.

My script is below:

```ruby
require "poppler"
require "open-uri"
require "tmpdir"

Dir.mktmpdir(nil, "tmp/") do |dir|
  local_path = dir + "/pdf-sample.pdf"
  open("http://www.polyu.edu.hk/iaee/files/pdf-sample.pdf") do |pdf|
    IO.copy_stream(pdf, local_path)
  end

  Poppler::Document.new local_path
end
```

**Comment by MattFenelon** [comment]
Ubuntu 14.04

**Comment by kou** [comment]
Thanks.

Could you try the following script?:

```ruby
require "poppler"
require "open-uri"
require "tmpdir"

Dir.mktmpdir(nil, "tmp/") do |dir|
  open("http://www.polyu.edu.hk/iaee/files/pdf-sample.pdf", "rb") do |pdf|
    Poppler::Document.new pdf.read
  end
end
```

**Comment by MattFenelon** [comment]
No error that time, just the object:

```
#<Poppler::Document:0x2318fb0 ptr=0x204f840>
```

**Comment by kou** [comment]
Thanks for confirming it. Please use the style if it's depends on filesystem.

**Comment by MattFenelon** [comment]
That's sort of what I've done, I'm downloading the file separately, reading the content into memory, and then passing that to Document. I'm going to close the bug anyway, it seems more related to the way NFS works.
