### ISSUE TITLE
When do you plan to make a new release?

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#734]
Like in the title?

When do you plan to make a new release with the last modifications?

**Comment by cosmo0920** [comment]
I think that there are big blockers for this issue...: #707 and #708

**Comment by cedlemo** [comment]
>First, we need to list the versions of each library on Ubuntu 14.04 and CentOS 6. We use them for minimum supported versions.

you talk about the versions of Glib, gtk 3 2 and everything? (Maybe I can do this)

No chance that you do a minor release  before ?

you know with all the recents change and the Regex support ?

> We should remove codes for Ruby 2.0 or older to improve maintainability.

any hints on this (ruby capi or ruby code ?), I have not your knowledge in ruby but I can find some time and I can do basic editing/testing.

**Comment by kou** [comment]
#707 and #708 aren't blocker.
Lacking my resource is the blocker.

First, we need to add an entry for the new release to NEWS.

**Comment by cedlemo** [comment]
> First, we need to add an entry for the new release to NEWS

you mean a list to all the commits/ modifications that have been done since the last release (october 2015 ) ?

**Comment by kou** [comment]
> you mean a list to all the commits/ modifications that have been done since the last release (october 2015 ) ?

Yes. (But we should not pick all commits. We just pick changes that will effect to users.)

**Comment by shevegen** [comment]
I can try to help a bit more - with the wiki, for instance, also with some of the smaller issues etc...

The only thing I can not help much with is the C code. :)

**Comment by kou** [comment]
Thanks.
https://github.com/ruby-gnome2/ruby-gnome2/blob/master/release.rd describes how to release. (But some descriptions are out of date...)

If you can find any work what you can, please work on it.

**Comment by kou** [comment]
> https://github.com/ruby-gnome2/ruby-gnome2/blob/master/release.rd describes how to release. (But some descriptions are out of date...)

`rake dist:test` exists for https://github.com/ruby-gnome2/ruby-gnome2/blob/master/release.rd#L22

`rake gem:windows:build` for https://github.com/ruby-gnome2/ruby-gnome2/blob/master/release.rd#L68

**Comment by cedlemo** [comment]
@kou I am Ok to work on the release news if you want.

**Comment by kou** [comment]
Thanks for working on updating NEWS!

I'm sorry but I couldn't imagine the new entry in [NEWS](https://github.com/ruby-gnome2/ruby-gnome2/blob/master/NEWS) from the sumup.txt.

Could you create a new entry for changes between "2015-10-06" and "2015-10-31"? You can use `git log --after="2015-10-06" --before="2015-10-31"'.

**Comment by cedlemo** [comment]
>I'm sorry but I couldn't imagine the new entry in NEWS from the sumup.txt.
I am sorry too, was it because there is too many entries or because I have done something wrong?

>Could you create a new entry for changes between "2015-10-06" and "2015-10-31"?

Of course, do I proceed like I did ? (I get git logs, I mark the interesting lines generate a sumup and  create a gist)

**Comment by kou** [comment]
Thanks.

https://github.com/ruby-gnome2/ruby-gnome2/commit/9bccda60dbb49713c6a7b736ff4a4f2d3e647511 is an expected output. It's OK to me that your work outputs text like the commit.

FYI: I used the following command line to get information for the commit:

```text
% git log -p --decorate --stat --reverse --before="2015-10-31" 3.0.7..
```

I searched by `^commit` to go to next (or previous) commit against the above command line's output.

**Comment by cedlemo** [comment]
Ok so I do the rest now ? do you want a month by month work so that you can easily check it?

**Comment by kou** [comment]
> Ok so I do the rest now ? do you want a month by month work so that you can easily check it?

Yes please. Could you work on it month by month?

**Comment by cedlemo** [comment]
@kou, I have read the file https://github.com/ruby-gnome2/ruby-gnome2/blob/master/release.rd and it seems that you doesn't make any annoucement in r/gnome or r/ruby is it a choice?

**Comment by kou** [comment]
Do r/gnome and r/ruby mean?
They mean ruby-gnome2-devel-en and ruby-talk?

**Comment by cedlemo** [comment]
No I was thinking of the sub-reddit https://www.reddit.com/r/ruby/ and https://www.reddit.com/r/gnome/

**Comment by kou** [comment]
Thanks. I'm not a reddit user. So I didn't care about it. There is no problem that we announce on reddit.

**Comment by kou** [comment]
I've released a new version.
All, could you announce it?

**Comment by cedlemo** [comment]
I am OK to make some annoucements but I really would like that we agree on the message I should use. For example the text in the *release.rd* file focus only on the gtk2 gem whereas the release here is for all the gems. Here is what I propose:

>  title: New version for the gems of the ruby-gnome2 project
>  
>  The gems of the ruby-gnome2 project are updated to the version 3.0.8. Those new versions brings:
>  *    better support for Gtk3
>  *   a complete tutorial for writting Gtk3 application with ruby
>  *   GLib::Regex support 
>  *   bug fixes
>  and more.
>  
>  = About the ruby-gnome2 project 
>  As a reminder, and for those that didn't know, the ruby-gnome2 project is a set of bindings for the GNOME 2.x and 3.x libraries to use from Ruby 2.0.0, 2.1 and 2.2. 
>  
>  The ruby-gnome2 project provides the following gems:
>  atk              cairo-gobject
>  clutter          clutter-gstreamer
>  clutter-gtk      gdk_pixbuf2 
>  gdk3             gio2
>  glib2            gobject-introspection
>  gstreamer        gtk2
>  gtk3             gtksourceview2
>  gtksourceview3   gvlc
>  pango            poppler
>  rsvg2            vte
>  vte3             webkit-gtk
>  webkit2-gtk      webkit-gtk2
>  
>  Since the version 3.0.0, the ruby-gnome2 gems are based on the gobject-instropection whenever it is possible. The platforms supported are Linux, windows and OSX.
>  
>  In order to install a gem (gtk3 for example) just do : 
>  
>      gem install gtk3
>  
>  = About GTK+
>  
> from http://www.gtk.org/
> 
>   GTK+ is a highly usable, feature rich toolkit for creating
>   graphical user interfaces which boasts cross platform
>   compatibility and an easy to use API. GTK+ it is written
>   in C, but has bindings to many other popular programming
>   languages such as C++, Python and C# among others. GTK+ is
>   licensed under the GNU LGPL 2.1 allowing development of
>   both free and proprietary software with GTK+ without any
>   license fees or royalties.
> 
> = About GNOME
> 
> from http://www.gnome.org/about/
> 
>   The GNOME project provides two things: The GNOME desktop
>   environment, an intuitive and attractive desktop for
>   users, and the GNOME development platform, an extensive
>   framework for building applications that integrate into
>   the rest of the desktop.

I can send an annoucement in (where I have already an account): 
https://www.ruby-forum.com/
https://www.reddit.com/r/ruby
https://www.reddit.com/r/gnome/
ruby-gnome2-devel-en@lists.sourceforge.net
http://www.gtkforums.com/
gtk-list@gnome.org (I can ask them before in order to see if it is ok to announce "non-officials" bindings update in their mailing list.)

**Comment by kou** [comment]
Thanks for the proposal. I'm OK with the following modifications:

  * ruby-gnome2 -> Ruby-GNOME2: See also http://ruby-gnome2.osdn.jp/hiki.cgi?Naming+and+Conversion+Rules
  * Gtk3 -> GTK+ 3
  * Ruby 2.0.0, 2.1 and 2.2 -> Ruby 2.1, 2.2 and 2.3 (We dropped 2.0.0 support)
  * windows -> Windows
  * OSX -> OS X

**Comment by kou** [comment]
> I can send an annoucement in (where I have already an account):

Thanks!!!

**Comment by cedlemo** [comment]
done for: 

https://www.ruby-forum.com/
https://www.reddit.com/r/ruby
https://www.reddit.com/r/gnome/
ruby-gnome2-devel-en@lists.sourceforge.net
http://www.gtkforums.com/
ruby-talk@ruby-lang.org

I hope this is enought @kou, I don't see where I could
make anoucement.

**Comment by kou** [comment]
Thanks! It's enough!
