### ISSUE TITLE
Builder doesn't set name to id

### ISSUE THREAD

**Issue by HCLarsen** [ruby-gnome2/ruby-gnome2#741]
According to the Gnome Reference Guides, the "id" from the ui file should become the widget's name property. This gem instead assigns the class name to the name property.

**Comment by kou** [comment]
Because `name` is conflicts with `gtk_widget_get_name()`. Use `builder_name` instead.

**Comment by kou** [comment]
If I misunderstood your comment, please add a comment with a code that shows your problem.

**Comment by HCLarsen** [comment]
I think you did misunderstand. Unless you're going to change the library, you can't use builder_name, because the CSS parser looks for the name property. Here's an example for you. Say I create a .ui file in Glade, which has a label in it like this:

`<object class="GtkLabel" id="label1">`

Then I should be able to style that object with a CSS file with this selector:

`#label1`

However, that doesn't work. When the builder parses the ui file, it should create a Gtk::Label object with a name attribute equal to "label1." However, instead it assigns the name attribute to "GtkLabel." Does that help explain the problem?

**Comment by cedlemo** [comment]
@kou : 

here is a simple ui interface done with glade (window + label) *builder_issue.ui*

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.19.0 -->
<interface>
  <requires lib="gtk+" version="3.16"/>
  <object class="GtkWindow" id="window1">
    <property name="can_focus">False</property>
    <child>
      <object class="GtkLabel" id="label1">
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <property name="label" translatable="yes">label</property>
      </object>
    </child>
  </object>
</interface>
```
Here is the code that illustrates what HCLarsen try to tell you:

```ruby
#!/usr/bin/env ruby

require "gtk3"

path = File.expand_path(File.dirname(__FILE__))
builder = Gtk::Builder.new(:file => "#{path}/builder_issue.ui")
window = builder.get_object("window1")
label = builder["label1"]
window.set_title "test"
window.set_default_size 100, 100
puts "window name #{window.name} class #{window.class}"
puts "label name #{label.name} class #{label.class}"
window.show_all
window.signal_connect "destroy" do  
  Gtk.main_quit
end
Gtk.main
```
The output:

```
window name GtkWindow class Gtk::Window
label name GtkLabel class Gtk::Label
```

**Comment by kou** [comment]
@cedlemo Thanks.

I think that `<property name="name">label1</property>` should be included in .ui:

```xml
<!-- ... -->
      <object class="GtkLabel" id="label1">
        <property name="name">label1</property>
        <!-- ... -->
```

Full .ui:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.18.3 -->
<interface>
  <requires lib="gtk+" version="3.16"/>
  <object class="GtkWindow" id="window1">
    <property name="can_focus">False</property>
    <child>
      <object class="GtkLabel" id="label1">
        <property name="name">label1</property>
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <property name="label" translatable="yes">label</property>
      </object>
    </child>
  </object>
</interface>
```

@HCLarsen 

> According to the Gnome Reference Guides, the "id" from the ui file should become the widget's name property.

Could you show URL?

**Comment by HCLarsen** [comment]
The URL is the one that cedlemo posted.

https://developer.gnome.org/gtk3/3.4/GtkCssProvider.html

I tested this by setting the name of my widget in my ruby code, after which time the styling in my CSS file did take effect.

**Comment by HCLarsen** [comment]
Here's some example code to illustrate:

The ui file:"
`<?xml version="1.0" encoding="UTF-8"?>

<interface>
  <requires lib="gtk+" version="3.12"/>
  <object class="GtkWindow" id="win">
    <property name="can_focus">False</property>
    <child>
      <object class="GtkBox" id="box1">
        <property name="can_focus">False</property>
        <property name="orientation">vertical</property>
        <child>
          <object class="GtkEventBox" id="eventbox1">
            <property name="can_focus">False</property>
            <child>
              <object class="GtkLabel" id="label1">
                <property name="can_focus">False</property>
                <property name="label" translatable="yes">True</property>
              </object>
            </child>
          </object>
        </child>
        <child>
          <object class="GtkEventBox" id="eventbox2">
            <property name="can_focus">False</property>
            <child>
              <object class="GtkLabel" id="label2">
                <property name="can_focus">False</property>
                <property name="label" translatable="yes">True</property>
              </object>
            </child>
          </object>
        </child>
      </object>
    </child>
  </object>
</interface>`

The CSS file:
`* {
  background-color: #000;
  color: #FFF;
  font-size: 42px;
}

#label1 {
  color: #F00;
}`

And the rb file:
`require "gtk3"

class Main
  def initialize
    ui_file = "#{File.expand_path(File.dirname(__FILE__))}/main2.ui"
    builder = Gtk::Builder.new
    builder.add_from_file(ui_file)

    provider = Gtk::CssProvider.new
    Dir.chdir(__dir__) do
      provider.load(:data => File.read("main.css"))
    end

    @win = builder.get_object("win")
    @box = builder.get_object("eventbox1")
    @label = builder.get_object("label1")

    apply_css(@win, provider)

    @win.signal_connect("destroy") { Gtk.main_quit }
    @win.show_all

    Gtk.main
  end

  def apply_css(widget, provider)
    widget.style_context.add_provider(provider, GLib::MAXUINT)
    if widget.is_a?(Gtk::Container)
      widget.each_all do |child|
        apply_css(child, provider)
      end
    end
  end
end

Main.new`

This code didn't apply the rule in my CSS file for #label1. When I added the line:

`@label.name = "label1"`

Before the line that applies the CSS rules, the text in the first label was formatted as red.

I hope this helps illustrate the issue.

**Comment by cedlemo** [comment]
I don't understand , I tested this and it works well:

```ruby
require "gtk3"

class Main
  def initialize
    ui_file = "#{File.expand_path(File.dirname(__FILE__))}/builder_issue_1.ui"
    builder = Gtk::Builder.new
    builder.add_from_file(ui_file)

    provider = Gtk::CssProvider.new
    Dir.chdir(__dir__) do
      provider.load(:data => File.read("builder_issue_1.css"))
    end

    @win = builder.get_object("win")
    @box = builder.get_object("eventbox1")
    @label = builder.get_object("label1")
    @label.name ="label1"
    apply_css(@win, provider)

    @win.signal_connect("destroy") { Gtk.main_quit }
    @win.show_all

    Gtk.main
  end

  def apply_css(widget, provider)
    widget.style_context.add_provider(provider, GLib::MAXUINT)
    if widget.is_a?(Gtk::Container)
      widget.each_all do |child|
        apply_css(child, provider)
      end
    end
  end
end

Main.new
```
The font color of the first label is red. When we set the name of the widget via the ui file or via the `#name=` method, the related selector  can be used in the Css.

**Comment by HCLarsen** [comment]
That's exactly my point @cedlemo. You shouldn't have to put the #name= method. That should be assigned automatically by the builder when it assigns that ui item to the object. Based on the Gnome Developer page, that code above should work without that line.

**Comment by kou** [comment]
> The URL is the one that cedlemo posted.
> 
> https://developer.gnome.org/gtk3/3.4/GtkCssProvider.html
> 
> I tested this by setting the name of my widget in my ruby code, after which time the styling in my CSS file did take effect.

Thanks.
Could you also show description that says 'the "id" from the ui file should become the widget's name property' in the page? I couldn't find it.

**Comment by HCLarsen** [comment]
Right here:

[Selectors work very similar to the way they do in CSS, with widget class names taking the role of element names, and widget names taking the role of IDs. When used in a selector, widget names must be prefixed with a '#' character. The '*' character represents the so-called universal selector, which matches any widget. ](https://developer.gnome.org/gtk3/3.4/GtkCssProvider.html)

It's right under the Selectors header.

**Comment by kou** [comment]
> Selectors work very similar to the way they do in CSS, with widget class names taking the role of element names, and widget names taking the role of IDs. When used in a selector, widget names must be prefixed with a '#' character. The '*' character represents the so-called universal selector, which matches any widget.

Thanks.
It says nothing about .ui file. So 'the "id" from the ui file should become the widget's name property' isn't true.

**Comment by HCLarsen** [comment]
It's rather obvious that they're talking about the ID in the ui file, because they're comparing it to CSS used in webpages where the # selector selects an element based on the ID in the HTML file. Don't you see how analogous this is?

**Comment by kou** [comment]
Could you confirm it at `gtk-list@gnome.org` mailing list not here?
http://www.gtk.org/mailing-lists.php
