### ISSUE TITLE
liststore gtk version 3.0.8 is very slow compared with gtk version 2.2.4

### ISSUE THREAD

**Issue by rafagf1** [ruby-gnome2/ruby-gnome2#749]
ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

ruby test_store.rb 2.2.4
Result: 0.04890669

ruby test_store.rb 3.0.8
Result: 8.145841804

[test.zip](https://github.com/ruby-gnome2/ruby-gnome2/files/216794/test.zip)

**Comment by cedlemo** [comment]
This is very interesting, I think that the difference come from the usage of gobject-introspection bindings or the usage of bindings done in a classical way (2.2.4) but a 200 ratio seems really important.

I have added some tests in your file:

```ruby
require 'gtk3'

b = Gtk::Builder.new(:file => "./test.glade")
s = b["liststoreTest"]

t1 = Time.now
5000.times do |n|
	iter = s.append
  iter[0] = "na1"
  iter[1] = "na2"
  iter[2] = "na3"
  iter[3] = "na4"
  iter[4] = "na5"
  iter[5] = "na6"
  iter[6] = "na7"
  iter[7] = "na8"
  iter[8] = "na9"
end	
puts Time.now-t1

t1 = Time.now
5000.times do |n|
	iter = s.append
  iter.set_values(["na1" ,"na2" ,"na3" ,"na4" ,"na5" ,"na6" ,"na7" ,"na8" ,"na9"])
end	
puts Time.now-t1

t1 = Time.now
5000.times do |n|
	iter = s.insert(n)
  iter.set_values(["na1" ,"na2" ,"na3" ,"na4" ,"na5" ,"na6" ,"na7" ,"na8" ,"na9"])
end	
puts Time.now - t1
```

The output : 

```
11.809733669
5.57446994
5.869688393
```

It looks like with the two last methods, you can reduce by 2 the elapsed time.

But we should take a reference : python and the bindings that use gobject-introspection:

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import time

builder = Gtk.Builder()
builder.add_from_file("test.glade")
s = builder.get_object("liststoreTest")

start_time = time.time()

for x in range(0, 5000):
    s.append(["na1" ,"na2" ,"na3" ,"na4" ,"na5" ,"na6" ,"na7" ,"na8" ,"na9"])

print(time.time() - start_time)
```
1.0157692432403564
So here we have a ratio of 5 between ruby and python in favor of python which is somehow important.


One question: is an insertion of 5000 entries a realistic usage of the ListStore ?

**Comment by rafagf1** [comment]
Yes, I have several listings with more than 2000 entries and many more columns than the example, and when I tried to migrate to gtk 3.0.8 is when I have seen the speed problem.

I didn't know  the "set_values" method of "Gtk::TreeIter" (in the documentation I haven't seen), although I have seen that documentation of "Gtk::ListStore"  does mention this method is undocumented, seems to be the same method but having a "Gtk::TreeIter" as the first parameter.

The "set_values" method is 2 to 3 times faster so I will use it, but still remains quite slower than version 2.2.4 of GTK and example you put in python.

**Comment by cedlemo** [comment]
> I didn't know the "set_values" method of "Gtk::TreeIter" (in the documentation I haven't seen)

I am  a recent contributor and I don't know everything about this project, I am not sure that the documentation is up to date. In general I look in the `gtk3/samples` or in the `gtk3/tests` when I don't remember something or when I don't know how to proceed.

> but still remains quite slower than version 2.2.4 of GTK and example you put in python.

I agree with you. This is something that must be said. Maybe @kou could answer to this.

**Comment by cedlemo** [comment]
While we wait for a better answer for @kou, I may have a solution that could optimize the code. In the Ruby-GNOME2 project, the idea is to provide a rubyish interface based on  C libs. So the code that you use is in fact some ruby code that encapsulate the "raw" ruby bindings. see this in the `gtk3/lib/gtk3/list-store.rb` file : 

```ruby
    alias_method :insert_raw, :insert
    def insert(index, values=nil)
      iter = insert_raw(index)
      setup_iter(iter)
      set_values(iter, values) if values
      iter
    end
```

So I have appended at the end of the script the more "raw" code you can use in order to insert data in the store : 

```ruby
require 'gtk3'

b = Gtk::Builder.new(:file => "./test.glade")
s = b["liststoreTest"]

t1 = Time.now
5000.times do |n|
	iter = s.append
  iter[0] = "na1"
  iter[1] = "na2"
  iter[2] = "na3"
  iter[3] = "na4"
  iter[4] = "na5"
  iter[5] = "na6"
  iter[6] = "na7"
  iter[7] = "na8"
  iter[8] = "na9"
end	
puts Time.now-t1

t1 = Time.now
5000.times do |n|
	iter = s.append
  iter.set_values(["na1" ,"na2" ,"na3" ,"na4" ,"na5" ,"na6" ,"na7" ,"na8" ,"na9"])
end	
puts Time.now-t1

t1 = Time.now
5000.times do |n|
	iter = s.insert(n)
  iter.set_values(["na1" ,"na2" ,"na3" ,"na4" ,"na5" ,"na6" ,"na7" ,"na8" ,"na9"])
end	
puts Time.now - t1

t1 = Time.now
5000.times do |n|
	iter = s.insert(n, ["na1" ,"na2" ,"na3" ,"na4" ,"na5" ,"na6" ,"na7" ,"na8" ,"na9"])
end	
puts Time.now - t1

t1 = Time.now
5000.times do |n|
	iter = s.insert_raw(n)
  _values = []
  columns = [0,1,2,3,4,5,6,7,8]
  type = s.get_column_type(0)
  ["na1" ,"na2" ,"na3" ,"na4" ,"na5" ,"na6" ,"na7" ,"na8" ,"na9"].each_with_index do |v, i|
    _values << GLib::Value.new(type, v)
  end
  s.set(iter, columns, _values)
end	
puts Time.now - t1
```

You can see that the code is less rubyish, there are more line but here are the times:

    12.888387362
    6.137056796
    6.374194922
    6.408112106
    2.581362645    <-- (1.0094106197357178 for python)

I don't know if we can do better.

**Comment by rafagf1** [comment]
I have seen that you have used directly the code of "TreeModel.set_values". The speed difference is remarkable because not have to check the data type for each iteration, I don't know if there is any way to optimize this query.

I modified your code if there are different types of data in our "liststore".

`t1 = Time.now
columns = [0,1,2,3,4,5,6,7,8]
types = [GLib::Type::INT,GLib::Type::STRING,GLib::Type::STRING,GLib::Type::STRING,GLib::Type::STRING,GLib::Type::STRING,GLib::Type::STRING,GLib::Type::STRING,GLib::Type::STRING]

5000.times do |n|
  iter = s.insert_raw(n)
  _values = []
  ["na1" ,"na2" ,"na3" ,"na4" ,"na5" ,"na6" ,"na7" ,"na8" ,"na9"].each_with_index do |v, i|
    _values << GLib::Value.new(types[i], v)
  end
  s.set(iter, columns, _values)
end 
puts Time.now - t1`

I think that inserting data could be optimized if "TreeModel.set_values" could consult directly the data type by the field position.

**Comment by cedlemo** [comment]
> I don't know if there is any way to optimize this query.

this one ? `s.get_column_type(0)` , it looks like it is the raw bindings, if I run this command :`find {gtk3,glib2} -type f | xargs grep -i column_type` in order to find some related code to `get_column_type` : 

```
  gtk3/lib/gtk3/tree-iter.rb:      gtype = @model.get_column_type(column)
  gtk3/lib/gtk3/tree-model.rb:          type = get_column_type(column_id)
  gtk3/lib/gtk3/tree-model.rb:          type = get_column_type(i)
  gtk3/lib/gtk3/tree-store.rb:    def initialize(*column_types)
  gtk3/lib/gtk3/tree-store.rb:      initialize_raw(column_types)
  gtk3/ext/gtk3/rb-gtk3-tree-model.c:        GType column_type =   gtk_tree_model_get_column_type(tree_model, i);
  gtk3/ext/gtk3/rb-gtk3-tree-model.c:        if (G_TYPE_FUNDAMENTAL(column_type) != G_TYPE_OBJECT)
```
>I think that inserting data could be optimized if "TreeModel.set_values" could consult directly the data type by the field position.

Like make a C bindings that check the type and that override the default bindings? Maybe it is possible. 
I am just a contributor, it is @kou who decide.

**Comment by rafagf1** [comment]
Something simple that works is this patch, but I don't know if it's the right.

```Diff
diff -Naur gtk3-3.0.8.new/lib/gtk3/tree-model.rb gtk3-3.0.8.ori/lib/gtk3/tree-model.rb
--- gtk3-3.0.8.new/lib/gtk3/tree-model.rb	2016-04-15 13:43:54.886842189 +0200
+++ gtk3-3.0.8.ori/lib/gtk3/tree-model.rb	2016-04-15 13:12:46.530875648 +0200
@@ -82,38 +82,27 @@
     end
 
     def set_values(iter, values)
-      set_col_types unless @col_types
-      set_n_columns unless @n_columns
+      columns = []
       _values = []
       if values.is_a?(Hash)
         values.each do |column_id, value|
-          _values << GLib::Value.new(@col_types[column_id], value)
+          type = get_column_type(column_id)
+          columns << column_id
+          _values << GLib::Value.new(type, value)
         end
       else
         values.each_with_index do |value, i|
-          _values << GLib::Value.new(@col_types[i], value)
+          type = get_column_type(i)
+          columns << i
+          _values << GLib::Value.new(type, value)
         end
       end
-      set(iter, @n_columns, _values)
+      set(iter, columns, _values)
     end
 
     private
     def setup_iter(iter)
       iter.model = self
     end
-
-    def set_col_types
-      @col_types = []
-      ncols = n_columns
-      (0..(ncols-1)).each{|n| @col_types[n] = get_column_type(n) }
-      @col_types
-    end
-
-    def set_n_columns
-      @n_columns = []
-      (0..(n_columns-1)).each{|n| @n_columns << n }
-      @n_columns
-    end
-
   end
 end

```

**Comment by kou** [comment]
I've implemented some optimizations at master.
Could you try master?

**Comment by cedlemo** [comment]
With the last script : 

```
1.465775064
0.428105645
0.439211803
0.445393754
0.392458528
```
lol faster than python !!!

**Comment by rafagf1** [comment]
With set_values() and stable 3.0.8:
8.609390774

With set_values() and master:
0.642688264

@kou great work, thanks.

**Comment by kou** [comment]
Thanks for confirming.
