### ISSUE TITLE
titlebar with wrong icon (windows10)

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#750]
the titlebar (windows 10) show strange icon for iconify/full-display
button.
![snap04_15_22_32_41](https://cloud.githubusercontent.com/assets/27629/14574886/80919a0a-035e-11e6-976f-1b98e44251a4.png)

**Comment by cedlemo** [comment]
I confirm, I have the same pb 
*  windows 10
*  ruby 2.3 64
*  gtk3 64
*  gtk3 gem 3.0.8 

The exec `gtk3-icon-browser.exe` shows normal icons.

**Comment by kou** [comment]
Thanks for your report.
It seems that gdk3 gem doesn't bundle symbolic images.
It'll be fixed in the next release.

**Comment by dbldub** [comment]
Hi @kou . Do you know when that will be?
Thanks.

**Comment by kou** [comment]
There is no plan for new release.
If someone help us, we'll be able to release a new version soon.

**Comment by dbldub** [comment]
As a temporary workaround, I was able to get the icons working by...
- Installing - https://msys2.github.io/
- Renaming Adwaita folder in ruby gem to something else for backup (C:\Ruby23-x64\lib\ruby\gems\2.3.0\gems\gdk3-3.0.8-x64-mingw32\vendor\local\share\icons\Adwaita.bak)
- Copying the Adwaita folder from msys location (C:\msys64\mingw32\share\icons\Adwaita\) to the ruby gem location (C:\Ruby23-x64\lib\ruby\gems\2.3.0\gems\gdk3-3.0.8-x64-mingw32\vendor\local\share\icons\Adwaita)
- Success

**Comment by kou** [comment]
3.0.9 includes the fix of this problem.
