### ISSUE TITLE
cairo scrarch (win10) on window resize

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#752]
Since gtk-3.0.8, I get often this error :

= = =
File: cairo-surface.c, Line 956

Expression: CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
= = =

I could not find in which exact situation this append.
In a map viewer (OSM tiles and smoth scrolling, so heavy cairo redraw) all work well, and in a simple
canvas test it scratch on a window resize ... ( gadget_clock.rb )

**Comment by kou** [comment]
It seems that it's a GC related problem.
If you can create a program that reproduce this problem, please share it us.

**Comment by glurp** [comment]
I got same scratch with sample/misc program : 

C:\Ruby22\lib\ruby\gems\2.2.0\gems\gtk3-3.0.8-x86-mingw32\sample\misc>**ruby drawing.rb**
Assertion failed!

Program: C:\Ruby22\bin\ruby.exe
File: cairo-surface.c, Line 956

Expression: CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by glurp** [comment]
Simplest version : scratch when signal connect on "draw" is declared.

= = =
require "gtk3"
surface = nil
myapp = Gtk::Application.new "org.gtk.example", :flags_none 

myapp.signal_connect "activate" do |app|
  win = Gtk::ApplicationWindow.new app

  drawing_area = Gtk::DrawingArea.new
  win.add drawing_area
  drawing_area.set_size_request 100, 100

  drawing_area.signal_connect "draw" do |_da, cr|
    false    
  end

  drawing_area.signal_connect "configure-event" do |da, _ev|
    surface.destroy if surface
    p 1
    surface = win.window.create_similar_surface(Cairo::CONTENT_COLOR,
                                                da.allocated_width,
                                                da.allocated_height)
    p 2
    true
  end

  win.show_all
end

myapp.run ARGV
= = = 
.....
2
1
1
2
1
2
1
2
1
2
1
Assertion failed!

Program: C:\Ruby22\bin\ruby.exe
File: cairo-surface.c, Line 956

Expression: CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by kou** [comment]
Thanks. I can reproduce the problem with the script that you provided.
But I couldn't solve the problem yet. Sorry.

**Comment by glurp** [comment]
ok with 3.0.9, so I close it.

**Comment by kou** [comment]
Wow! It's good news.
