### ISSUE TITLE
font_features demo update

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#756]
@kou,

I have a hard time updating the font_features demo. 

https://github.com/GNOME/gtk/blob/master/demos/gtk-demo/font_features.c

They introduced some Harbfbuzz code https://www.freedesktop.org/wiki/Software/HarfBuzz/.

I have looked in the Pango module but I didn't found anything related. I tried this following gem : 

https://github.com/jslabovitz/harfbuzz-gem
Unfortunaltely, I have not found anything usefull. Should I continue to try using this gem and contact the author in order to help me or is there any other solution?

Thanks.

**Comment by kou** [comment]
You don't need to work on the demo.
Because we don't provide HarfBuzz API to users.

**Comment by cedlemo** [comment]
Ok, I let the font_features demo unchanged.
