### ISSUE TITLE
pango_cairo_context_set_shape_renderer in rotated_text demo

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#759]
@kou I am working on the update of the rotated_text demo : 

https://github.com/GNOME/gtk/blob/master/demos/gtk-demo/rotated_text.c 
At this line : 
https://github.com/GNOME/gtk/blob/master/demos/gtk-demo/rotated_text.c#L213 

they use the function `pango_cairo_context_set_shape_renderer` in order to bind a callback to the context of the pango layout. I don't see how to do this , I have looked here pango/ext/pango/rbpangocairocontext.c but find nothing. 

Should it be implemented?
If yes can I work on it?

**Comment by kou** [comment]
> Should it be implemented?

Yes.

> If yes can I work on it?

Yes, please.

**Comment by cedlemo** [comment]
@kou,

It looks like I miss something (don't focus on the code or the printf statements thanks) : 

I have added this in the file *pango/ext/pango/rbpangocontext.c* 

```c
#ifdef HAVE_RB_CAIRO_H
static VALUE
rg_set_font_options(VALUE self, VALUE options)
{
    if (NIL_P(options))
        pango_cairo_context_set_font_options(_SELF(self), NULL);
    else
        pango_cairo_context_set_font_options(_SELF(self),
                                             RVAL2CRFONTOPTIONS(options));
    return self;
}

static VALUE
rg_font_options(VALUE self)
{
    const cairo_font_options_t *options;
    options = pango_cairo_context_get_font_options(_SELF(self));
    if (options)
        return CRFONTOPTIONS2RVAL(cairo_font_options_copy(options));
    else
        return Qnil;
}

static VALUE
rg_set_resolution(VALUE self, VALUE dpi)
{
    pango_cairo_context_set_resolution(_SELF(self), NUM2DBL(dpi));
    return self;
}

static VALUE
rg_resolution(VALUE self)
{
    return rb_float_new(pango_cairo_context_get_resolution(_SELF(self)));
}
// Part I added
static void
shape_renderer_callback (cairo_t *cr, PangoAttrShape *attr,
                         gboolean do_path, gpointer data)
{
  printf("ok 2\n");
  VALUE rb_cr, rb_attr, rb_do_path, rb_callback;
  rb_cr = CRCONTEXT2RVAL(cr);
  rb_attr = ATTR2RVAL((PangoAttribute *) attr);
  rb_do_path = CBOOL2RVAL(do_path);
  rb_callback = (VALUE) data;
  rb_funcall(rb_callback, id_call, 3, rb_cr, rb_attr, rb_do_path);
}

static VALUE
rg_set_shape_renderer(VALUE self)
{
    if(!rb_block_given_p())
    {
      printf("No block given\n");
      return self;
    }
    VALUE func = rb_block_proc();
    //G_RELATIVE(self, func); with or without doent change anything
    printf("ok\n");
    pango_cairo_context_set_shape_renderer(_SELF(self),
                                           (PangoCairoShapeRendererFunc) shape_renderer_callback,
                                           (gpointer) func,
                                           NULL);
    return self;
}
#endif
```
I have added the requirred code in `Init_pango_context`.

Here is the ruby code that I use to test the implementation (before doing something clean)

```ruby
require "gtk3"
HEART = "♥"
TEXT = "I ♥ GTK+"
win = Gtk::Window.new("Shape Renderer Callback")
win.signal_connect("destroy") { Gtk.main_quit }
win.set_default_size(200, 200)

label = Gtk::Label.new(TEXT)
label.angle = 45

layout = label.layout

layout.context.set_shape_renderer do |cr, attr, do_path|
  puts cr.class
  puts attr.class
  puts do_path.class
end
metrics = layout.context.get_metrics(layout.font_description)
ascent = metrics.ascent
logical_rect = Pango::Rectangle.new(0, -ascent, ascent, ascent)
ink_rect = logical_rect.dup

attrs = Pango::AttrList.new
attrs.insert(Pango::AttrShape.new(ink_rect, logical_rect, HEART))
layout.attributes = attrs

win.add(label)
win.show_all
Gtk.main
```

When I run this I the output is:

```
ok
```
This 'ok' come from the C function `rg_set_shape_renderer` but there is no 'ok2' from the `shape_renderer_callback` and the code of the callback is not executed.

In fact  the `shape_renderer_callback` is not executed at all. The ruby code I use for my test is based on the C demo rotated_text here https://github.com/GNOME/gtk/blob/master/demos/gtk-demo/rotated_text.c#L211.

**Comment by kou** [comment]
You should set `Pango::AttrList` to `Gtk::Label` not `Pango::Layout`:

```ruby
# layout.attributes = attrs
label.attributes = attrs
```

And you should set `start_index` and `end_index`:

```ruby
attr = Pango::AttrShape.new(ink_rect, logical_rect, HEART)
attr.start_index = TEXT[0, TEXT.index(HEART)].bytesize
attr.end_index = attr.start_index + HEART.bytesize
attrs.insert(attr)
```

I hope that this comment helps you. :-)

**Comment by cedlemo** [comment]
>I hope that this comment helps you. :-)

Yes it does !

What should I test in the test cases? the first thing that comes to me is something like:

```
layout.context.set_shape_renderer do |cr, attr, do_path|
  assert_instance_of(Cairo::Context, cr)
  ...
end
```
But I know you don't want me to use the `assert_instance_of` because of it meaningless

**Comment by kou** [comment]
It's difficult because I don't know about the behavior of `set_shape_renderer`.

Could you create a pull request that tests class of passed instance? I'll consider about test after the pull request is merged.

**Comment by cedlemo** [comment]
Ok course.
