### ISSUE TITLE
Bug in Gtk::Treeview#row_expanded not returning valid iter

### ISSUE THREAD

**Issue by Beagle123** [ruby-gnome2/ruby-gnome2#762]
Hi:

I don't know where to report these bugs.  Please let me know.

I found this bug when using Gtk::Treeview#row_expanded.  The method
doesn't return a valid iter.

```ruby
def self__row_expanded(view, iter, path)
 #iter = model.get_iter(path)
  VR::msg( iter[2] )
end
```

This causes this error:

```text
/home/eric/.rvm/gems/ruby-2.3.0/gems/gtk3-3.0.8/lib/gtk3/tree-iter.rb:28:in
`get_value': undefined method `get_value' for nil:NilClass
   from
/home/eric/vrp/vr3/visualruby_examples/filetreeview/bin/FileTreeView.rb:18:in
`self__row_expanded'
   from /home/eric/vrp/vrlib3/lib/GladeGUI.rb:163:in `call'
   from /home/eric/vrp/vrlib3/lib/GladeGUI.rb:163:in `block (2 levels)
in parse_signals'
   from
/home/eric/.rvm/gems/ruby-2.3.0/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb:551:in
`invoke'
   from
/home/eric/.rvm/gems/ruby-2.3.0/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb:551:in
`block in define_method'
   from
/home/eric/vrp/vr3/visualruby_examples/filetreeview/bin/FileTreeView.rb:51:in
`refresh'
```

If I uncomment the line where I reassign the iter variable using the
model#get_iter method, it works perfectly.

I'd like to work more closely with the people who work on Ruby/Gtk.
Please let me know who you are.

Thanks for all your great work!

Eric

**Comment by kou** [comment]
> I don't know where to report these bugs. Please let me know.

Here is correct.

> I found this bug when using Gtk::Treeview#row_expanded. The method
> doesn't return a valid iter.

Could you show a program that reproduces the problem? It should be run by our environment.

`Gtk::TreeView#row_expanded` doesn't use `iter`. So it seems that you may misunderstand.

**Comment by Beagle123** [comment]
Hi kou:
I'm referring to the Gtk::TreeView's row-expanded signal:

It passes the view, path and iter to the handler.  The iter is invalid.
Are you sure that the signal is passing the correct value?
When I oputut the class name it does come back as an iter object, but it fails when I do this:
puts iter[0].to_s etc.


Thanks,Eric

**Comment by kou** [comment]
I've fixed it.

I hope that you provide a runnable program that reproduces a problem at the next time.
