### ISSUE TITLE
How to access Pango::AttrShape data

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#766]
@kou, When I use the method `set_shape_renderer` I have access as argument of my block to a cairo context, a `Pango::AttrShape` and a boolean value.

How should I use the `Pango::AttrShape` in order to get the value / data that comes with it like in C:

   # GPOINTER_TO_UINT (attr->data)

```ruby
 layout.context.set_shape_renderer do |cr, attr, do_path|
    x, y = cr.current_point
    cr.translate(x, y)
    cr.scale(attr.ink_rect.width / Pango::SCALE,
             attr.ink_rect.height / Pango::SCALE)
    
   if attr.to_s == HEART # Don't work
      cr.move_to(0.5, 0)
      cr.line_to(0.9, -0.4)
      cr.curve_to(1.1, -0.8, 0.5, -0.9, 0.5, -0.5)
      cr.curve_to(0.5, -0.9, -0.1, -0.8, 0.1, -0.4)
      cr.close_path
    end

    unless do_path
      cr.set_source_rgb(1, 0, 0)
      cr.fill
    end
  end
end
```

**Comment by kou** [comment]
I've added `Pango::AttrShape#data`. Use it.

**Comment by cedlemo** [comment]
O_O That was so simple and I haven't think to make a PR with that.

Thanks.
