### ISSUE TITLE
rename some classes in GObjectIntrospection::Loader

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#770]
@kou,

I am working (trying to work) on the bindings of the GOffice library. I have some structure, object, interface that will be mapped to Ruby classes. There are some restrictions on the name to use for the classes so I needed to modify them for example:

*   3DRotationSel (can not be used) will become Rotation3DSel
*   cPolygon  will become CanvasPolygon

So in my loader I have created a rename_class method (see https://github.com/cedlemo/gsf_goffice_gnumeric/blob/master/goffice/loader.rb#L210)

```ruby
def self.rename_class(class_name)
      name = case class_name
      when /\A3DRotationSel\z/
        "Rotation3DSel"
      when /\Ac(\d*[A-Z]\w*)\z/
        "Canvas#{Object::Regexp.last_match[0]}"
      when /\Ag(\d*[A-Z]\w*)\z/
        "Graph#{Object::Regexp.last_match[0]}"
      when /\Ago_regression_stat_t\z/
        "RegressionStatT"
      when /\Ago_regression_stat_tl\z/
        "RegressionStatTl"
      else
        class_name
      end
    end
```
And I have to use it in different places (this was some sequences of try/fails) in Loader:

*   load_object_info
*   load_enum_info
*   load_struct_info
*   define_struct
*   load_flags_info
*   load_interface_info

Is there a better way to do this.

FYI I just begin https://github.com/cedlemo/gsf_goffice_gnumeric and try to implement a GOffice demo.

Do you think that they could be added to the ruby-GNOME2 project. (Not as they are now, my github repo is just for tests.)

**Comment by kou** [comment]
It seems that we need to provide `GI::Loader.rubyish_class_name` API like `GI::Loader#rubyisth_method_name`.

> Do you think that they could be added to the ruby-GNOME2 project. (Not as they are now, my github repo is just for tests.)

Sure.

**Comment by cedlemo** [comment]
> It seems that we need to provide GI::Loader.rubyish_class_name API 

something like this in the loader.rb file of gobject-introspection.:

```ruby
def rubyish_class_name(name)
   name # I assume that by default we don't need to modify the name
end
```
then I use it in those methods :  

*  load_object_info
*  load_enum_info
*  load_struct_info
*  define_struct
*  load_flags_info
*  load_interface_info
(is there any other ? )


After that I will just have to add the rules I need in the `rubyish_class_name` of the goffice/loader.rb.
Are you OK with this?

**Comment by kou** [comment]
> Are you OK with this?

Yes!

Here are steps to implement it:

  1. We merge libgsf, GOffice and Gnumeric bindings
  2. Loop the followings
      1. Add `rubyish_class_name` feature to `GI::Loader#load_XXX`
      2. Use it in libgsf, GOffice and Gnumeric bindings

**Comment by cedlemo** [comment]
@kou this is done so I will start  the gobject-introspection implementation of gdk_pixbuf2 #773  if you agree.

**Comment by kou** [comment]
I agree with it!
