### ISSUE TITLE
Implement Gdk::Pixbuf.new(:resource => path)

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#773]
@kou, 
I create an issue in order to set it as an active task, not forget it. #771

Furthermore, I have one little question: When I look at the code I have to modify / extend : 
https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gdk_pixbuf2/ext/gdk_pixbuf2/rbgdk-pixbuf.c#L98

I feel like (maybe) we should try to simplify? 
*   should we assure support for old options (can we drop some ?)
*   should we factorize ?

Because if you look here, https://developer.gnome.org/gdk-pixbuf/2.33/gdk-pixbuf-File-Loading.html, there are other functions that are not implemented. 

do you know about clang-format, it is a tools that "format" your C/C++ code (no lines with more 80 c, no new lines after bracket of if ... ). Do you think it could be a good tool to fix style issues in C files like this one for example.

**Comment by kou** [comment]
> I feel like (maybe) we should try to simplify? 

Yes if we can do. But it seems that this case is difficult because there are many patterns to be supported.

> * should we assure support for old options (can we drop some ?)

Normally, we keep backward compatibility. We drop backward compatibility when bound library drops the feature. Or we drop old bound library.

If there are some options that matches the above situation, we can drop them.

> * should we factorize ?

I'm sorry but I couldn't imagine what you imagine. Could you show sample codes?

> do you know about clang-format, it is a tools that "format" your C/C++ code (no lines with more 80 c, no new lines after bracket of if ... ). Do you think it could be a good tool to fix style issues in C files like this one for example.

I don't know about clang-format. It may be a good tool for us. (It may be better that we drop the C code and migrate to GObject Introspection based bindings.)

**Comment by cedlemo** [comment]
> It may be better that we drop the C code and migrate to GObject Introspection based bindings

Maybe we should work on this instead?

**Comment by kou** [comment]
> > It may be better that we drop the C code and migrate to GObject Introspection based bindings
> 
> Maybe we should work on this instead?

If there are many(? 10 or more?) unbound features, we should choose GObject Introspection based bindings. Do you know there are how many unbound features?

**Comment by cedlemo** [comment]
> Do you know there are how many unbound features?
Sorry @kou, I don't really understand what you ask On my system I have those gir files:
 
*    /usr/share/gir-1.0/Gdk-2.0.gir
*    /usr/share/gir-1.0/Gdk-3.0.gir
*    /usr/share/gir-1.0/GdkPixbuf-2.0.gir
*    /usr/share/gir-1.0/GdkX11-2.0.gir
*    /usr/share/gir-1.0/GdkX11-3.0.gir

Now if you question is does those gir file cover all the Gdk code? then, I can not answer you.

I can (maybe) do a comparaison of functions in those files (it is xml) and those in the gdk header files (I have a libclangc ruby binding) if you want.

**Comment by kou** [comment]
Ah, sorry for my less description.

I hope that the following description is enough:

gdk_pixbuf2 gem provides many bindings. It covered all features in old gdk-pixbuf. But gdk-pixbuf is improved. Some new gdk-pixbuf features aren't bound by gdk_pixbuf2 gem. For example, `gdk_pixbuf_new_from_resource()` isn't bound. If there are many unbound features, we should migrate gdk_pixbuf2 gem to GObject Introspection based bindings rather than implementing unbound features by writing new C codes.

I want to know how many unbound features of new gdk-pixbuf exist. If there are 10 or more unbound features, we should migrate to GObject Introspection based bindings.

**Comment by cedlemo** [comment]
OK I will check this.

**Comment by cedlemo** [comment]
So I checked the functions wrapped in the `Gdk::Pixbuf` C code and I have compared it with the C functions of my GdkPixbuf headers. (https://gist.github.com/cedlemo/6cc19fcc3212356b7f2c1227b3758361 )

```
Currently wrapped functions number : 71
Gdk Pixbuf functions 92 in Headers
Gdk Pixbufs functions done
	gdk_pixbuf_get_n_channels
	gdk_pixbuf_get_bits_per_sample
	gdk_pixbuf_get_pixels
	gdk_pixbuf_get_width
	gdk_pixbuf_get_height
	gdk_pixbuf_get_rowstride
	gdk_pixbuf_new
	gdk_pixbuf_copy
	gdk_pixbuf_new_subpixbuf
	gdk_pixbuf_new_from_file
	gdk_pixbuf_new_from_file_at_size
	gdk_pixbuf_new_from_file_at_scale
	gdk_pixbuf_new_from_data
	gdk_pixbuf_new_from_xpm_data
	gdk_pixbuf_fill
	gdk_pixbuf_savev
	gdk_pixbuf_save_to_callbackv
	gdk_pixbuf_save_to_bufferv
	gdk_pixbuf_add_alpha
	gdk_pixbuf_copy_area
	gdk_pixbuf_saturate_and_pixelate
	gdk_pixbuf_get_option
	gdk_pixbuf_scale
	gdk_pixbuf_composite
	gdk_pixbuf_composite_color
	gdk_pixbuf_scale_simple
	gdk_pixbuf_composite_color_simple
	gdk_pixbuf_rotate_simple
	gdk_pixbuf_flip
	gdk_pixbuf_animation_new_from_file
	gdk_pixbuf_animation_get_width
	gdk_pixbuf_animation_get_height
	gdk_pixbuf_animation_is_static_image
	gdk_pixbuf_animation_get_static_image
	gdk_pixbuf_animation_get_iter
	gdk_pixbuf_animation_iter_get_delay_time
	gdk_pixbuf_animation_iter_get_pixbuf
	gdk_pixbuf_animation_iter_on_currently_loading_frame
	gdk_pixbuf_animation_iter_advance
	gdk_pixbuf_simple_anim_new
	gdk_pixbuf_simple_anim_add_frame
	gdk_pixbuf_get_formats
	gdk_pixbuf_format_get_name
	gdk_pixbuf_format_get_description
	gdk_pixbuf_format_get_mime_types
	gdk_pixbuf_format_get_extensions
	gdk_pixbuf_format_is_writable
	gdk_pixbuf_format_is_scalable
	gdk_pixbuf_format_is_disabled
	gdk_pixbuf_format_set_disabled
	gdk_pixbuf_format_get_license
	gdk_pixbuf_get_file_info
	gdk_pixbuf_loader_new
	gdk_pixbuf_loader_new_with_type
	gdk_pixbuf_loader_new_with_mime_type
	gdk_pixbuf_loader_set_size
	gdk_pixbuf_loader_write
	gdk_pixbuf_loader_get_pixbuf
	gdk_pixbuf_loader_get_animation
	gdk_pixbuf_loader_close
	gdk_pixbuf_loader_get_format
Gdk functions that remain to be wrapped
	gdk_pixbuf_error_quark
	gdk_pixbuf_get_colorspace
	gdk_pixbuf_get_has_alpha
	gdk_pixbuf_get_byte_length
	gdk_pixbuf_get_pixels_with_length
	gdk_pixbuf_read_pixels
	gdk_pixbuf_read_pixel_bytes
	gdk_pixbuf_new_from_resource
	gdk_pixbuf_new_from_resource_at_scale
	gdk_pixbuf_new_from_bytes
	gdk_pixbuf_new_from_stream
	gdk_pixbuf_new_from_stream_async
	gdk_pixbuf_new_from_stream_finish
	gdk_pixbuf_new_from_stream_at_scale
	gdk_pixbuf_new_from_stream_at_scale_async
	gdk_pixbuf_save_to_stream
	gdk_pixbuf_save_to_stream_async
	gdk_pixbuf_save_to_stream_finish
	gdk_pixbuf_apply_embedded_orientation
	gdk_pixbuf_get_options
	gdk_pixbuf_animation_new_from_stream
	gdk_pixbuf_animation_new_from_stream_async
	gdk_pixbuf_animation_new_from_stream_finish
	gdk_pixbuf_animation_new_from_resource
	gdk_pixbuf_simple_anim_set_loop
	gdk_pixbuf_simple_anim_get_loop
	gdk_pixbuf_get_file_info_async
	gdk_pixbuf_get_file_info_finish
	gdk_pixbuf_format_copy
	gdk_pixbuf_format_free
	gdk_pixbuf_loader_write_bytes
```

**Comment by kou** [comment]
Thanks!
We should migrate gdk_pixbuf2 gem to GObject Introspection based bindings.

**Comment by cedlemo** [comment]
How should we proceed?

**Comment by kou** [comment]
Here are instructions:

1. Move `gdk_pixbuf2` to `gdk_pixbuf2-no-gi`.
2. Create GObject Introspection bindings as `gdk_pixbuf2` like `gsf` and `goffice`.
3. Make `gdk_pixbuf2/sample/*.rb` workable with the GObject Introspection bindings.
4. Support `Gdk::Pixbuf.new(:resource => path)`.

**Comment by cedlemo** [comment]
@kou ,

I am working on the GobjectIntrospection for GdkPixbuf but when I try to make some basic tests, it did'nt work. I have followed the steps like for gsf, goffice and gnumeric. and created the files and directories required:

```
├── COPYING.LIB
├── lib
│   ├── gdk_pixbuf2
│   │   ├── gdk_pixbuf.rb
│   │   └── loader.rb
│   └── gdk_pixbuf2.rb
├── Rakefile
├── README.md
├── sample
└── test
    ├── fixture
    │   └── gnome-logo-icon.png
    ├── gdk_pixbuf2-test-utils.rb
    ├── run-test.rb
    └── test-gdk_pixbuf.rb
```

Here are the gdk_pixbuf2.rb : 

```ruby
require "gobject-introspection"
require "gio2"

base_dir = Pathname.new(__FILE__).dirname.dirname.expand_path
vendor_dir = base_dir + "vendor" + "local"
vendor_bin_dir = vendor_dir + "bin"
GLib.prepend_dll_path(vendor_bin_dir)
vendor_girepository_dir = vendor_dir + "lib" + "girepository-1.0"
GObjectIntrospection.prepend_typelib_path(vendor_girepository_dir)

require "gdk_pixbuf2/loader"

module Gdk
  class Pixbuf
    LOG_DOMAIN = "GdkPixbuf"
    GLib::Log.set_log_domain(LOG_DOMAIN)

    class << self
      def const_missing(name)
        init
        if const_defined?(name)
          const_get(name)
        else
          super
        end
      end

      def init
        class << self
          remove_method(:init)
          remove_method(:const_missing)
        end
        Gio.init if Gio.respond_to?(:init)
        loader = Loader.new(self)
        loader.load(LOG_DOMAIN)
      end
    end
  end
end
```
and the loader.rb file : 

```ruby
module Gdk
  class Pixbuf
    class Loader < GObjectIntrospection::Loader
      private
      def load_function_info(info)
        name = info.name
        case name
        when "init"
          # ignore
        else
          super
        end
      end

      def pre_load(repository, namespace)
      end

      def post_load(repository, namespace)
        require_libraries
      end

      def require_libraries
        require "gdk_pixbuf2/gdk_pixbuf"
      end

      def initialize_post(object)
        super
        return unless object.is_a?(GLib::Object)
        self.class.reference_gobject(object, :sink => true)
      end
    end
  end
end
```

What is wrong with this?

**Comment by cedlemo** [comment]
@kou , it seems that was I proposed : 
 > Is it not better suited to create a GdkPixbuf module, fill it with the loader and then include it in gdk?

works fine.

```ruby
require "gobject-introspection"
require "gio2"

base_dir = Pathname.new(__FILE__).dirname.dirname.expand_path
vendor_dir = base_dir + "vendor" + "local"
vendor_bin_dir = vendor_dir + "bin"
GLib.prepend_dll_path(vendor_bin_dir)
vendor_girepository_dir = vendor_dir + "lib" + "girepository-1.0"
GObjectIntrospection.prepend_typelib_path(vendor_girepository_dir)

require "gdk_pixbuf2/loader"

module GdkPixbuf
    LOG_DOMAIN = "GdkPixbuf"
    GLib::Log.set_log_domain(LOG_DOMAIN)

    class << self
      def const_missing(name)
        init
        if const_defined?(name)
          const_get(name)
        else
          super
        end
      end

      def init
        class << self
          remove_method(:init)
          remove_method(:const_missing)
        end
        Gio.init if Gio.respond_to?(:init)
        loader = Loader.new(self)
        loader.load(LOG_DOMAIN)
      end
    end
end
```

**Comment by cedlemo** [comment]
Done
