### ISSUE TITLE
goo canvas ruby gem compile error: use of undeclared identifier 'G_WIN32_OS_ANY'

### ISSUE THREAD

**Issue by JohnGillanders** [ruby-gnome2/ruby-gnome2#779]
Hi,

Great work on ruby-gnome2, thank you.

I am trying to compile the ruby gem for goocanvas in Mac OS X Yosemite (10.10.5) after installing gtk and goocanvas via MacPorts, but I get the compile error: use of undeclared identifier 'G_WIN32_OS_ANY'
It seems to be the same problem as in issue 361 (https://github.com/ruby-gnome2/ruby-gnome2/issues/361), but affecting goocanvas rather than glib2 (I can install the glib2 ruby gem no problem.
I have tried with gem1.9 and gem2.3, and get the same result.

Morpheus:~ jgillanders$ sudo /opt/local/bin/gem2.3 install glib2
Building native extensions.  This could take a while...
Successfully installed glib2-3.0.7
Parsing documentation for glib2-3.0.7
Done installing documentation for glib2 after 2 seconds
1 gem installed

Morpheus:~ jgillanders$ sudo /opt/local/bin/gem2.3 install goocanvas
Building native extensions.  This could take a while...
ERROR:  Error installing goocanvas:
	ERROR: Failed to build gem native extension.

    current directory: /opt/local/lib/ruby2.3/gems/2.3.0/gems/glib2-2.2.0/ext/glib2
/opt/local/bin/ruby2.3 -r ./siteconf20160525-52435-xtzsit.rb extconf.rb
checking for -Wall option to compiler... yes
checking for -Waggregate-return option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wswitch-default option to compiler... yes
checking for -Wswitch-enum option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wunsafe-loop-optimizations option to compiler... yes
checking for -Wwrite-strings option to compiler... yes
checking for rb_define_alloc_func() in ruby.h... yes
checking for rb_block_proc() in ruby.h... yes
checking for new allocation framework... yes
checking for attribute assignment... no
checking for Win32 OS... no
checking for gobject-2.0 version (>= 2.12.0)... yes
checking for gthread-2.0... yes
checking for unistd.h... yes
checking for io.h... no
checking for g_spawn_close_pid() in glib.h... yes
checking for g_thread_init() in glib.h... yes
checking for g_main_depth() in glib.h... yes
checking for g_listenv() in glib.h... yes
checking for rb_check_array_type() in ruby.h... yes
checking for rb_check_hash_type() in ruby.h... yes
checking for rb_exec_recursive() in ruby.h... yes
checking for rb_errinfo() in ruby.h... yes
checking for rb_sourcefile() in ruby.h... yes
checking for rb_sourceline() in ruby.h... yes
checking for ruby_set_current_source() in ruby.h... no
checking for rb_thread_blocking_region() in ruby.h... no
checking for ruby_native_thread_p() in ruby.h... yes
checking for rb_thread_call_with_gvl() in ruby.h... yes
checking for rb_str_new_cstr() in ruby.h... yes
checking for rb_gc_register_mark_object() in ruby.h... yes
checking for rb_exc_new_str() in ruby.h... yes
checking for curr_thread in ruby.h,node.h... no
checking for rb_curr_thread in ruby.h,node.h... no
creating ruby-glib2.pc
creating glib-enum-types.c
creating glib-enum-types.h
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/local/lib/ruby2.3/gems/2.3.0/extensions/x86_64-darwin-14/2.3.0/glib2-2.2.0/mkmf.log

current directory: /opt/local/lib/ruby2.3/gems/2.3.0/gems/glib2-2.2.0/ext/glib2
make "DESTDIR=" clean

current directory: /opt/local/lib/ruby2.3/gems/2.3.0/gems/glib2-2.2.0/ext/glib2
make "DESTDIR="
compiling glib-enum-types.c
warning: unknown warning option '-Wunsafe-loop-optimizations'; did you mean '-Wunavailable-declarations'? [-Wunknown-warning-option]
glib-enum-types.c:1187:9: error: use of undeclared identifier 'G_WIN32_OS_ANY'
      { G_WIN32_OS_ANY, "G_WIN32_OS_ANY", "any" },
        ^
glib-enum-types.c:1188:9: error: use of undeclared identifier 'G_WIN32_OS_WORKSTATION'
      { G_WIN32_OS_WORKSTATION, "G_WIN32_OS_WORKSTATION", "workstation" },
        ^
glib-enum-types.c:1189:9: error: use of undeclared identifier 'G_WIN32_OS_SERVER'
      { G_WIN32_OS_SERVER, "G_WIN32_OS_SERVER", "server" },
        ^
1 warning and 3 errors generated.
make: *** [glib-enum-types.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/local/lib/ruby2.3/gems/2.3.0/gems/glib2-2.2.0 for inspection.
Results logged to /opt/local/lib/ruby2.3/gems/2.3.0/extensions/x86_64-darwin-14/2.3.0/glib2-2.2.0/gem_make.out

Thanks in advance for your help!
John

**Comment by kou** [comment]
We dropped goocanvas support. Sorry.
Check clutter-gtk instead.

**Comment by JohnGillanders** [comment]
Okay, thanks. Guess I should have checked the main website before posting, sorry.
