### ISSUE TITLE
Bugs with Gtk::TreeIter

### ISSUE THREAD

**Issue by Beagle123** [ruby-gnome2/ruby-gnome2#786]
Hi:

I'm getting major bugs when using TreeViews and ListViews.  The problems occur when I set-up a listview, and fill the model with my subclasses.

When the column's set_cell_data_func runs, it goes haywire.  It works fine about 50% of the time, but often it crashes with segfaults and untracable errors.  The only errors I can track down emerge from the set_cell_data_func method when I try to set the values of the iter.

You can easily reproduce there errors like so:

from your home directory type:

git clone git@github.com:Beagle123/visualruby.git visualruby

cd visualruby

gem install require_all

gem install gtksourceview3

ruby vr

Go to "Open Project" 

open the "listview" project.

Press the "Run button"

You should get a bunch of random errors especially if you play with the program.

Please help. 

Thanks for your great work,
Eric

**Comment by Beagle123** [comment]
from /home/eric/.rvm/gems/ruby-2.3.0/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb:551:in `block in define_method'
	 from /home/eric/.rvm/gems/ruby-2.3.0/gems/gtk3-3.0.8/lib/gtk3/tree-model.rb:59:in `get_value'
	 from /home/eric/.rvm/gems/ruby-2.3.0/gems/gtk3-3.0.8/lib/gtk3/tree-iter.rb:28:in `get_value'
	 from /home/eric/vrp/vr3/vrlib/lib/treeview/IterMethods.rb:21:in `[]'
	 from /home/eric/vrp/vr3/examples/listview/bin/SongListViewGUI.rb:13:in `self__row_activated'
	 from /home/eric/vrp/vr3/vrlib/lib/GladeGUI.rb:165:in `call'

**Comment by cedlemo** [comment]
@Beagle123 ,
could you provide a simple example that reproduce/illustrate your problem?

**Comment by Beagle123** [comment]
Were you able to reproduce it?

I can try to make another example with basic gtk code, but I think the simple example will work.  I'll try.

Eric

**Comment by Beagle123** [comment]
This turned out to be a virus on my computer.  I reinstalled ubuntu, and everything works perfectly.
