### ISSUE TITLE
Window.add_events(:key_press) not working.

### ISSUE THREAD

**Issue by Beagle123** [ruby-gnome2/ruby-gnome2#806]
Hi:

This code is from the example on key_press events:

window = Gtk::Window.new
window.add_events(Gdk::Event::KEY_PRESS)

It doesn't work with gtk3.  It gives error saying to use :key_press symbol as mask.

However, this doesn't work either:

window = Gtk::Window.new
window.add_events(:key_press)

Thanks for all your great work.  I've really been working on visualruby to git it out:

http://visualruby.net

Best,
Eric

**Comment by kou** [comment]
> This code is from the example on key_press events:

Could you show the example?

Try the following:

```ruby
window.add_events(:key_press_mask)
```

By the way, `Gtk::Window` handles key press event by default.

**Comment by Beagle123** [comment]
Sorry to bother you.  It was my bad.
was doing this:
def self__key_press_event
WHen I should have had this:
def window1__key_press_event
Thanks for getting back to me.
Best,Eric
