### ISSUE TITLE
support of g_object_bind_property_full

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#843]
@kou,

I am working on the spinbutton demo and it seems that the `g_object_bind_property_full` is not supported what is the alternative?

*   https://github.com/GNOME/gtk/blob/master/demos/gtk-demo/spinbutton.c#L211
*   https://developer.gnome.org/gobject/unstable/GBinding.html#g-object-bind-property-full

**Comment by kou** [comment]
We need to extend `rg_bind_property()` in glib2/ext/glib2/rbgobj_object.c` to accept `:transform_to` and `:transform_from` keywords.

By the way, I (須藤功平) gave you "Continuous development award" in Tokyo RubyKaigi 11: http://regional.rubykaigi.org/tokyo11/tokyorubykaigi11_speakers_award.pdf
In Tokyo RubyKaigi 11, each speaker created a new award and chose winner. I created " Continuous development award" and chose you as winner. :-)

**Comment by cedlemo** [comment]
> We need to extend rg_bind_property() in glib2/ext/glib2/rbgobj_object.cto accept:transform_toand:transform_from` keywords.

I could work on it if you want.

>  I created " Continuous development award" and chose you as winner. :-)

Thanks a lot @Kou. I like the Ruby-GNOME2 project and contributing to it, make me learn and progress.

**Comment by kou** [comment]
> I could work on it if you want.

Thanks. Could you work on it?

**Comment by cedlemo** [comment]
@kou, before doing anything it would help me if we could agree on the interface we want and how to keep backward compatibility.

*   the current usage is `awidget#bind_property("src_prop", target, "target_prop", flags )`
and the extended usage should be : 
```ruby
awidget.bind_property("src_prop", target, "target_prop",
                flags, :transform_to => aproc, :transform_from => anotherproc )
```
and both should work. Is it what you expect?

**Comment by kou** [comment]
Yes!
