### ISSUE TITLE
Gdk::Pixbuf.new: "ArgumentError: string contains null byte"

### ISSUE THREAD

**Issue by gdelugre** [ruby-gnome2/ruby-gnome2#847]
Hello,

When ``Gdk::Pixbuf.new`` is called with 7 arguments, its first argument is supposed to be the image data represented as a ``String``.

However the code converts it as a C string and it fails with an exception if the pixels contain a null byte:

```ruby
irb(main):001:0> require 'gtk2'
=> true
irb(main):002:0> include Gtk
=> Object
irb(main):003:0> Gdk::Pixbuf.new "ab\x00cd".b, Gdk::Pixbuf::ColorSpace::RGB, false, 8, 1, 1, 1
ArgumentError: string contains null byte
	from (irb):3:in `initialize'
	from (irb):3:in `new'
	from (irb):3
	from /usr/bin/irb:11:in `<main>'
```

As most pictures contain pixels with null bytes, this is quite problematic. I am also interested if there exists another way to load a ``Pixbuf`` from a memory string without using a file.

This has been tested with ``gdk_pixbuf2`` 3.0.8 on Ruby MRI 2.3.1.

**Comment by cedlemo** [comment]
Hi,
it works with the new implementation of GdkPixbuf (I use the git gems):

```ruby
Gdk::Pixbuf.new(:data => "ab\x00cd".b,
                           :colorspace => :rgb,
                           :has_alpha => false, 
                           :bits_per_sample => 8,
                           :width => 1, :height => 1,
                           :row_stride => 1)
=> #<GdkPixbuf::Pixbuf:0x3050368 ptr=0x21d6980>
```

Could you try them ?

**Comment by bogdanRada** [comment]
i am having same issue. Tried that, but it gives me same error.

**Comment by kou** [comment]
3.0.9 includes the fix of this.
