### ISSUE TITLE
gdk_pixbuf2 3.0.9 lacks dependency

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome2/ruby-gnome2#862]
gdk_pixbuf2 3.0.9 must have dependency for gobject-introspection and gio2, otherwise for example test suite for rsvg2 fails like:

https://kojipkgs.fedoraproject.org//work/tasks/6562/15266562/build.log

**Comment by kou** [comment]
Oh...
Thanks for your report. I've fixed it.

**Comment by tsutsui** [comment]
It looks "gobject-introspection" is also required as runtime dependency.

**Comment by kou** [comment]
It's already required through gio2.

**Comment by tsutsui** [comment]
Ah, I missed it. Thanks.
