### ISSUE TITLE
 Typelib file for namespace 'WebKit'

### ISSUE THREAD

**Issue by sphynx79** [ruby-gnome2/ruby-gnome2#887]
I try to use webkit-gtk-3.0.9 but when i start sample file brower.rb, i receive this error:

C:/Users/en27553/Desktop/prova/.rblcl/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:37:in `require': Typelib file for namespace 'WebKit' (any version) not found (GLib::Error)
        from C:/Users/en27553/Desktop/prova/.rblcl/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:37:in `load'
        from C:/Users/en27553/Desktop/prova/.rblcl/lib/ruby/gems/2.3.0/gems/webkit-gtk-3.0.8/lib/webkit-gtk.rb:43:in `init'
        from C:/Users/en27553/Desktop/prova/.rblcl/lib/ruby/gems/2.3.0/gems/webkit-gtk-3.0.8/lib/webkit-gtk.rb:28:in `const_missing'
        from brower.rb:25:in `<main>'

I try also version 3.0.8 and same problem, and same problem also with webkit2-gtk 3.0.9

I use windows 7 64 bit and ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

Thanks

**Comment by kou** [comment]
Because [WebKitGTK+](https://webkitgtk.org/) doesn't support Windows yet. Could you send a Windows support request to WebKitGTK+ project?

**Comment by sphynx79** [comment]
But i install mingw-w64-x86_64-webkitgtk3 in my windows with mingw64.
If i can not use webkit how i can render local html file in one window?
Thanks

**Comment by sphynx79** [comment]
i try to install also ruby in mingw64 version ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32] and webkit-gtk work fine.

**Comment by kou** [comment]
> But i install mingw-w64-x86_64-webkitgtk3 in my windows with mingw64.

You mean this?

https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/mingw-w64-x86_64-webkitgtk3-2.4.11-1-any.pkg.tar.xz/download

I hope that you don't omit information...

The WebKitGTK+ is old (2.4.11). The latest WebKitGTK+ is 2.12.3 (stable) or 2.13.4 (unstable).

2.13.4 uses `F_GETFD` in [Source/WTF/wtf/UniStdExtras.cpp](https://trac.webkit.org/browser/releases/WebKitGTK/webkit-2.13.4/Source/WTF/wtf/UniStdExtras.cpp#L37). `F_GETFD` doesn't exist on Windows.

Here are build error by this:

```text
[  1%] Building CXX object Source/WTF/wtf/CMakeFiles/WTF.dir/UniStdExtras.cpp.obj
/home/vagrant/ruby-gnome2.win64/webkit2-gtk/tmp/windows/webkitgtk/webkitgtk-2.13.4/Source/WTF/wtf/UniStdExtras.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
/home/vagrant/ruby-gnome2.win64/webkit2-gtk/tmp/windows/webkitgtk/webkitgtk-2.13.4/Source/WTF/wtf/UniStdExtras.cpp: In function 'bool WTF::setCloseOnExec(int)':
/home/vagrant/ruby-gnome2.win64/webkit2-gtk/tmp/windows/webkitgtk/webkitgtk-2.13.4/Source/WTF/wtf/UniStdExtras.cpp:37:43: error: 'F_GETFD' was not declared in this scope
         int flags = fcntl(fileDescriptor, F_GETFD);
                                           ^
/home/vagrant/ruby-gnome2.win64/webkit2-gtk/tmp/windows/webkitgtk/webkitgtk-2.13.4/Source/WTF/wtf/UniStdExtras.cpp:37:50: error: 'fcntl' was not declared in this scope
         int flags = fcntl(fileDescriptor, F_GETFD);
                                                  ^
/home/vagrant/ruby-gnome2.win64/webkit2-gtk/tmp/windows/webkitgtk/webkitgtk-2.13.4/Source/WTF/wtf/UniStdExtras.cpp:39:49: error: 'F_SETFD' was not declared in this scope
             returnValue = fcntl(fileDescriptor, F_SETFD, flags | FD_CLOEXEC);
                                                 ^
/home/vagrant/ruby-gnome2.win64/webkit2-gtk/tmp/windows/webkitgtk/webkitgtk-2.13.4/Source/WTF/wtf/UniStdExtras.cpp:39:66: error: 'FD_CLOEXEC' was not declared in this scope
             returnValue = fcntl(fileDescriptor, F_SETFD, flags | FD_CLOEXEC);
                                                                  ^
Source/WTF/wtf/CMakeFiles/WTF.dir/build.make:2013: recipe for target 'Source/WTF/wtf/CMakeFiles/WTF.dir/UniStdExtras.cpp.obj' failed
```

I hope that you send a Windows support report to WebKitGTK+ not Ruby-GNOME2.
