### ISSUE TITLE
Strange window titlebar with  set_decorated() on windows

### ISSUE THREAD

**Issue by glurp** [ruby-gnome2/ruby-gnome2#897]
my code: 

``` ruby
require "gtk3"

def populate(win,vbox)
  button = Gtk::Button.new(:label => "Chrome off")
  button.signal_connect("clicked") { win.set_decorated(false)}
  vbox.add(button)
  button = Gtk::Button.new(:label => "Chrome on")
  button.signal_connect("clicked") { win.set_decorated(true) }
  vbox.add(button)
end

app = Gtk::Application.new("org.gtk.example", :flags_none)
app.signal_connect "activate" do |app|
  win = Gtk::ApplicationWindow.new app
  content=  Gtk::Box.new(:vertical)
  win.add content
  populate(win,content)
  win.show_all
end

app.run([$0]+ARGV)
```

Running on Win10 :
![snap08_30_13_23_22](https://cloud.githubusercontent.com/assets/27629/18087446/91978590-6eb5-11e6-8527-b96c56243084.png)

after click on 'Chorme off" :
![snap08_30_13_23_33](https://cloud.githubusercontent.com/assets/27629/18087463/a20ba69a-6eb5-11e6-935b-e81764ef9e2a.png)

**Comment by kou** [comment]
[gtk_window_set_decorated() document](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-decorated) says:

>  Depending on the system, this function may not have any effect when called on a window that is already visible, so you should call it before calling `gtk_widget_show()`.

Try:

```ruby
require "gtk3"

def populate(win,vbox)
  button = Gtk::Button.new(:label => "Chrome off")
  button.signal_connect("clicked") { win.set_decorated(false)}
  vbox.add(button)
  button = Gtk::Button.new(:label => "Chrome on")
  button.signal_connect("clicked") { win.set_decorated(true) }
  vbox.add(button)
end

app = Gtk::Application.new("org.gtk.example", :flags_none)
app.signal_connect "activate" do |app|
  win = Gtk::ApplicationWindow.new app
  content=  Gtk::Box.new(:vertical)
  win.add content
  win.set_decorated(false)
  populate(win,content)
  win.show_all
end

app.run([$0]+ARGV)
```

**Comment by glurp** [comment]
thank you,
I will try, but I get string issues with the 3.1.0 ... (see at gnome2 forum: https://www.ruby-forum.com/topic/6879121#new)

I think that set_decorated() works find dynamically with old gtk version (2015, 3.07).
