### ISSUE TITLE
Manual specification of *.typefile location

### ISSUE THREAD

**Issue by Kagetsuki** [ruby-gnome2/ruby-gnome2#907]
After inclusion, gintrospection attempts to load typefiles from an assumed path. EG:
https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gdk_pixbuf2/lib/gdk_pixbuf2.rb#L25

On environments like Heroku not only do these paths change during the build and deploy process but standard paths like /usr can't be written to. Because of this typefiles are not in the expected location and we get errors like ```GLib::Error: Typelib file for namespace 'Gio' (any version) not found```.

Is it possible to override or manually specify the location of typefiles, EG through an environment variable? Would it be possible to add such an option if not?

**Comment by Kagetsuki** [comment]
After extremely painful investigation I've learned the glib and related libraries available on Heroku cedar-14 are NOT compatible. While ↑ would perhaps make ruby-gnome2 packages more portable it may not actually help anyone and thus implementation may be impractical and unneccessary. Closing issue as it does not need to be handled.

To anyone who stumbles across this and is using Heroku (cedar 14): peg your gems to maximum 3.0.8. EG:
````
gem 'glib2', '3.0.8'
gem 'gdk_pixbuf2', '3.0.8'
gem 'rsvg2', '3.0.8'
```

**Comment by kou** [comment]
You can custom search path for typelib by `GI_TYPELIB_PATH` environment variable.
This Japanese article may help you: http://qiita.com/groonga/items/71b145b37d77bd160bf2#%E6%BA%96%E5%82%99

**Comment by Kagetsuki** [comment]
@kou Good to know! Thanks!

**Comment by kou** [comment]
No problem. :-)
