### ISSUE TITLE
Allow ClutterGdk methods

### ISSUE THREAD

**Issue by dark-yux** [ruby-gnome2/ruby-gnome2#916]
I was trying to get a ClutterStage from a GdkWindow and noticed they were missing.

**Comment by kou** [comment]
Ah, we should also load "ClutterGdk" GI typelib.
It seems that clutter-gtk should do it.

**Comment by kou** [comment]
In the next release, clutter-gdk is added and it's required automatically when you use clutter-gtk.
You can get `ClutterStage` from `GdkWindow` by `Gdk::Window#clutter_stage`.
