### ISSUE TITLE
uninitialized constant Gtk::Socket

### ISSUE THREAD

**Issue by sphynx79** [ruby-gnome2/ruby-gnome2#926]
I need to use Socket to plot graphic from gluplot.
But in gtk 3.0.9 Gtk::Socket.new not work:
C:/Users/en27553/Desktop/Prove/Prova_Plot/.rblcl/lib/ruby/gems/2.3.0/gems/glib2-3.0.9-x64-mingw32/lib/glib2/deprecatable.rb:112:in `const_missing': uninitialized constant Gtk::Socket (NameError)

I use ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32] windows 7.
I try also in mingw64 but same error.

**Comment by kou** [comment]
Could you show a script that reproduces your problem?

**Comment by kou** [comment]
Ah, you're on Windows.
`Gtk::Socket` is available only on X11: https://developer.gnome.org/gtk3/stable/GtkSocket.html#GtkSocket.description

> The GtkPlug and GtkSocket widgets are only available when GTK+ is compiled for the X11 platform and GDK_WINDOWING_X11 is defined. They can only be used on a GdkX11Display. To use GtkPlug and GtkSocket, you need to include the gtk/gtkx.h header.
