### ISSUE TITLE
Source file information in warnings is often not useful

### ISSUE THREAD

**Issue by mvz** [ruby-gnome2/ruby-gnome2#935]
Hello,

The CRITICAL and other messages emitted print the current ruby source file and line number. However, due to the handling of introspected methods, these are often inside gobject-introspection. For example:

```
/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject-introspection/loader.rb: line 114
   Gdk-CRITICAL **:gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
/home/matijs/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject-introspection/loader.rb: line 114
   Gtk-CRITICAL **:gtk_accessible_get_widget: assertion 'GTK_IS_ACCESSIBLE (accessible)' failed
```

Is there any way to improve this information, for example by printing more of the current Ruby callstack?

**Comment by kou** [comment]
Thanks for your suggestion.
I've implemented it.

**Comment by mvz** [comment]
Thanks, @kou!
