### ISSUE TITLE
Updated pixbuf issue?

### ISSUE THREAD

**Issue by Beagle123** [ruby-gnome2/ruby-gnome2#950]
Hi:

I'm the author of visualruby.  Recently, when gtk3 was updated to v 3.0.9, my users are experiencing errors on windows machines.  I'm guessing that it is related to the updated pixbuf class.

WHen you released v 3.0.9, the only changes I made to visualruby, was to update the syntax for the pixbuf class so I wouldn't get the deprecated warinings.  After that, many winows users reported this error:

ERROR:
vr
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.9-x64-mingw32/lib/gobject-introspection/loader.rb:
line 302
   GLib-GObject-WARNING **:attempt to override closure->va_marshal
(0000000063A48970) with new marshal (00000000064A0518)

There are several reports of it here:

https://www.ruby-forum.com/forum/gnome2

I'm sorry that I can't be more specific about the error.  Please let me know if you know anything.

Thanks,
Eric

**Comment by kou** [comment]
It seems that it's a GTK+ problem.
We'll release a new version with new GTK+. Could you try new release after we release it?

**Comment by kou** [comment]
It'll be fixed.
