### ISSUE TITLE
GDateTime

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#955]
@kou,

How should I use a `GDateTime` instance ?

I have a method that returns an object which class gtype is a `GDateTime` but I am not able to use its methods : 

```ruby
commit.author.time.class.gtype # => GDateType
```
when I try to use the format method : (https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format)

```ruby
puts commit.author.time.format("%c")
```

I have this : 

``` 
private method `format' called for #<#<Class:0x00000002b84370>:0x2b84320 ptr=0x2cd3e60 own=true> (NoMethodError)
Did you mean?  Float
```

**Comment by kou** [comment]
Ah, we should create bindings for `GDateTime.

If we create bindings by hand, we should convert `GDateTime` to Ruby's `DateTime` for Rubyish API. But we can't do it in GObject Introspection based bindings. So we need to create bindings for `GDateTime`.

**Comment by cedlemo** [comment]
> So we need to create bindings for GDateTime.

I am interested in doing it.

When do you want to do the next release @kou ?

Should I try to focus on the remaining issues of #943 before ?

**Comment by kou** [comment]
I want to release the next version in this year.

But I couldn't much time until 12/3. I have a talk at [PGConf.ASIA 2016](http://www.pgconf.asia/). :<
So, you can work on `GDateTime`.

**Comment by cedlemo** [comment]
Great, I will do the update of the NEWS too. 

> I have a talk at PGConf.ASIA 2016. :<

I guess this is for Groonga/ PGroonga, I wish you good luck @kou.

**Comment by kou** [comment]
> Great, I will do the update of the NEWS too.

Thanks.

> I guess this is for Groonga/ PGroonga, I wish you good luck @kou.

Right. Thanks! :-)
