### ISSUE TITLE
No doc ?

### ISSUE THREAD

**Issue by Ogromny** [ruby-gnome2/ruby-gnome2#956]
Hi,
I installed gtk2, but when i do 
```sh
ri Gtk::Button
```
I find nothing ? Why ? I don't understand :/

Sorry for my bad English I'm French
Thanks in advance

**Comment by cedlemo** [comment]
Hi Ogromny,

It depends on how you installed your gem. For example I have this file `~/.gemrc` which contains that disable the doc creation when I install the gem : 

```ruby
gem: --no-ri --no-rdoc
```

When I remove it and install the gems, I have access to the ri doc. 

But I think that it won't help you a lot. If you really need a classical doc, you should try to look here _https://ruby-gnome2.osdn.jp/_ . 

You should be aware that gtk2 start to be old and that you really should use gtk3 (the Gnome team is working on gtk4).

If you need information the best way is to use an irb section : 

```ruby
irb -r gtk3
Gtk::Button.signals # => list the signals that Gtk::Button can connect with Gtk::Button#signal_connect
Gtk::Button.properties # => list the properties that you can read /set
Gtk::Button.methods
Gtk::Button.instance_methods.grep(/a_pattern/)
``` 

And read the samples in `gtk3/sample` (create a local copy of this repo `git clone https://github.com/ruby-gnome2/ruby-gnome2.git`): 

Do a `grep "Gtk::Button" *.rb` in this directory.

Then for a particular class you can search for its "rubyish" implementation for example look for a file `gtk3/lib/gtk3/button.rb` :

```ruby
module Gtk
  class Button
    alias_method :initialize_raw, :initialize
    def initialize(options={})
      label = options[:label]
      use_underline = options[:use_underline]
      if use_underline.nil?
        mnemonic = options[:mnemonic]
        if mnemonic
          label = mnemonic
          use_underline = true
        end
      end
      stock = options[:stock_id]
      icon_name = options[:icon_name]
      icon_size = options[:icon_size] || :button

      if label
        if use_underline
          initialize_new_with_mnemonic(label)
        else
          initialize_new_with_label(label)
        end
      elsif stock
        initialize_new_from_stock(stock)
      elsif icon_name
        case icon_size
        when Symbol, String
          icon_size = IconSize.new(icon_size.to_s)
        end
        initialize_new_from_icon_name(icon_name, icon_size)
      else
        initialize_raw
      end
    end
  end
end
``` 

And of course you can ask any questions here. Furthermore your english seems fine but I am french too so this means nothing :)  welcome).

**Comment by Ogromny** [comment]
Merci de ta réponse :D

Je posais la question parce que j'utilise [Intellij](https://www.jetbrains.com/idea/) et que Intellij ne trouve pas les définitions des fonctions/classes/etc de gtk2 :/

![image](http://i.imgur.com/MzabBe4.png)

Donc c'est un peux galère :/

---------
Thanks for you answers :D

I ask the question because I use [Intellij](https://www.jetbrains.com/idea/) and Intellij cannot find the definitions of functions/classes/etc of gtk2 :/

![image](http://i.imgur.com/MzabBe4.png)

**Comment by cedlemo** [comment]
Wow I didn't know about it, I see it costs almost the price of a cheap laptop :) . I don't know how its completion works, but some ruby-gnome2 bindings are built on GObject-introspection, which means that the code is dynamically created (just a few glue code is written) so I guess it will be hard for your IDE to get module, class, methods, attributes information.

**Comment by Ogromny** [comment]
The completion works with rdoc, do you know where I can find the API reference from http://ruby-gnome2.osdn.jp/ to a rdoc format :D ?

**Comment by cedlemo** [comment]
> The completion works with rdoc, do you know where I can find the API reference from http://ruby-gnome2.osdn.jp/ to a rdoc format ?

No I don't know, only @kou update this site so I can not help you more on this.

**Comment by Ogromny** [comment]
Ok thanks ;)

**Comment by kou** [comment]
We never support RDoc format. We may support YARD format. We'll generate YARD format document for GObject Introspection based bindings automatically. `.gir` file has API document. We'll extract them and input them to YARD.

Here is a prototype of the tool: https://sourceforge.net/projects/ruby-gnome2/files/yard/yagi_gnome-0.0.1.pre.gem/download?use_mirror=master

**Comment by cedlemo** [comment]
I didn't know about it. It could be great that you create a repo for it on github.

**Comment by kou** [comment]
It's a good idea.
I've created an empty repository: https://github.com/ruby-gnome2/yard-gobject-introspection

**Comment by cedlemo** [comment]
@kou,
if you don't put at least one file, I can not fork it and send pull request. I have extracted the files from the gem but I have not been able to push them in the repository.

**Comment by kou** [comment]
Oh. I didn't know about it.
I've added you to "ruby-gnome2/developers" team. (Welcome!) Now, you can push it to the repository directly.

Note that we will refer the gem code but will not work with the gem code. Because the gem code is old. It's written before we create gobject-introspection gem. We'll create the feature (GObject Introspection and YARD integration) from scratch.

**Comment by cedlemo** [comment]
> I've added you to "ruby-gnome2/developers" team. (Welcome!)

Thanks a lot .

> Note that we will refer the gem code but will not work with the gem code. Because the gem code is old. It's written before we create gobject-introspection gem. We'll create the feature (GObject Introspection and YARD integration) from scratch.

Ok so no need to push the old files.
