### ISSUE TITLE
gtk-demo and gtk version number

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#967]
@kou,

I am currently working on updating the data files (images, css, ui) in the gtk-demo from the version 3.20 to 3.22. I have seen that some files are renammed with the gtk4 prefix because their started to use the Gtk 4.xx versioning scheme. Knowing that even if they use the Gtk 4.xx it is still Gtk3+ (https://blogs.gnome.org/desrt/2016/06/13/gtk-4-0-is-not-gtk-4/) , should I keep the gtk3 prefix or should I follow their naming convention?

 (FYI keeping the gtk3 prefix will need more work for me, modifying the ui files, the css files and keep track of the differences between our naming rules and theirs).

**Comment by kou** [comment]
OK. We use gtk4 prefix to reduce our works.

**Comment by cedlemo** [comment]
ok thanks
