### ISSUE TITLE
NameError: undefined method `list_schemas' for class `Gio::SettingsSchemaSource'

### ISSUE THREAD

**Issue by andymeneely** [ruby-gnome2/ruby-gnome2#970]
My travis build started failing when 3.1.0 was released. Here's job:

https://travis-ci.org/andymeneely/victory-point-salad/jobs/181255227

In particular, the build fails when [my library does `require 'rsvg2'`](https://github.com/andymeneely/squib/blob/master/lib/squib.rb#L4) 

When I restart a prior build, one that used the 3.0.9 gems, the build fails for the same reason. When I try it out with the 3.0.9 gems it does not fail.

FWIW I can't reproduce this on Windows.

My travis config may be helpful too: 

https://travis-ci.org/andymeneely/victory-point-salad/jobs/181255227/config

A while back I had to add an `apt-get install libgirepository1.0-dev` to get it working - not sure if that factors into this.

**Comment by andymeneely** [comment]
Ah, I see that 45f81794cc502b43b8baa466bf116ad6f895aa37 was put in to fix this issue three days after the 3.1.0 release. I'll lock onto 3.0.9 until that fix is released.

**Comment by kou** [comment]
3.1.1 will fix it.
