### ISSUE TITLE
GdkPixbuf missing #save_to_buffer method in 3.x

### ISSUE THREAD

**Issue by gh2k** [ruby-gnome2/ruby-gnome2#983]
After updating from gdk_pixbuf2 2.2.5, to gdk_pixbuf2 3.1.0, Pixbuf objects are missing the save_to_buffer method. e.g. with irb:

2.2.5:
```
2.2.6 :001 > require 'gdk_pixbuf2'
 => true 
2.2.6 :002 > p = Gdk::Pixbuf.new('kitten.jpg')
 => #<Gdk::Pixbuf:0x10f6080 ptr=0x1938120> 
2.2.6 :003 > p.save_to_buffer('png').length
 => 76896 
```

3.1.0:
```
2.2.6 :001 > require 'gdk_pixbuf2'
 => true 
2.2.6 :002 > p = GdkPixbuf::Pixbuf.new(file: 'kitten.jpg')
 => #<GdkPixbuf::Pixbuf:0x1007b88 ptr=0xcf4d20> 
2.2.6 :003 > p.save_to_buffer('png').length
NoMethodError: undefined method `save_to_buffer' for #<GdkPixbuf::Pixbuf:0x1007b88 ptr=0xcf4d20>
	from (irb):3
	from /home/simon/.rvm/rubies/ruby-2.2.6/bin/irb:11:in `<main>'
```

**Comment by cedlemo** [comment]
@gh2k, 

The 2.2.5 version was C bindings, the 3.1.0 is based on GObject-Introspection that is why there is a difference now. We should be able to implement it, I guess. 

@kou,

Here is the C api of the `gdk_pixbuf_save_to_bufferv` : 

```
gboolean
gdk_pixbuf_save_to_bufferv (GdkPixbuf *pixbuf,
                            gchar **buffer,
                            gsize *buffer_size,
                            const char *type,
                            char **option_keys,
                            char **option_values,
                            GError **error);
```

Correct me if I am wrong but it looks like we will have to use C code in order to implement it.

**Comment by gh2k** [comment]
There's a [reference to it in the gdk_pixbuf2-no-gi](https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gdk_pixbuf2-no-gi/ext/gdk_pixbuf2/rbgdk-pixbuf.c#L410) folder, so I'm wondering if that code can be copied over?

I couldn't figure out how to use gdk_pixbuf2-no-gi in a gem.

**Comment by kou** [comment]
I've implemented `GdkPixbuf::Pixbuf#save_to_buffer` again.
But `#save_to_buffer` is deprecated. You can just do `#save("png")` now.

**Comment by gh2k** [comment]
TIL. :)

That's great, thanks. It's much better because our old code works with deprecation warnings after upgrading, instead of failing in a way that's hard to understand.
