### ISSUE TITLE
cairo scrarch (win10) on window resize  mot solved in 3.1

### ISSUE THREAD

**Issue by AdMachielsen** [ruby-gnome2/ruby-gnome2#986]
Hi,  If I start the drawing.rb program resize the window and the close the window I get an error code.
I copy pasted the relevant part.
-----
D:\Ruby23-x64\lib\ruby\gems\2.3.0\gems\gtk3-3.1.0-x64-mingw32\sample\misc>drawing.rb
Assertion failed!
Program: D:\Ruby23-x64\bin\ruby.exe
File: cairo-surface.c, Line 956
Expression: CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
---
Note I'm actually creating  grayscale image viewer, this program crashes with the some error during windows resizing/

**Comment by kou** [comment]
It'll be fixed by upgrading your cairo gem to the newest version.
