### ISSUE TITLE
PixBuf Clean up issue?

### ISSUE THREAD

**Issue by AdMachielsen** [ruby-gnome2/ruby-gnome2#991]
I create a simple gray scale image viewer, but application crashes after some window sizing operations.
It seems to me that the buffer of the PixBuf is correctly released (unref?).
- Ruby version 2.3.3p222
- GTK3 version 3.1.1

```text
Program error:
-------------------------------------------------------------------------------------------------
D:\Ruby23-x64\extensions\BUG WX>gtk_imageCanvas.rb
1
2
3
4
Assertion failed!
Program: D:\Ruby23-x64\bin\ruby.exe
File: cairo-surface.c, Line 956
Expression: CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
--------------------------------------------------------------------------------------------------
Source Code
--------------------------------------------------------------------------------------------------

```ruby
require 'gtk3'
#========================================================
class ImageCanvas < Gtk::DrawingArea
	def initialize()
		super()
		# simple gray scale 256x256 image
		@image_data = Array.new(256){|r| Array.new(256) {|c| (r+c)}}
		@rgb_str = image_str()
		signal_connect('draw') {|w, cr| draw(w, cr) }
		show_all
	end
	
	#-------------------------------------------------------------------------
	# Convert image data to and "RGB string"
	#-------------------------------------------------------------------------
	def image_str()
		res = []
		@image_data.flatten.each do |v|
			v = 255 if v > 255
			res << v; res << v ; res << v
		end
		res.pack("c*")
	end
	
	#-------------------------------------------------------------------------
	# Calculate new image and draw
	#-------------------------------------------------------------------------
	def draw(wd, cr)
		@count ||= 0
		@count +=1
		puts @count
		image_rgb = GdkPixbuf::Pixbuf.new(
#			:data =>	@rgb_str,		# Variant 1: error when window sizing and closing app
			:data =>	image_str,        # Variant 2: app crashes when window sizing
			:colorspace =>        GdkPixbuf::Colorspace::RGB,
			:has_alpha  =>        false, :bits_per_samples =>  8,
			:width =>             256, :height =>            256,
			:row_stride =>        256 * 3)
		cr.set_source_pixbuf(image_rgb, 0,0)
		cr.paint
		image_rgb.unref # doesn't make a difference
		true
	end
end

#=================================================================
class ImageView < Gtk::Window
	def initialize
		super
		set_title('ImageViewer')
		set_size_request(256, 256)
		add(ImageCanvas.new())
		signal_connect("destroy") { Gtk.main_quit }
		show_all
	end
end
window = ImageView.new
window.show_all
Gtk.main
```
--------------------------------------------------------------------------------------------------
I'm pretty new to WXRuby, so I might forgot essential info, please let me know if I need to clarify
the issue.

Kind regards,
Ad

**Comment by cedlemo** [comment]
@AdMachielsen, have you followed the instructions given by @kou [here](https://github.com/ruby-gnome2/ruby-gnome2/issues/986) ?

FYI you script works well on Linux.

**Comment by AdMachielsen** [comment]
Yes I did, But it didn't solve the issue I had, I thought that the two were related, but after following the instruction my original problem wasn't solved. That why I made the smallest script I could make to show the issue I have.

**Comment by shevegen** [comment]
Works for me on Linux too. Not sure why it does not want to work on windows.

**Comment by ccortiz78** [comment]
I had similar issue, but with gtkmm3 (MSYS2) under windows 7 and windows10.
On window resizing, the same error:

Assertion failed!
Program: D:\Ruby23-x64\bin\ruby.exe
File: cairo-surface.c, Line 956
Expression: CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)

Try to use the Clasic Windows Theme on Windows 7... it is weird, but works for me.

**Comment by kou** [comment]
@ccortiz78 Thanks for your information! It shows that this problem isn't related with Ruby and the Classic Windows Theme. This problem is related with only GTK+ and the current Windows theme.

Did you report this problem to GTK+ developers? If you already did, could you share URL for the report? If you didn't report it, could you report this problem to https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B ? It's better that you provide a program that reproduces this problem.

**Comment by AdMachielsen** [comment]
I'm now using a RUBY 2.4.1p111, and installed the new GTK3.1.6 gem, this combination doesn't show the issue. So from my point of view this issue can be considered solved and closed.

Thanks for all the effort and good work
