### ISSUE TITLE
Is there Gio::Settings.bind_full

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#993]
Is there a way to bind a setting with a widget property like the function `g_settings_bind_with_mapping` ( https://developer.gnome.org/gio/unstable/GSettings.html#g-settings-bind-with-mapping).

I know `Gio::Settings.bind` which works well with boolean setting and checkbox but I would like to link a combobox to a setting and I don't see how to do it.

**Comment by kou** [comment]
I'll look into this after 2017-02-11. I have a talk about gobject-introspection gem in [Nagoya RubyKaigi 03](http://regional.rubykaigi.org/nagoya03/) at 2017-02-11. I need to prepare the talk. Sorry!

**Comment by cedlemo** [comment]
> I need to prepare the talk. Sorry!

It is Ok @kou, no problem.

**Comment by kou** [comment]
Could you show a script that you're working on? I want to use it to try this case.

**Comment by cedlemo** [comment]
> Could you show a script that you're working on? I want to use it to try this case.

It is not a real script, it is my terminal emulator : 

https://github.com/cedlemo/topinambour/blob/master/lib/preferences.rb#L79

In this part I already have linked the g_settings of all the boolean key with a simple Gio::Settings#bind.

But in my prefs dialog, I have comboboxes that I want to bind with the related settings one good example which will be easy to see if it works is the combobox with the id "cursor_shape_sel".

My terminal is really simple : 

    git clone https://github.com/cedlemo/topinambour/

*   lib/preferences.rb  all the code related to the preferences dialog
*   data all the gschema and ui files
*  bin/topinambour the main executable file.

If you prefer, I could create a simpler test script (maybe in the end of the week).

**Comment by kou** [comment]
Thanks.

How about the following? You can use `Gio::Settings.bind` for combo boxes.

```diff
diff --git a/data/gschemas.compiled b/data/gschemas.compiled
index 0cfb74e..a11363e 100644
Binary files a/data/gschemas.compiled and b/data/gschemas.compiled differ
diff --git a/data/topinambour.gschema.xml b/data/topinambour.gschema.xml
index 1b82361..f62f5cb 100644
--- a/data/topinambour.gschema.xml
+++ b/data/topinambour.gschema.xml
@@ -56,5 +56,8 @@
     <key name="mouse-autohide" type="b">
       <default>true</default>
     </key>
+    <key name="cursor-shape" type="i">
+      <default>0</default>
+    </key>
   </schema>
 </schemalist>
diff --git a/lib/preferences.rb b/lib/preferences.rb
index 36ec941..cb665bb 100644
--- a/lib/preferences.rb
+++ b/lib/preferences.rb
@@ -72,6 +72,7 @@ class TopinambourPreferences < Gtk::Window
     bind_switch_state_with_setting(rewrap_on_resize_switch, "rewrap-on-resize")
     bind_switch_state_with_setting(mouse_autohide_switch, "mouse-autohide")
 
+    bind_combo_box_with_setting(cursor_shape_sel, "cursor-shape")
   end
 
   private
@@ -89,4 +90,19 @@ class TopinambourPreferences < Gtk::Window
       false
     end
   end
+
+  def bind_combo_box_with_setting(combo_box, setting)
+    @settings.bind(setting,
+                   combo_box,
+                   "active",
+                   Gio::SettingsBindFlags::DEFAULT)
+    combo_box.signal_connect "changed" do
+      index = combo_box.active
+      m = "#{setting.gsub(/-/,"_")}="
+      @parent.notebook.each do |tab|
+        tab.term.send(m, index)
+      end
+      false
+    end
+  end
 end
```

You can change cursor shape by `gsettings` with this change like the following:

```text
% gsettings --schemadir data set com.github.cedlemo.topinambour cursor-shape 1
```

**Comment by cedlemo** [comment]
It works 👍 

Thanks.
