### ISSUE TITLE
Atk::TextRectangle.new

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/ruby-gnome2#997]
@kou,

in the test file https://github.com/ruby-gnome2/ruby-gnome2/blob/master/atk/test/test-text-rectangle.rb

the creation methods take arguments, should I keep this ? I searched in all the ruby-gnome code and it is not used at all.

**Comment by kou** [comment]
You don't need to care about it.
I'll check it when your work is finished.

**Comment by cedlemo** [comment]
Ok.
